package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsopensearchserverless"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsopensearchserverlessIAccessPolicyRef = interfacesawsopensearchserverless.IAccessPolicyRef
type Type__interfacesawsopensearchserverlessICollectionRef = interfacesawsopensearchserverless.ICollectionRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsopensearchserverlessIIndexRef = interfacesawsopensearchserverless.IIndexRef
type Type__interfacesawsopensearchserverlessILifecyclePolicyRef = interfacesawsopensearchserverless.ILifecyclePolicyRef
type Type__interfacesawsopensearchserverlessISecurityConfigRef = interfacesawsopensearchserverless.ISecurityConfigRef
type Type__interfacesawsopensearchserverlessISecurityPolicyRef = interfacesawsopensearchserverless.ISecurityPolicyRef
type Type__interfacesawsopensearchserverlessIVpcEndpointRef = interfacesawsopensearchserverless.IVpcEndpointRef
