package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsentityresolution"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsentityresolutionIIdMappingWorkflowRef = interfacesawsentityresolution.IIdMappingWorkflowRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsentityresolutionIIdNamespaceRef = interfacesawsentityresolution.IIdNamespaceRef
type Type__interfacesawsentityresolutionIMatchingWorkflowRef = interfacesawsentityresolution.IMatchingWorkflowRef
type Type__interfacesawsentityresolutionIPolicyStatementRef = interfacesawsentityresolution.IPolicyStatementRef
type Type__interfacesawsentityresolutionISchemaMappingRef = interfacesawsentityresolution.ISchemaMappingRef
