package previewawsdynamodbmixins

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTableMixinProps",
		reflect.TypeOf((*CfnGlobalTableMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin",
		reflect.TypeOf((*CfnGlobalTablePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnGlobalTablePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.AttributeDefinitionProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_AttributeDefinitionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.CapacityAutoScalingSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_CapacityAutoScalingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ContributorInsightsSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ContributorInsightsSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.GlobalReadProvisionedThroughputSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_GlobalReadProvisionedThroughputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.GlobalSecondaryIndexProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_GlobalSecondaryIndexProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.GlobalTableWitnessProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_GlobalTableWitnessProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.KeySchemaProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_KeySchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.KinesisStreamSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_KinesisStreamSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.LocalSecondaryIndexProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_LocalSecondaryIndexProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.PointInTimeRecoverySpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_PointInTimeRecoverySpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ProjectionProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ProjectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReadOnDemandThroughputSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReadOnDemandThroughputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReadProvisionedThroughputSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReadProvisionedThroughputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReplicaGlobalSecondaryIndexSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReplicaGlobalSecondaryIndexSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReplicaSSESpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReplicaSSESpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReplicaSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReplicaSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ReplicaStreamSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ReplicaStreamSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.ResourcePolicyProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_ResourcePolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.SSESpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_SSESpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.StreamSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_StreamSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.TargetTrackingScalingPolicyConfigurationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_TargetTrackingScalingPolicyConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.TimeToLiveSpecificationProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_TimeToLiveSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.WarmThroughputProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_WarmThroughputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.WriteOnDemandThroughputSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_WriteOnDemandThroughputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnGlobalTablePropsMixin.WriteProvisionedThroughputSettingsProperty",
		reflect.TypeOf((*CfnGlobalTablePropsMixin_WriteProvisionedThroughputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTableMixinProps",
		reflect.TypeOf((*CfnTableMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin",
		reflect.TypeOf((*CfnTablePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnTablePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.AttributeDefinitionProperty",
		reflect.TypeOf((*CfnTablePropsMixin_AttributeDefinitionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.ContributorInsightsSpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_ContributorInsightsSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.CsvProperty",
		reflect.TypeOf((*CfnTablePropsMixin_CsvProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.GlobalSecondaryIndexProperty",
		reflect.TypeOf((*CfnTablePropsMixin_GlobalSecondaryIndexProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.ImportSourceSpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_ImportSourceSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.InputFormatOptionsProperty",
		reflect.TypeOf((*CfnTablePropsMixin_InputFormatOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.KeySchemaProperty",
		reflect.TypeOf((*CfnTablePropsMixin_KeySchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.KinesisStreamSpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_KinesisStreamSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.LocalSecondaryIndexProperty",
		reflect.TypeOf((*CfnTablePropsMixin_LocalSecondaryIndexProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.OnDemandThroughputProperty",
		reflect.TypeOf((*CfnTablePropsMixin_OnDemandThroughputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.PointInTimeRecoverySpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_PointInTimeRecoverySpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.ProjectionProperty",
		reflect.TypeOf((*CfnTablePropsMixin_ProjectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.ProvisionedThroughputProperty",
		reflect.TypeOf((*CfnTablePropsMixin_ProvisionedThroughputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.ResourcePolicyProperty",
		reflect.TypeOf((*CfnTablePropsMixin_ResourcePolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.S3BucketSourceProperty",
		reflect.TypeOf((*CfnTablePropsMixin_S3BucketSourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.SSESpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_SSESpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.StreamSpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_StreamSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.TimeToLiveSpecificationProperty",
		reflect.TypeOf((*CfnTablePropsMixin_TimeToLiveSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_dynamodb.mixins.CfnTablePropsMixin.WarmThroughputProperty",
		reflect.TypeOf((*CfnTablePropsMixin_WarmThroughputProperty)(nil)).Elem(),
	)
}
