package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsapprunner"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsapprunnerIAutoScalingConfigurationRef = interfacesawsapprunner.IAutoScalingConfigurationRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsapprunnerIObservabilityConfigurationRef = interfacesawsapprunner.IObservabilityConfigurationRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsapprunnerIServiceRef = interfacesawsapprunner.IServiceRef
type Type__interfacesawsapprunnerIVpcConnectorRef = interfacesawsapprunner.IVpcConnectorRef
type Type__interfacesawsapprunnerIVpcIngressConnectionRef = interfacesawsapprunner.IVpcIngressConnectionRef
