package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsobservabilityadmin"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsobservabilityadminIOrganizationCentralizationRuleRef = interfacesawsobservabilityadmin.IOrganizationCentralizationRuleRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsobservabilityadminIOrganizationTelemetryRuleRef = interfacesawsobservabilityadmin.IOrganizationTelemetryRuleRef
type Type__interfacesawsobservabilityadminITelemetryRuleRef = interfacesawsobservabilityadmin.ITelemetryRuleRef
