package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsconnect"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsconnectIAgentStatusRef = interfacesawsconnect.IAgentStatusRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsconnectIApprovedOriginRef = interfacesawsconnect.IApprovedOriginRef
type Type__interfacesawsconnectIContactFlowRef = interfacesawsconnect.IContactFlowRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsconnectIContactFlowModuleRef = interfacesawsconnect.IContactFlowModuleRef
type Type__interfacesawsconnectIContactFlowVersionRef = interfacesawsconnect.IContactFlowVersionRef
type Type__interfacesawsconnectIDataTableRef = interfacesawsconnect.IDataTableRef
type Type__interfacesawsconnectIDataTableAttributeRef = interfacesawsconnect.IDataTableAttributeRef
type Type__interfacesawsconnectIDataTableRecordRef = interfacesawsconnect.IDataTableRecordRef
type Type__interfacesawsconnectIEmailAddressRef = interfacesawsconnect.IEmailAddressRef
type Type__interfacesawsconnectIEvaluationFormRef = interfacesawsconnect.IEvaluationFormRef
type Type__interfacesawsconnectIHoursOfOperationRef = interfacesawsconnect.IHoursOfOperationRef
type Type__interfacesawsconnectIInstanceRef = interfacesawsconnect.IInstanceRef
type Type__interfacesawsconnectIInstanceStorageConfigRef = interfacesawsconnect.IInstanceStorageConfigRef
type Type__interfacesawsconnectIIntegrationAssociationRef = interfacesawsconnect.IIntegrationAssociationRef
type Type__interfacesawsconnectIPhoneNumberRef = interfacesawsconnect.IPhoneNumberRef
type Type__interfacesawsconnectIPredefinedAttributeRef = interfacesawsconnect.IPredefinedAttributeRef
type Type__interfacesawsconnectIPromptRef = interfacesawsconnect.IPromptRef
type Type__interfacesawsconnectIQueueRef = interfacesawsconnect.IQueueRef
type Type__interfacesawsconnectIQuickConnectRef = interfacesawsconnect.IQuickConnectRef
type Type__interfacesawsconnectIRoutingProfileRef = interfacesawsconnect.IRoutingProfileRef
type Type__interfacesawsconnectIRuleRef = interfacesawsconnect.IRuleRef
type Type__interfacesawsconnectISecurityKeyRef = interfacesawsconnect.ISecurityKeyRef
type Type__interfacesawsconnectISecurityProfileRef = interfacesawsconnect.ISecurityProfileRef
type Type__interfacesawsconnectITaskTemplateRef = interfacesawsconnect.ITaskTemplateRef
type Type__interfacesawsconnectITrafficDistributionGroupRef = interfacesawsconnect.ITrafficDistributionGroupRef
type Type__interfacesawsconnectIUserRef = interfacesawsconnect.IUserRef
type Type__interfacesawsconnectIUserHierarchyGroupRef = interfacesawsconnect.IUserHierarchyGroupRef
type Type__interfacesawsconnectIUserHierarchyStructureRef = interfacesawsconnect.IUserHierarchyStructureRef
type Type__interfacesawsconnectIViewRef = interfacesawsconnect.IViewRef
type Type__interfacesawsconnectIViewVersionRef = interfacesawsconnect.IViewVersionRef
type Type__interfacesawsconnectIWorkspaceRef = interfacesawsconnect.IWorkspaceRef
