package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawselasticbeanstalk"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawselasticbeanstalkIApplicationRef = interfacesawselasticbeanstalk.IApplicationRef
type Type__interfacesawselasticbeanstalkIApplicationVersionRef = interfacesawselasticbeanstalk.IApplicationVersionRef
type Type__interfacesawselasticbeanstalkIConfigurationTemplateRef = interfacesawselasticbeanstalk.IConfigurationTemplateRef
type Type__interfacesawselasticbeanstalkIEnvironmentRef = interfacesawselasticbeanstalk.IEnvironmentRef
type Type__awscdkITaggable = awscdk.ITaggable
