package awsappmesh

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRouteMixinProps",
		reflect.TypeOf((*CfnGatewayRouteMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnGatewayRoutePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteHostnameMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteHostnameMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteHostnameRewriteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteHostnameRewriteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteMetadataMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteMetadataMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteRangeMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteRangeMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteSpecProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteTargetProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteTargetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GatewayRouteVirtualServiceProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GatewayRouteVirtualServiceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GrpcGatewayRouteActionProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GrpcGatewayRouteActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GrpcGatewayRouteMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GrpcGatewayRouteMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GrpcGatewayRouteMetadataProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GrpcGatewayRouteMetadataProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GrpcGatewayRouteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GrpcGatewayRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.GrpcGatewayRouteRewriteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_GrpcGatewayRouteRewriteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteActionProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteHeaderMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteHeaderMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteHeaderProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRoutePathRewriteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRoutePathRewriteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRoutePrefixRewriteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRoutePrefixRewriteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpGatewayRouteRewriteProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpGatewayRouteRewriteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpPathMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpPathMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.HttpQueryParameterMatchProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_HttpQueryParameterMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnGatewayRoutePropsMixin.QueryParameterProperty",
		reflect.TypeOf((*CfnGatewayRoutePropsMixin_QueryParameterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnMeshMixinProps",
		reflect.TypeOf((*CfnMeshMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnMeshPropsMixin",
		reflect.TypeOf((*CfnMeshPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnMeshPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnMeshPropsMixin.EgressFilterProperty",
		reflect.TypeOf((*CfnMeshPropsMixin_EgressFilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnMeshPropsMixin.MeshServiceDiscoveryProperty",
		reflect.TypeOf((*CfnMeshPropsMixin_MeshServiceDiscoveryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnMeshPropsMixin.MeshSpecProperty",
		reflect.TypeOf((*CfnMeshPropsMixin_MeshSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRouteMixinProps",
		reflect.TypeOf((*CfnRouteMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin",
		reflect.TypeOf((*CfnRoutePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnRoutePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.DurationProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_DurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRetryPolicyProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRetryPolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRouteActionProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRouteActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRouteMatchProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRouteMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRouteMetadataMatchMethodProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRouteMetadataMatchMethodProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRouteMetadataProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRouteMetadataProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcRouteProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.GrpcTimeoutProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_GrpcTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HeaderMatchMethodProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HeaderMatchMethodProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpPathMatchProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpPathMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpQueryParameterMatchProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpQueryParameterMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpRetryPolicyProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpRetryPolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpRouteActionProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpRouteActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpRouteHeaderProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpRouteHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpRouteMatchProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpRouteMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpRouteProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.HttpTimeoutProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_HttpTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.MatchRangeProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_MatchRangeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.QueryParameterProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_QueryParameterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.RouteSpecProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_RouteSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.TcpRouteActionProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_TcpRouteActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.TcpRouteMatchProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_TcpRouteMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.TcpRouteProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_TcpRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.TcpTimeoutProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_TcpTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnRoutePropsMixin.WeightedTargetProperty",
		reflect.TypeOf((*CfnRoutePropsMixin_WeightedTargetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayMixinProps",
		reflect.TypeOf((*CfnVirtualGatewayMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnVirtualGatewayPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.JsonFormatRefProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_JsonFormatRefProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.LoggingFormatProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_LoggingFormatProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.SubjectAlternativeNameMatchersProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_SubjectAlternativeNameMatchersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.SubjectAlternativeNamesProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_SubjectAlternativeNamesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayAccessLogProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayAccessLogProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayBackendDefaultsProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayBackendDefaultsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayClientPolicyProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayClientPolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayClientPolicyTlsProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayClientPolicyTlsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayClientTlsCertificateProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayClientTlsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayFileAccessLogProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayFileAccessLogProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayGrpcConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayGrpcConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayHealthCheckPolicyProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayHealthCheckPolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayHttp2ConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayHttp2ConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayHttpConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayHttpConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsAcmCertificateProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsAcmCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsCertificateProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsFileCertificateProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsFileCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsSdsCertificateProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsSdsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsValidationContextProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsValidationContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayListenerTlsValidationContextTrustProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayListenerTlsValidationContextTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayLoggingProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayLoggingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayPortMappingProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayPortMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewaySpecProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewaySpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayTlsValidationContextAcmTrustProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayTlsValidationContextAcmTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayTlsValidationContextFileTrustProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayTlsValidationContextFileTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayTlsValidationContextProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayTlsValidationContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayTlsValidationContextSdsTrustProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayTlsValidationContextSdsTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualGatewayPropsMixin.VirtualGatewayTlsValidationContextTrustProperty",
		reflect.TypeOf((*CfnVirtualGatewayPropsMixin_VirtualGatewayTlsValidationContextTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodeMixinProps",
		reflect.TypeOf((*CfnVirtualNodeMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin",
		reflect.TypeOf((*CfnVirtualNodePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnVirtualNodePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.AccessLogProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_AccessLogProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.AwsCloudMapInstanceAttributeProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_AwsCloudMapInstanceAttributeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.AwsCloudMapServiceDiscoveryProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_AwsCloudMapServiceDiscoveryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.BackendDefaultsProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_BackendDefaultsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.BackendProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_BackendProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ClientPolicyProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ClientPolicyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ClientPolicyTlsProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ClientPolicyTlsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ClientTlsCertificateProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ClientTlsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.DnsServiceDiscoveryProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_DnsServiceDiscoveryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.DurationProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_DurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.FileAccessLogProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_FileAccessLogProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.GrpcTimeoutProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_GrpcTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.HealthCheckProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_HealthCheckProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.HttpTimeoutProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_HttpTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.JsonFormatRefProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_JsonFormatRefProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTimeoutProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsAcmCertificateProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsAcmCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsCertificateProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsFileCertificateProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsFileCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsSdsCertificateProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsSdsCertificateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsValidationContextProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsValidationContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ListenerTlsValidationContextTrustProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ListenerTlsValidationContextTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.LoggingFormatProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_LoggingFormatProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.LoggingProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_LoggingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.OutlierDetectionProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_OutlierDetectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.PortMappingProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_PortMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.ServiceDiscoveryProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_ServiceDiscoveryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.SubjectAlternativeNameMatchersProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_SubjectAlternativeNameMatchersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.SubjectAlternativeNamesProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_SubjectAlternativeNamesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TcpTimeoutProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TcpTimeoutProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TlsValidationContextAcmTrustProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TlsValidationContextAcmTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TlsValidationContextFileTrustProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TlsValidationContextFileTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TlsValidationContextProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TlsValidationContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TlsValidationContextSdsTrustProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TlsValidationContextSdsTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.TlsValidationContextTrustProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_TlsValidationContextTrustProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeGrpcConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeGrpcConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeHttp2ConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeHttp2ConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeHttpConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeHttpConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeSpecProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualNodeTcpConnectionPoolProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualNodeTcpConnectionPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualNodePropsMixin.VirtualServiceBackendProperty",
		reflect.TypeOf((*CfnVirtualNodePropsMixin_VirtualServiceBackendProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualRouterMixinProps",
		reflect.TypeOf((*CfnVirtualRouterMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualRouterPropsMixin",
		reflect.TypeOf((*CfnVirtualRouterPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnVirtualRouterPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualRouterPropsMixin.PortMappingProperty",
		reflect.TypeOf((*CfnVirtualRouterPropsMixin_PortMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualRouterPropsMixin.VirtualRouterListenerProperty",
		reflect.TypeOf((*CfnVirtualRouterPropsMixin_VirtualRouterListenerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualRouterPropsMixin.VirtualRouterSpecProperty",
		reflect.TypeOf((*CfnVirtualRouterPropsMixin_VirtualRouterSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServiceMixinProps",
		reflect.TypeOf((*CfnVirtualServiceMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServicePropsMixin",
		reflect.TypeOf((*CfnVirtualServicePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnVirtualServicePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServicePropsMixin.VirtualNodeServiceProviderProperty",
		reflect.TypeOf((*CfnVirtualServicePropsMixin_VirtualNodeServiceProviderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServicePropsMixin.VirtualRouterServiceProviderProperty",
		reflect.TypeOf((*CfnVirtualServicePropsMixin_VirtualRouterServiceProviderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServicePropsMixin.VirtualServiceProviderProperty",
		reflect.TypeOf((*CfnVirtualServicePropsMixin_VirtualServiceProviderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_appmesh.CfnVirtualServicePropsMixin.VirtualServiceSpecProperty",
		reflect.TypeOf((*CfnVirtualServicePropsMixin_VirtualServiceSpecProperty)(nil)).Elem(),
	)
}
