package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsfrauddetector"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsfrauddetectorIDetectorRef = interfacesawsfrauddetector.IDetectorRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsfrauddetectorIEntityTypeRef = interfacesawsfrauddetector.IEntityTypeRef
type Type__interfacesawsfrauddetectorIEventTypeRef = interfacesawsfrauddetector.IEventTypeRef
type Type__interfacesawsfrauddetectorILabelRef = interfacesawsfrauddetector.ILabelRef
type Type__interfacesawsfrauddetectorIListRef = interfacesawsfrauddetector.IListRef
type Type__interfacesawsfrauddetectorIOutcomeRef = interfacesawsfrauddetector.IOutcomeRef
type Type__interfacesawsfrauddetectorIVariableRef = interfacesawsfrauddetector.IVariableRef
