package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawspersonalize"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawspersonalizeIDatasetRef = interfacesawspersonalize.IDatasetRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawspersonalizeIDatasetGroupRef = interfacesawspersonalize.IDatasetGroupRef
type Type__interfacesawspersonalizeIEventTrackerRef = interfacesawspersonalize.IEventTrackerRef
type Type__interfacesawspersonalizeIMetricAttributionRef = interfacesawspersonalize.IMetricAttributionRef
type Type__interfacesawspersonalizeISchemaRef = interfacesawspersonalize.ISchemaRef
type Type__interfacesawspersonalizeISolutionRef = interfacesawspersonalize.ISolutionRef
