package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsquicksight"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsquicksightIActionConnectorRef = interfacesawsquicksight.IActionConnectorRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsquicksightIAnalysisRef = interfacesawsquicksight.IAnalysisRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsquicksightICustomPermissionsRef = interfacesawsquicksight.ICustomPermissionsRef
type Type__interfacesawsquicksightIDashboardRef = interfacesawsquicksight.IDashboardRef
type Type__interfacesawsquicksightIDataSetRef = interfacesawsquicksight.IDataSetRef
type Type__interfacesawsquicksightIDataSourceRef = interfacesawsquicksight.IDataSourceRef
type Type__interfacesawsquicksightIFolderRef = interfacesawsquicksight.IFolderRef
type Type__interfacesawsquicksightIRefreshScheduleRef = interfacesawsquicksight.IRefreshScheduleRef
type Type__interfacesawsquicksightITemplateRef = interfacesawsquicksight.ITemplateRef
type Type__interfacesawsquicksightIThemeRef = interfacesawsquicksight.IThemeRef
type Type__interfacesawsquicksightITopicRef = interfacesawsquicksight.ITopicRef
type Type__interfacesawsquicksightIVPCConnectionRef = interfacesawsquicksight.IVPCConnectionRef
