package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawssagemaker"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawssagemakerIAppRef = interfacesawssagemaker.IAppRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawssagemakerIAppImageConfigRef = interfacesawssagemaker.IAppImageConfigRef
type Type__interfacesawssagemakerIClusterRef = interfacesawssagemaker.IClusterRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawssagemakerICodeRepositoryRef = interfacesawssagemaker.ICodeRepositoryRef
type Type__interfacesawssagemakerIDataQualityJobDefinitionRef = interfacesawssagemaker.IDataQualityJobDefinitionRef
type Type__interfacesawssagemakerIDeviceRef = interfacesawssagemaker.IDeviceRef
type Type__interfacesawssagemakerIDeviceFleetRef = interfacesawssagemaker.IDeviceFleetRef
type Type__interfacesawssagemakerIDomainRef = interfacesawssagemaker.IDomainRef
type Type__interfacesawssagemakerIEndpointRef = interfacesawssagemaker.IEndpointRef
type Type__interfacesawssagemakerIEndpointConfigRef = interfacesawssagemaker.IEndpointConfigRef
type Type__interfacesawssagemakerIFeatureGroupRef = interfacesawssagemaker.IFeatureGroupRef
type Type__interfacesawssagemakerIImageRef = interfacesawssagemaker.IImageRef
type Type__interfacesawssagemakerIImageVersionRef = interfacesawssagemaker.IImageVersionRef
type Type__interfacesawssagemakerIInferenceComponentRef = interfacesawssagemaker.IInferenceComponentRef
type Type__interfacesawssagemakerIInferenceExperimentRef = interfacesawssagemaker.IInferenceExperimentRef
type Type__interfacesawssagemakerIMlflowTrackingServerRef = interfacesawssagemaker.IMlflowTrackingServerRef
type Type__interfacesawssagemakerIModelRef = interfacesawssagemaker.IModelRef
type Type__interfacesawssagemakerIModelBiasJobDefinitionRef = interfacesawssagemaker.IModelBiasJobDefinitionRef
type Type__interfacesawssagemakerIModelCardRef = interfacesawssagemaker.IModelCardRef
type Type__interfacesawssagemakerIModelExplainabilityJobDefinitionRef = interfacesawssagemaker.IModelExplainabilityJobDefinitionRef
type Type__interfacesawssagemakerIModelPackageRef = interfacesawssagemaker.IModelPackageRef
type Type__interfacesawssagemakerIModelPackageGroupRef = interfacesawssagemaker.IModelPackageGroupRef
type Type__interfacesawssagemakerIModelQualityJobDefinitionRef = interfacesawssagemaker.IModelQualityJobDefinitionRef
type Type__interfacesawssagemakerIMonitoringScheduleRef = interfacesawssagemaker.IMonitoringScheduleRef
type Type__interfacesawssagemakerINotebookInstanceRef = interfacesawssagemaker.INotebookInstanceRef
type Type__interfacesawssagemakerINotebookInstanceLifecycleConfigRef = interfacesawssagemaker.INotebookInstanceLifecycleConfigRef
type Type__interfacesawssagemakerIPartnerAppRef = interfacesawssagemaker.IPartnerAppRef
type Type__interfacesawssagemakerIPipelineRef = interfacesawssagemaker.IPipelineRef
type Type__interfacesawssagemakerIProcessingJobRef = interfacesawssagemaker.IProcessingJobRef
type Type__interfacesawssagemakerIProjectRef = interfacesawssagemaker.IProjectRef
type Type__interfacesawssagemakerISpaceRef = interfacesawssagemaker.ISpaceRef
type Type__interfacesawssagemakerIStudioLifecycleConfigRef = interfacesawssagemaker.IStudioLifecycleConfigRef
type Type__interfacesawssagemakerIUserProfileRef = interfacesawssagemaker.IUserProfileRef
type Type__interfacesawssagemakerIWorkteamRef = interfacesawssagemaker.IWorkteamRef
type Type__awscdkIResource = awscdk.IResource
