package previewawskendramixins

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourceMixinProps",
		reflect.TypeOf((*CfnDataSourceMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin",
		reflect.TypeOf((*CfnDataSourcePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnDataSourcePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.AccessControlListConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_AccessControlListConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.AclConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_AclConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ColumnConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ColumnConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceAttachmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceAttachmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceAttachmentToIndexFieldMappingProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceAttachmentToIndexFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceBlogConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceBlogConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceBlogToIndexFieldMappingProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceBlogToIndexFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluencePageConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluencePageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluencePageToIndexFieldMappingProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluencePageToIndexFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceSpaceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceSpaceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConfluenceSpaceToIndexFieldMappingProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceSpaceToIndexFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ConnectionConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.CustomDocumentEnrichmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_CustomDocumentEnrichmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DataSourceToIndexFieldMappingProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DataSourceToIndexFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DataSourceVpcConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DataSourceVpcConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DatabaseConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DatabaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DocumentAttributeConditionProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DocumentAttributeConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DocumentAttributeTargetProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DocumentAttributeTargetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DocumentAttributeValueProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DocumentAttributeValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.DocumentsMetadataConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DocumentsMetadataConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.GoogleDriveConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_GoogleDriveConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.HookConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_HookConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.InlineCustomDocumentEnrichmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_InlineCustomDocumentEnrichmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.OneDriveConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_OneDriveConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.OneDriveUsersProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_OneDriveUsersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ProxyConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ProxyConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.S3DataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_S3DataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.S3PathProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_S3PathProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceChatterFeedConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceChatterFeedConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceCustomKnowledgeArticleTypeConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceCustomKnowledgeArticleTypeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceKnowledgeArticleConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceKnowledgeArticleConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceStandardKnowledgeArticleTypeConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceStandardKnowledgeArticleTypeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceStandardObjectAttachmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceStandardObjectAttachmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SalesforceStandardObjectConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceStandardObjectConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ServiceNowConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ServiceNowConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ServiceNowKnowledgeArticleConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ServiceNowKnowledgeArticleConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.ServiceNowServiceCatalogConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ServiceNowServiceCatalogConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SharePointConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SharePointConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.SqlConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SqlConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.TemplateConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_TemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerAuthenticationConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerAuthenticationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerBasicAuthenticationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerBasicAuthenticationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerSeedUrlConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerSeedUrlConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerSiteMapsConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerSiteMapsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WebCrawlerUrlsProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerUrlsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnDataSourcePropsMixin.WorkDocsConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WorkDocsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnFaqMixinProps",
		reflect.TypeOf((*CfnFaqMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnFaqPropsMixin",
		reflect.TypeOf((*CfnFaqPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnFaqPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnFaqPropsMixin.S3PathProperty",
		reflect.TypeOf((*CfnFaqPropsMixin_S3PathProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexMixinProps",
		reflect.TypeOf((*CfnIndexMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin",
		reflect.TypeOf((*CfnIndexPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnIndexPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.CapacityUnitsConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_CapacityUnitsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.DocumentMetadataConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_DocumentMetadataConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.JsonTokenTypeConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_JsonTokenTypeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.JwtTokenTypeConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_JwtTokenTypeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.RelevanceProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_RelevanceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.SearchProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_SearchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.ServerSideEncryptionConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_ServerSideEncryptionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.UserTokenConfigurationProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_UserTokenConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kendra.mixins.CfnIndexPropsMixin.ValueImportanceItemProperty",
		reflect.TypeOf((*CfnIndexPropsMixin_ValueImportanceItemProperty)(nil)).Elem(),
	)
}
