package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawscleanrooms"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawscleanroomsIAnalysisTemplateRef = interfacesawscleanrooms.IAnalysisTemplateRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawscleanroomsICollaborationRef = interfacesawscleanrooms.ICollaborationRef
type Type__interfacesawscleanroomsIConfiguredTableRef = interfacesawscleanrooms.IConfiguredTableRef
type Type__interfacesawscleanroomsIConfiguredTableAssociationRef = interfacesawscleanrooms.IConfiguredTableAssociationRef
type Type__interfacesawscleanroomsIIdMappingTableRef = interfacesawscleanrooms.IIdMappingTableRef
type Type__interfacesawscleanroomsIIdNamespaceAssociationRef = interfacesawscleanrooms.IIdNamespaceAssociationRef
type Type__interfacesawscleanroomsIMembershipRef = interfacesawscleanrooms.IMembershipRef
type Type__interfacesawscleanroomsIPrivacyBudgetTemplateRef = interfacesawscleanrooms.IPrivacyBudgetTemplateRef
