package mixinsawsappflow

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorMixinProps",
		reflect.TypeOf((*CfnConnectorMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfileMixinProps",
		reflect.TypeOf((*CfnConnectorProfileMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnConnectorProfilePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.AmplitudeConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_AmplitudeConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ApiKeyCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ApiKeyCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.BasicAuthCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_BasicAuthCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ConnectorOAuthRequestProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ConnectorOAuthRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ConnectorProfileConfigProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ConnectorProfileConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.CustomAuthCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_CustomAuthCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.CustomConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_CustomConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.CustomConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_CustomConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.DatadogConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_DatadogConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.DatadogConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_DatadogConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.DynatraceConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_DynatraceConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.DynatraceConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_DynatraceConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.GoogleAnalyticsConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_GoogleAnalyticsConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.InforNexusConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_InforNexusConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.InforNexusConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_InforNexusConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.MarketoConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_MarketoConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.MarketoConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_MarketoConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.OAuth2CredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_OAuth2CredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.OAuth2PropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_OAuth2PropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.OAuthCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_OAuthCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.OAuthPropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_OAuthPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.PardotConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_PardotConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.PardotConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_PardotConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.RedshiftConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_RedshiftConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.RedshiftConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_RedshiftConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SAPODataConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SAPODataConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SAPODataConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SAPODataConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SalesforceConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SalesforceConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SalesforceConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SalesforceConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ServiceNowConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ServiceNowConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ServiceNowConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ServiceNowConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SingularConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SingularConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SlackConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SlackConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SlackConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SlackConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SnowflakeConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SnowflakeConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.SnowflakeConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_SnowflakeConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.TrendmicroConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_TrendmicroConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.VeevaConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_VeevaConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.VeevaConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_VeevaConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ZendeskConnectorProfileCredentialsProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ZendeskConnectorProfileCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorProfilePropsMixin.ZendeskConnectorProfilePropertiesProperty",
		reflect.TypeOf((*CfnConnectorProfilePropsMixin_ZendeskConnectorProfilePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorPropsMixin",
		reflect.TypeOf((*CfnConnectorPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnConnectorPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorPropsMixin.ConnectorProvisioningConfigProperty",
		reflect.TypeOf((*CfnConnectorPropsMixin_ConnectorProvisioningConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnConnectorPropsMixin.LambdaConnectorProvisioningConfigProperty",
		reflect.TypeOf((*CfnConnectorPropsMixin_LambdaConnectorProvisioningConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowMixinProps",
		reflect.TypeOf((*CfnFlowMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin",
		reflect.TypeOf((*CfnFlowPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnFlowPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.AggregationConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_AggregationConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.AmplitudeSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_AmplitudeSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ConnectorOperatorProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ConnectorOperatorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.CustomConnectorDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_CustomConnectorDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.CustomConnectorSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_CustomConnectorSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.DataTransferApiProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_DataTransferApiProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.DatadogSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_DatadogSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.DestinationConnectorPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_DestinationConnectorPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.DestinationFlowConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_DestinationFlowConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.DynatraceSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_DynatraceSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ErrorHandlingConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ErrorHandlingConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.EventBridgeDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_EventBridgeDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.GlueDataCatalogProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_GlueDataCatalogProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.GoogleAnalyticsSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_GoogleAnalyticsSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.IncrementalPullConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_IncrementalPullConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.InforNexusSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_InforNexusSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.LookoutMetricsDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_LookoutMetricsDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.MarketoDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_MarketoDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.MarketoSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_MarketoSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.MetadataCatalogConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_MetadataCatalogConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.PardotSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PardotSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.PrefixConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PrefixConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.RedshiftDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_RedshiftDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.S3DestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_S3DestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.S3InputFormatConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_S3InputFormatConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.S3OutputFormatConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_S3OutputFormatConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.S3SourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_S3SourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SAPODataDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SAPODataDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SAPODataPaginationConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SAPODataPaginationConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SAPODataParallelismConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SAPODataParallelismConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SAPODataSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SAPODataSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SalesforceDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SalesforceDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SalesforceSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SalesforceSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ScheduledTriggerPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ScheduledTriggerPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ServiceNowSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ServiceNowSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SingularSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SingularSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SlackSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SlackSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SnowflakeDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SnowflakeDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SourceConnectorPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SourceConnectorPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SourceFlowConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SourceFlowConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.SuccessResponseHandlingConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_SuccessResponseHandlingConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.TaskPropertiesObjectProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_TaskPropertiesObjectProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.TaskProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_TaskProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.TrendmicroSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_TrendmicroSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.TriggerConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_TriggerConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.UpsolverDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_UpsolverDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.UpsolverS3OutputFormatConfigProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_UpsolverS3OutputFormatConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.VeevaSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_VeevaSourcePropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ZendeskDestinationPropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ZendeskDestinationPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_appflow.mixins.CfnFlowPropsMixin.ZendeskSourcePropertiesProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ZendeskSourcePropertiesProperty)(nil)).Elem(),
	)
}
