package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsbedrockagentcore"
)
type Type__awscdkResource = awscdk.Resource
type Type__awsec2IConnectable = awsec2.IConnectable
type Type__awsiamIGrantable = awsiam.IGrantable
type Type__awscdkIResource = awscdk.IResource
type Type__interfacesawsbedrockagentcoreIRuntimeRef = interfacesawsbedrockagentcore.IRuntimeRef
type Type__interfacesawsbedrockagentcoreIBrowserCustomRef = interfacesawsbedrockagentcore.IBrowserCustomRef
type Type__interfacesawsbedrockagentcoreICodeInterpreterCustomRef = interfacesawsbedrockagentcore.ICodeInterpreterCustomRef
type Type__interfacesawsbedrockagentcoreIEvaluatorRef = interfacesawsbedrockagentcore.IEvaluatorRef
type Type__interfacesawsbedrockagentcoreIGatewayRef = interfacesawsbedrockagentcore.IGatewayRef
type Type__interfacesawsbedrockagentcoreIGatewayTargetRef = interfacesawsbedrockagentcore.IGatewayTargetRef
type Type__interfacesawsbedrockagentcoreIMemoryRef = interfacesawsbedrockagentcore.IMemoryRef
type Type__interfacesawsbedrockagentcoreIOnlineEvaluationConfigRef = interfacesawsbedrockagentcore.IOnlineEvaluationConfigRef
type Type__interfacesawsbedrockagentcoreIPolicyRef = interfacesawsbedrockagentcore.IPolicyRef
type Type__interfacesawsbedrockagentcoreIPolicyEngineRef = interfacesawsbedrockagentcore.IPolicyEngineRef
type Type__interfacesawsbedrockagentcoreIRuntimeEndpointRef = interfacesawsbedrockagentcore.IRuntimeEndpointRef
