//go:build no_runtime_type_checking

package previewawssagemakerevents

// Building without runtime type checking enabled, so all the below just return nil

func validateSageMakerModelBuildingPipelineExecutionStepStatusChange_SageMakerModelBuildingPipelineExecutionStepStatusChangePatternParameters(options *SageMakerModelBuildingPipelineExecutionStepStatusChange_SageMakerModelBuildingPipelineExecutionStepStatusChangeProps) error {
	return nil
}

