package internal
import (
	"github.com/aws/aws-cdk-go/awscdkapigatewayv2alpha/v2"
)
type Type__awscdkapigatewayv2alphaIHttpRouteIntegration = awscdkapigatewayv2alpha.IHttpRouteIntegration
type Type__awscdkapigatewayv2alphaIWebSocketRouteIntegration = awscdkapigatewayv2alpha.IWebSocketRouteIntegration
