package previewawseksmixins


// Experimental.
type CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields string

const (
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_STREAM CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "STREAM"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_LEVEL CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "LEVEL"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_MESSAGE CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "MESSAGE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_ERROR CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "ERROR"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_CONTROLLER CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "CONTROLLER"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_CONTROLLERGROUP CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "CONTROLLERGROUP"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_CONTROLLERKIND CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "CONTROLLERKIND"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_RECONCILEID CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "RECONCILEID"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_WORKER_COUNT CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "WORKER_COUNT"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_NAME CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "NAME"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_NAMESPACE CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "NAMESPACE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_APPLICATION CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "APPLICATION"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_APP_NAMESPACE CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "APP_NAMESPACE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_PROJECT CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "PROJECT"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_APPLICATIONSET CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "APPLICATIONSET"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_ACTION CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "ACTION"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_COUNT CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "COUNT"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_REQUEUEAFTER CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "REQUEUEAFTER"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_TYPE CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "TYPE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_RESOURCE_ARN CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "RESOURCE_ARN"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields_EVENT_TIMESTAMP CfnCapabilityEksCapabilityArgocdApplicationsetLogsRecordFields = "EVENT_TIMESTAMP"
)

