package previewawseksmixins


// Experimental.
type CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields string

const (
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_STREAM CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "STREAM"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_LEVEL CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "LEVEL"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_MSG CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "MSG"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_ERROR CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "ERROR"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_APPLICATION CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "APPLICATION"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_APP_NAMESPACE CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "APP_NAMESPACE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_PROJECT CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "PROJECT"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_DEST_SERVER CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "DEST_SERVER"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_DEST_NAMESPACE CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "DEST_NAMESPACE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_DEST_NAME CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "DEST_NAME"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_COMPARISON_LEVEL CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "COMPARISON_LEVEL"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_TIME_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "TIME_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_PATCH_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "PATCH_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_SETOP_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "SETOP_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_COMPARE_APP_STATE_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "COMPARE_APP_STATE_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_REFRESH_APP_CONDITIONS_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "REFRESH_APP_CONDITIONS_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_PROCESS_REFRESH_APP_CONDITIONS_ERRORS_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "PROCESS_REFRESH_APP_CONDITIONS_ERRORS_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_COMPARISON_WITH_NOTHING_MS CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "COMPARISON_WITH_NOTHING_MS"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_RESOURCE_ARN CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "RESOURCE_ARN"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields_EVENT_TIMESTAMP CfnCapabilityEksCapabilityArgocdApplicationLogsRecordFields = "EVENT_TIMESTAMP"
)

