package previewawseksmixins


// Experimental.
type CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields string

const (
	// Experimental.
	CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields_STREAM CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields = "STREAM"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields_LEVEL CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields = "LEVEL"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields_MESSAGE CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields = "MESSAGE"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields_RESOURCE_ARN CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields = "RESOURCE_ARN"
	// Experimental.
	CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields_EVENT_TIMESTAMP CfnCapabilityEksCapabilityArgocdCommitserverLogsRecordFields = "EVENT_TIMESTAMP"
)

