package previewawsguarddutyevents

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents",
		reflect.TypeOf((*DetectorEvents)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "guardDutyFindingPattern", GoMethod: "GuardDutyFindingPattern"},
		},
		func() interface{} {
			return &jsiiProxy_DetectorEvents{}
		},
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DetectorEvents_GuardDutyFinding{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AccessControlList",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AccessControlList)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AccessKeyDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AccessKeyDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AccountLevelPermissions",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AccountLevelPermissions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Action",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Action)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AdditionalInfo",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AdditionalInfo)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AdditionalInfoItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AdditionalInfoItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AdditionalInfoItem1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AdditionalInfoItem1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AffectedResources1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AffectedResources1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Anomalies",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Anomalies)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AwsApiCallAction",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AwsApiCallAction)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.AwsApiCallAction1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_AwsApiCallAction1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.BlockPublicAccess",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_BlockPublicAccess)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.BucketLevelPermissions",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_BucketLevelPermissions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.City",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_City)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.City1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_City1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.City2",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_City2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.City3",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_City3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.City4",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_City4)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ContainerDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ContainerDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Country",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Country)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Country1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Country1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Country2",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Country2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Country3",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Country3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Country4",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Country4)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.DefaultServerSideEncryption",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_DefaultServerSideEncryption)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.DnsRequestAction",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_DnsRequestAction)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EbsVolumeDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EbsVolumeDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EbsVolumeDetailsItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EbsVolumeDetailsItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EbsVolumeScanDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EbsVolumeScanDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EcsClusterDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EcsClusterDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EcsClusterDetailsItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EcsClusterDetailsItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EksClusterDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EksClusterDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Evidence",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Evidence)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.EvidenceItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_EvidenceItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.GeoLocation",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_GeoLocation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.GeoLocation1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_GeoLocation1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.GuardDutyFindingProps",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_GuardDutyFindingProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.HighestSeverityThreatDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_HighestSeverityThreatDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.IamInstanceProfile",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_IamInstanceProfile)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.InstanceDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_InstanceDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.InstanceDetailsItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_InstanceDetailsItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.InstanceDetailsItem1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_InstanceDetailsItem1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.InstanceDetailsItemItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_InstanceDetailsItemItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.InstanceDetailsItemItem1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_InstanceDetailsItemItem1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.KubernetesApiCallAction",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_KubernetesApiCallAction)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.KubernetesDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_KubernetesDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.KubernetesUserDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_KubernetesUserDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.KubernetesWorkloadDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_KubernetesWorkloadDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.KubernetesWorkloadDetailsItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_KubernetesWorkloadDetailsItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.LocalIpDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_LocalIpDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.LocalIpDetails1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_LocalIpDetails1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.LocalPortDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_LocalPortDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.LocalPortDetails1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_LocalPortDetails1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.NetworkConnectionAction",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_NetworkConnectionAction)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.NewPolicy",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_NewPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.OldPolicy",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_OldPolicy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Organization",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Organization)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Organization1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Organization1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Organization2",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Organization2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Organization3",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Organization3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Organization4",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Organization4)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Owner",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Owner)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.PermissionConfiguration",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_PermissionConfiguration)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.PortProbeAction",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_PortProbeAction)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.PortProbeActionItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_PortProbeActionItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ProfiledBehavior",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ProfiledBehavior)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.PublicAccess",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_PublicAccess)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteAccountDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteAccountDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteIpDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteIpDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteIpDetails1",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteIpDetails1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteIpDetails2",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteIpDetails2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteIpDetails3",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteIpDetails3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemoteIpDetails4",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemoteIpDetails4)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.RemotePortDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_RemotePortDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Resource",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Resource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ResourceItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ResourceItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ScanDetections",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ScanDetections)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ScannedItemCount",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ScannedItemCount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.SecurityContext",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_SecurityContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.Service",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_Service)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.TaskDetails",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_TaskDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.TaskDetailsItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_TaskDetailsItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ThreatDetectedByName",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ThreatDetectedByName)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ThreatDetectedByNameItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ThreatDetectedByNameItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ThreatDetectedByNameItemItem",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ThreatDetectedByNameItemItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.ThreatsDetectedItemCount",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_ThreatsDetectedItemCount)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.UnusualBehavior",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_UnusualBehavior)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_guardduty.events.DetectorEvents.GuardDutyFinding.UserAgent",
		reflect.TypeOf((*DetectorEvents_GuardDutyFinding_UserAgent)(nil)).Elem(),
	)
}
