package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsiotfleetwise"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsiotfleetwiseICampaignRef = interfacesawsiotfleetwise.ICampaignRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsiotfleetwiseIDecoderManifestRef = interfacesawsiotfleetwise.IDecoderManifestRef
type Type__interfacesawsiotfleetwiseIFleetRef = interfacesawsiotfleetwise.IFleetRef
type Type__interfacesawsiotfleetwiseIModelManifestRef = interfacesawsiotfleetwise.IModelManifestRef
type Type__interfacesawsiotfleetwiseISignalCatalogRef = interfacesawsiotfleetwise.ISignalCatalogRef
type Type__interfacesawsiotfleetwiseIStateTemplateRef = interfacesawsiotfleetwise.IStateTemplateRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsiotfleetwiseIVehicleRef = interfacesawsiotfleetwise.IVehicleRef
