//go:build no_runtime_type_checking

package previewawsroute53recoveryreadinessevents

// Building without runtime type checking enabled, so all the below just return nil

func validateRoute53ApplicationRecoveryControllerReadinessCheckStatusChange_Route53ApplicationRecoveryControllerReadinessCheckStatusChangePatternParameters(options *Route53ApplicationRecoveryControllerReadinessCheckStatusChange_Route53ApplicationRecoveryControllerReadinessCheckStatusChangeProps) error {
	return nil
}

