//go:build no_runtime_type_checking

package previewawsroute53recoveryreadinessevents

// Building without runtime type checking enabled, so all the below just return nil

func validateRoute53ApplicationRecoveryControllerCellReadinessStatusChange_EventPatternParameters(options *Route53ApplicationRecoveryControllerCellReadinessStatusChange_Route53ApplicationRecoveryControllerCellReadinessStatusChangeProps) error {
	return nil
}

