package mixinsawswafv2

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnIPSetMixinProps",
		reflect.TypeOf((*CfnIPSetMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnIPSetPropsMixin",
		reflect.TypeOf((*CfnIPSetPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnIPSetPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationMixinProps",
		reflect.TypeOf((*CfnLoggingConfigurationMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnLoggingConfigurationPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.ActionConditionProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_ActionConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.ConditionProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_ConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.FieldToMatchProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_FieldToMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.FilterProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_FilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.LabelNameConditionProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_LabelNameConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnLoggingConfigurationPropsMixin.LoggingFilterProperty",
		reflect.TypeOf((*CfnLoggingConfigurationPropsMixin_LoggingFilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRegexPatternSetMixinProps",
		reflect.TypeOf((*CfnRegexPatternSetMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRegexPatternSetPropsMixin",
		reflect.TypeOf((*CfnRegexPatternSetPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnRegexPatternSetPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupMixinProps",
		reflect.TypeOf((*CfnRuleGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin",
		reflect.TypeOf((*CfnRuleGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnRuleGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.AndStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_AndStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.AsnMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_AsnMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.BodyProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_BodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.ByteMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_ByteMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.CaptchaConfigProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_CaptchaConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.ChallengeConfigProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_ChallengeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.CookieMatchPatternProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_CookieMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.CookiesProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_CookiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.CustomResponseBodyProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_CustomResponseBodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.FieldToMatchProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_FieldToMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.ForwardedIPConfigurationProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_ForwardedIPConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.GeoMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_GeoMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.HeaderMatchPatternProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_HeaderMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.HeadersProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_HeadersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.IPSetForwardedIPConfigurationProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_IPSetForwardedIPConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.IPSetReferenceStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_IPSetReferenceStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.ImmunityTimePropertyProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_ImmunityTimePropertyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.JA3FingerprintProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_JA3FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.JA4FingerprintProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_JA4FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.JsonBodyProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_JsonBodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.JsonMatchPatternProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_JsonMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.LabelMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_LabelMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.LabelProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_LabelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.LabelSummaryProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_LabelSummaryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.NotStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_NotStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.OrStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_OrStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateBasedStatementCustomKeyProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateBasedStatementCustomKeyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateBasedStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateBasedStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitCookieProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitCookieProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitHeaderProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitJA3FingerprintProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitJA3FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitJA4FingerprintProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitJA4FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitLabelNamespaceProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitLabelNamespaceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitQueryArgumentProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitQueryArgumentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitQueryStringProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitQueryStringProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RateLimitUriPathProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RateLimitUriPathProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RegexMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RegexMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RegexPatternSetReferenceStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RegexPatternSetReferenceStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RuleActionProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RuleActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.RuleProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_RuleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.SizeConstraintStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_SizeConstraintStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.SqliMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_SqliMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.StatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_StatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.TextTransformationProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_TextTransformationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.UriFragmentProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_UriFragmentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.VisibilityConfigProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_VisibilityConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnRuleGroupPropsMixin.XssMatchStatementProperty",
		reflect.TypeOf((*CfnRuleGroupPropsMixin_XssMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLAssociationMixinProps",
		reflect.TypeOf((*CfnWebACLAssociationMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLAssociationPropsMixin",
		reflect.TypeOf((*CfnWebACLAssociationPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnWebACLAssociationPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLMixinProps",
		reflect.TypeOf((*CfnWebACLMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin",
		reflect.TypeOf((*CfnWebACLPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnWebACLPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AWSManagedRulesACFPRuleSetProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AWSManagedRulesACFPRuleSetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AWSManagedRulesATPRuleSetProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AWSManagedRulesATPRuleSetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AWSManagedRulesAntiDDoSRuleSetProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AWSManagedRulesAntiDDoSRuleSetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AWSManagedRulesBotControlRuleSetProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AWSManagedRulesBotControlRuleSetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AllowActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AllowActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AndStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AndStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ApplicationAttributeProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ApplicationAttributeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ApplicationConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ApplicationConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AsnMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AsnMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.AssociationConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_AssociationConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.BlockActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_BlockActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.BodyProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_BodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ByteMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ByteMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CaptchaActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CaptchaActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CaptchaConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CaptchaConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ChallengeActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ChallengeActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ChallengeConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ChallengeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ClientSideActionConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ClientSideActionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ClientSideActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ClientSideActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CookieMatchPatternProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CookieMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CookiesProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CookiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CountActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CountActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CustomHTTPHeaderProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CustomHTTPHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CustomRequestHandlingProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CustomRequestHandlingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CustomResponseBodyProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CustomResponseBodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.CustomResponseProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_CustomResponseProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.DataProtectProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_DataProtectProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.DataProtectionConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_DataProtectionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.DefaultActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_DefaultActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ExcludedRuleProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ExcludedRuleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.FieldIdentifierProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_FieldIdentifierProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.FieldToMatchProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_FieldToMatchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.FieldToProtectProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_FieldToProtectProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ForwardedIPConfigurationProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ForwardedIPConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.GeoMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_GeoMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.HeaderMatchPatternProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_HeaderMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.HeadersProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_HeadersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.IPSetForwardedIPConfigurationProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_IPSetForwardedIPConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.IPSetReferenceStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_IPSetReferenceStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ImmunityTimePropertyProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ImmunityTimePropertyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.JA3FingerprintProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_JA3FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.JA4FingerprintProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_JA4FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.JsonBodyProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_JsonBodyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.JsonMatchPatternProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_JsonMatchPatternProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.LabelMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_LabelMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.LabelProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_LabelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ManagedRuleGroupConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ManagedRuleGroupConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ManagedRuleGroupStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ManagedRuleGroupStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.NotStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_NotStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.OnSourceDDoSProtectionConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_OnSourceDDoSProtectionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.OrStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_OrStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.OverrideActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_OverrideActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateBasedStatementCustomKeyProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateBasedStatementCustomKeyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateBasedStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateBasedStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitCookieProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitCookieProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitHeaderProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitJA3FingerprintProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitJA3FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitJA4FingerprintProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitJA4FingerprintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitLabelNamespaceProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitLabelNamespaceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitQueryArgumentProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitQueryArgumentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitQueryStringProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitQueryStringProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RateLimitUriPathProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RateLimitUriPathProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RegexMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RegexMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RegexPatternSetReferenceStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RegexPatternSetReferenceStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RegexProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RegexProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RequestBodyAssociatedResourceTypeConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RequestBodyAssociatedResourceTypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RequestInspectionACFPProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RequestInspectionACFPProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RequestInspectionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RequestInspectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ResponseInspectionBodyContainsProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ResponseInspectionBodyContainsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ResponseInspectionHeaderProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ResponseInspectionHeaderProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ResponseInspectionJsonProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ResponseInspectionJsonProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ResponseInspectionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ResponseInspectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.ResponseInspectionStatusCodeProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_ResponseInspectionStatusCodeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RuleActionOverrideProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RuleActionOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RuleActionProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RuleActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RuleGroupReferenceStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RuleGroupReferenceStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.RuleProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_RuleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.SizeConstraintStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_SizeConstraintStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.SqliMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_SqliMatchStatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.StatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_StatementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.TextTransformationProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_TextTransformationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.UriFragmentProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_UriFragmentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.VisibilityConfigProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_VisibilityConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_wafv2.mixins.CfnWebACLPropsMixin.XssMatchStatementProperty",
		reflect.TypeOf((*CfnWebACLPropsMixin_XssMatchStatementProperty)(nil)).Elem(),
	)
}
