package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsroute53recoverycontrol"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsroute53recoverycontrolIClusterRef = interfacesawsroute53recoverycontrol.IClusterRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsroute53recoverycontrolIControlPanelRef = interfacesawsroute53recoverycontrol.IControlPanelRef
type Type__interfacesawsroute53recoverycontrolIRoutingControlRef = interfacesawsroute53recoverycontrol.IRoutingControlRef
type Type__interfacesawsroute53recoverycontrolISafetyRuleRef = interfacesawsroute53recoverycontrol.ISafetyRuleRef
