package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawspcaconnectorad"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawspcaconnectoradIConnectorRef = interfacesawspcaconnectorad.IConnectorRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawspcaconnectoradIDirectoryRegistrationRef = interfacesawspcaconnectorad.IDirectoryRegistrationRef
type Type__interfacesawspcaconnectoradIServicePrincipalNameRef = interfacesawspcaconnectorad.IServicePrincipalNameRef
type Type__interfacesawspcaconnectoradITemplateRef = interfacesawspcaconnectorad.ITemplateRef
type Type__interfacesawspcaconnectoradITemplateGroupAccessControlEntryRef = interfacesawspcaconnectorad.ITemplateGroupAccessControlEntryRef
