package awsdatabrew


// Represents options that specify how and where DataBrew writes the Amazon S3 output generated by recipe jobs.
//
// Example:
//   // The code below shows an example of how to instantiate this type.
//   // The values are placeholders you should change.
//   import "github.com/aws/aws-cdk-go/awscdk"
//
//   s3TableOutputOptionsProperty := &s3TableOutputOptionsProperty{
//   	location: &s3LocationProperty{
//   		bucket: jsii.String("bucket"),
//
//   		// the properties below are optional
//   		bucketOwner: jsii.String("bucketOwner"),
//   		key: jsii.String("key"),
//   	},
//   }
//
type CfnJob_S3TableOutputOptionsProperty struct {
	// Represents an Amazon S3 location (bucket name and object key) where DataBrew can write output from a job.
	Location interface{} `field:"required" json:"location" yaml:"location"`
}

