package awsdatabrew


// Represents a JDBC database output object which defines the output destination for a DataBrew recipe job to write into.
//
// Example:
//   // The code below shows an example of how to instantiate this type.
//   // The values are placeholders you should change.
//   import "github.com/aws/aws-cdk-go/awscdk"
//
//   databaseOutputProperty := &databaseOutputProperty{
//   	databaseOptions: &databaseTableOutputOptionsProperty{
//   		tableName: jsii.String("tableName"),
//
//   		// the properties below are optional
//   		tempDirectory: &s3LocationProperty{
//   			bucket: jsii.String("bucket"),
//
//   			// the properties below are optional
//   			bucketOwner: jsii.String("bucketOwner"),
//   			key: jsii.String("key"),
//   		},
//   	},
//   	glueConnectionName: jsii.String("glueConnectionName"),
//
//   	// the properties below are optional
//   	databaseOutputMode: jsii.String("databaseOutputMode"),
//   }
//
type CfnJob_DatabaseOutputProperty struct {
	// Represents options that specify how and where DataBrew writes the database output generated by recipe jobs.
	DatabaseOptions interface{} `field:"required" json:"databaseOptions" yaml:"databaseOptions"`
	// The AWS Glue connection that stores the connection information for the target database.
	GlueConnectionName *string `field:"required" json:"glueConnectionName" yaml:"glueConnectionName"`
	// The output mode to write into the database.
	//
	// Currently supported option: NEW_TABLE.
	DatabaseOutputMode *string `field:"optional" json:"databaseOutputMode" yaml:"databaseOutputMode"`
}

