package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsgreengrass"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsgreengrassIConnectorDefinitionRef = interfacesawsgreengrass.IConnectorDefinitionRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsgreengrassIConnectorDefinitionVersionRef = interfacesawsgreengrass.IConnectorDefinitionVersionRef
type Type__interfacesawsgreengrassICoreDefinitionRef = interfacesawsgreengrass.ICoreDefinitionRef
type Type__interfacesawsgreengrassICoreDefinitionVersionRef = interfacesawsgreengrass.ICoreDefinitionVersionRef
type Type__interfacesawsgreengrassIDeviceDefinitionRef = interfacesawsgreengrass.IDeviceDefinitionRef
type Type__interfacesawsgreengrassIDeviceDefinitionVersionRef = interfacesawsgreengrass.IDeviceDefinitionVersionRef
type Type__interfacesawsgreengrassIFunctionDefinitionRef = interfacesawsgreengrass.IFunctionDefinitionRef
type Type__interfacesawsgreengrassIFunctionDefinitionVersionRef = interfacesawsgreengrass.IFunctionDefinitionVersionRef
type Type__interfacesawsgreengrassIGroupRef = interfacesawsgreengrass.IGroupRef
type Type__interfacesawsgreengrassIGroupVersionRef = interfacesawsgreengrass.IGroupVersionRef
type Type__interfacesawsgreengrassILoggerDefinitionRef = interfacesawsgreengrass.ILoggerDefinitionRef
type Type__interfacesawsgreengrassILoggerDefinitionVersionRef = interfacesawsgreengrass.ILoggerDefinitionVersionRef
type Type__interfacesawsgreengrassIResourceDefinitionRef = interfacesawsgreengrass.IResourceDefinitionRef
type Type__interfacesawsgreengrassIResourceDefinitionVersionRef = interfacesawsgreengrass.IResourceDefinitionVersionRef
type Type__interfacesawsgreengrassISubscriptionDefinitionRef = interfacesawsgreengrass.ISubscriptionDefinitionRef
type Type__interfacesawsgreengrassISubscriptionDefinitionVersionRef = interfacesawsgreengrass.ISubscriptionDefinitionVersionRef
