package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsnetworkmanager"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsnetworkmanagerIConnectAttachmentRef = interfacesawsnetworkmanager.IConnectAttachmentRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsnetworkmanagerIConnectPeerRef = interfacesawsnetworkmanager.IConnectPeerRef
type Type__interfacesawsnetworkmanagerICoreNetworkRef = interfacesawsnetworkmanager.ICoreNetworkRef
type Type__interfacesawsnetworkmanagerICustomerGatewayAssociationRef = interfacesawsnetworkmanager.ICustomerGatewayAssociationRef
type Type__interfacesawsnetworkmanagerIDeviceRef = interfacesawsnetworkmanager.IDeviceRef
type Type__interfacesawsnetworkmanagerIDirectConnectGatewayAttachmentRef = interfacesawsnetworkmanager.IDirectConnectGatewayAttachmentRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsnetworkmanagerIGlobalNetworkRef = interfacesawsnetworkmanager.IGlobalNetworkRef
type Type__interfacesawsnetworkmanagerILinkRef = interfacesawsnetworkmanager.ILinkRef
type Type__interfacesawsnetworkmanagerILinkAssociationRef = interfacesawsnetworkmanager.ILinkAssociationRef
type Type__interfacesawsnetworkmanagerISiteRef = interfacesawsnetworkmanager.ISiteRef
type Type__interfacesawsnetworkmanagerISiteToSiteVpnAttachmentRef = interfacesawsnetworkmanager.ISiteToSiteVpnAttachmentRef
type Type__interfacesawsnetworkmanagerITransitGatewayPeeringRef = interfacesawsnetworkmanager.ITransitGatewayPeeringRef
type Type__interfacesawsnetworkmanagerITransitGatewayRegistrationRef = interfacesawsnetworkmanager.ITransitGatewayRegistrationRef
type Type__interfacesawsnetworkmanagerITransitGatewayRouteTableAttachmentRef = interfacesawsnetworkmanager.ITransitGatewayRouteTableAttachmentRef
type Type__interfacesawsnetworkmanagerIVpcAttachmentRef = interfacesawsnetworkmanager.IVpcAttachmentRef
