package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawscognito"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawscognitoIIdentityPoolRef = interfacesawscognito.IIdentityPoolRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawscognitoIIdentityPoolPrincipalTagRef = interfacesawscognito.IIdentityPoolPrincipalTagRef
type Type__interfacesawscognitoIIdentityPoolRoleAttachmentRef = interfacesawscognito.IIdentityPoolRoleAttachmentRef
type Type__interfacesawscognitoILogDeliveryConfigurationRef = interfacesawscognito.ILogDeliveryConfigurationRef
type Type__interfacesawscognitoIManagedLoginBrandingRef = interfacesawscognito.IManagedLoginBrandingRef
type Type__interfacesawscognitoITermsRef = interfacesawscognito.ITermsRef
type Type__interfacesawscognitoIUserPoolRef = interfacesawscognito.IUserPoolRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawscognitoIUserPoolClientRef = interfacesawscognito.IUserPoolClientRef
type Type__interfacesawscognitoIUserPoolDomainRef = interfacesawscognito.IUserPoolDomainRef
type Type__interfacesawscognitoIUserPoolGroupRef = interfacesawscognito.IUserPoolGroupRef
type Type__interfacesawscognitoIUserPoolIdentityProviderRef = interfacesawscognito.IUserPoolIdentityProviderRef
type Type__interfacesawscognitoIUserPoolResourceServerRef = interfacesawscognito.IUserPoolResourceServerRef
type Type__interfacesawscognitoIUserPoolRiskConfigurationAttachmentRef = interfacesawscognito.IUserPoolRiskConfigurationAttachmentRef
type Type__interfacesawscognitoIUserPoolUICustomizationAttachmentRef = interfacesawscognito.IUserPoolUICustomizationAttachmentRef
type Type__interfacesawscognitoIUserPoolUserRef = interfacesawscognito.IUserPoolUserRef
type Type__interfacesawscognitoIUserPoolUserToGroupAttachmentRef = interfacesawscognito.IUserPoolUserToGroupAttachmentRef
type Type__awscdkIResource = awscdk.IResource
type Type__awscdkResource = awscdk.Resource
