package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsrobomaker"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsrobomakerIFleetRef = interfacesawsrobomaker.IFleetRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsrobomakerIRobotRef = interfacesawsrobomaker.IRobotRef
type Type__interfacesawsrobomakerIRobotApplicationRef = interfacesawsrobomaker.IRobotApplicationRef
type Type__interfacesawsrobomakerIRobotApplicationVersionRef = interfacesawsrobomaker.IRobotApplicationVersionRef
type Type__interfacesawsrobomakerISimulationApplicationRef = interfacesawsrobomaker.ISimulationApplicationRef
type Type__interfacesawsrobomakerISimulationApplicationVersionRef = interfacesawsrobomaker.ISimulationApplicationVersionRef
