package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsroute53resolver"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsroute53resolverIFirewallDomainListRef = interfacesawsroute53resolver.IFirewallDomainListRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsroute53resolverIFirewallRuleGroupRef = interfacesawsroute53resolver.IFirewallRuleGroupRef
type Type__interfacesawsroute53resolverIFirewallRuleGroupAssociationRef = interfacesawsroute53resolver.IFirewallRuleGroupAssociationRef
type Type__interfacesawsroute53resolverIOutpostResolverRef = interfacesawsroute53resolver.IOutpostResolverRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsroute53resolverIResolverConfigRef = interfacesawsroute53resolver.IResolverConfigRef
type Type__interfacesawsroute53resolverIResolverDNSSECConfigRef = interfacesawsroute53resolver.IResolverDNSSECConfigRef
type Type__interfacesawsroute53resolverIResolverEndpointRef = interfacesawsroute53resolver.IResolverEndpointRef
type Type__interfacesawsroute53resolverIResolverQueryLoggingConfigRef = interfacesawsroute53resolver.IResolverQueryLoggingConfigRef
type Type__interfacesawsroute53resolverIResolverQueryLoggingConfigAssociationRef = interfacesawsroute53resolver.IResolverQueryLoggingConfigAssociationRef
type Type__interfacesawsroute53resolverIResolverRuleRef = interfacesawsroute53resolver.IResolverRuleRef
type Type__interfacesawsroute53resolverIResolverRuleAssociationRef = interfacesawsroute53resolver.IResolverRuleAssociationRef
