package previewawsmedialivemixins

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelMixinProps",
		reflect.TypeOf((*CfnChannelMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPlacementGroupMixinProps",
		reflect.TypeOf((*CfnChannelPlacementGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPlacementGroupPropsMixin",
		reflect.TypeOf((*CfnChannelPlacementGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnChannelPlacementGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin",
		reflect.TypeOf((*CfnChannelPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnChannelPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AacSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AacSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Ac3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Ac3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AdditionalDestinationsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AdditionalDestinationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AncillarySourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AncillarySourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AnywhereSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AnywhereSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ArchiveCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ArchiveContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ArchiveGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ArchiveOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ArchiveS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AribDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AribDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AribSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AribSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioChannelMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioChannelMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioCodecSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioCodecSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioDolbyEDecodeProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioDolbyEDecodeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioHlsRenditionSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioHlsRenditionSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioLanguageSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioLanguageSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioNormalizationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioNormalizationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioOnlyHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioOnlyHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioPidSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioPidSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioSilenceFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSilenceFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioTrackProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioTrackProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioTrackSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioTrackSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AudioWatermarkSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioWatermarkSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AutomaticInputFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AutomaticInputFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Av1ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Av1ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Av1SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Av1SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AvailBlankingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailBlankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AvailConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.AvailSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.BandwidthReductionFilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BandwidthReductionFilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.BlackoutSlateProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BlackoutSlateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.BurnInDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BurnInDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionLanguageMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionLanguageMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionRectangleProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionRectangleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CaptionSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CdiInputSpecificationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CdiInputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ChannelEngineVersionRequestProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ChannelEngineVersionRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CmafIngestCaptionLanguageMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestCaptionLanguageMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CmafIngestGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.CmafIngestOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ColorCorrectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorCorrectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ColorCorrectionSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorCorrectionSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ColorSpacePassthroughSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorSpacePassthroughSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DolbyVision81SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DolbyVision81SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DvbNitSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbNitSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DvbSdtSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSdtSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DvbSubDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSubDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DvbSubSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSubSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.DvbTdtSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbTdtSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Eac3AtmosSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Eac3AtmosSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Eac3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Eac3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EbuTtDDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EbuTtDDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EmbeddedDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EmbeddedPlusScte20DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedPlusScte20DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EmbeddedSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EncoderSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EncoderSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EpochLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EpochLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.EsamProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EsamProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FailoverConditionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FailoverConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FailoverConditionSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FailoverConditionSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FeatureActivationsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FeatureActivationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FecOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FecOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Fmp4HlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Fmp4HlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.FrameCaptureSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.GlobalConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_GlobalConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H264ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H264FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H264SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H265ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H265FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.H265SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Hdr10SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Hdr10SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsAkamaiSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsAkamaiSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsBasicPutSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsBasicPutSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsMediaStoreSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsMediaStoreSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HlsWebdavSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsWebdavSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.HtmlMotionGraphicsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HtmlMotionGraphicsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputAttachmentProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputAttachmentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputChannelLevelProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputChannelLevelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputLocationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputLossBehaviorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLossBehaviorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputLossFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLossFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.InputSpecificationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.KeyProviderSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_KeyProviderSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.M2tsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_M2tsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.M3u8SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_M3u8SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MaintenanceCreateSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MaintenanceCreateSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MediaPackageGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MediaPackageOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MediaPackageOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MediaPackageV2DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageV2DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MediaPackageV2GroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageV2GroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MotionGraphicsConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MotionGraphicsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MotionGraphicsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MotionGraphicsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Mp2SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mp2SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Mpeg2FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mpeg2FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Mpeg2SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mpeg2SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MsSmoothGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MsSmoothGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MsSmoothOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MsSmoothOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MulticastInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MulticastInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MultiplexContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MultiplexGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MultiplexM2tsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexM2tsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MultiplexOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.MultiplexProgramChannelDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexProgramChannelDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.NetworkInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NetworkInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.NielsenCBETProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenCBETProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.NielsenConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.NielsenNaesIiNwProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenNaesIiNwProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.NielsenWatermarksSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenWatermarksSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputDestinationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputGroupProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputLocationRefProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputLocationRefProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.OutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.PassThroughSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_PassThroughSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.RawSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RawSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Rec601SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Rec601SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Rec709SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Rec709SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.RemixSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RemixSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.RtmpCaptionInfoDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpCaptionInfoDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.RtmpGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.RtmpOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte20PlusEmbeddedDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte20PlusEmbeddedDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte20SourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte20SourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte27DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte27DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte27SourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte27SourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte35SpliceInsertProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte35SpliceInsertProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.Scte35TimeSignalAposProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte35TimeSignalAposProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.SmpteTtDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SmpteTtDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.SrtGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.SrtOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.SrtOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.StandardHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_StandardHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.StaticKeySettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_StaticKeySettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TeletextDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TeletextDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TeletextSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TeletextSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TemporalFilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TemporalFilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.ThumbnailConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ThumbnailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TimecodeBurninSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TimecodeBurninSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TimecodeConfigProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TimecodeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.TtmlDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TtmlDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.UdpContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.UdpGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.UdpOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoBlackFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoBlackFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoCodecSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoCodecSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoSelectorColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoSelectorPidProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorPidProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoSelectorProgramIdProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorProgramIdProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VideoSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.VpcOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VpcOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.WavSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_WavSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnChannelPropsMixin.WebvttDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_WebvttDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnCloudWatchAlarmTemplateGroupMixinProps",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnCloudWatchAlarmTemplateGroupPropsMixin",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnCloudWatchAlarmTemplateGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnCloudWatchAlarmTemplateMixinProps",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnCloudWatchAlarmTemplatePropsMixin",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplatePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnCloudWatchAlarmTemplatePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnClusterMixinProps",
		reflect.TypeOf((*CfnClusterMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnClusterPropsMixin",
		reflect.TypeOf((*CfnClusterPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnClusterPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnClusterPropsMixin.ClusterNetworkSettingsProperty",
		reflect.TypeOf((*CfnClusterPropsMixin_ClusterNetworkSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnClusterPropsMixin.InterfaceMappingProperty",
		reflect.TypeOf((*CfnClusterPropsMixin_InterfaceMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnEventBridgeRuleTemplateGroupMixinProps",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnEventBridgeRuleTemplateGroupPropsMixin",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnEventBridgeRuleTemplateGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnEventBridgeRuleTemplateMixinProps",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnEventBridgeRuleTemplatePropsMixin",
		reflect.TypeOf((*CfnEventBridgeRuleTemplatePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnEventBridgeRuleTemplatePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnEventBridgeRuleTemplatePropsMixin.EventBridgeRuleTemplateTargetProperty",
		reflect.TypeOf((*CfnEventBridgeRuleTemplatePropsMixin_EventBridgeRuleTemplateTargetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputMixinProps",
		reflect.TypeOf((*CfnInputMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin",
		reflect.TypeOf((*CfnInputPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnInputPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputDestinationRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputDestinationRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputDeviceSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputDeviceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputRequestDestinationRouteProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputRequestDestinationRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputSdpLocationProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputSdpLocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputSourceRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputSourceRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.InputVpcRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputVpcRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.MediaConnectFlowRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MediaConnectFlowRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.MulticastSettingsCreateRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MulticastSettingsCreateRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.MulticastSourceCreateRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MulticastSourceCreateRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.RouterDestinationSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_RouterDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.RouterSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_RouterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.Smpte2110ReceiverGroupProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.Smpte2110ReceiverGroupSdpSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupSdpSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.Smpte2110ReceiverGroupSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.SrtCallerDecryptionRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtCallerDecryptionRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.SrtCallerSourceRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtCallerSourceRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputPropsMixin.SrtSettingsRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtSettingsRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputSecurityGroupMixinProps",
		reflect.TypeOf((*CfnInputSecurityGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputSecurityGroupPropsMixin",
		reflect.TypeOf((*CfnInputSecurityGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnInputSecurityGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnInputSecurityGroupPropsMixin.InputWhitelistRuleCidrProperty",
		reflect.TypeOf((*CfnInputSecurityGroupPropsMixin_InputWhitelistRuleCidrProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexMixinProps",
		reflect.TypeOf((*CfnMultiplexMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexPropsMixin",
		reflect.TypeOf((*CfnMultiplexPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnMultiplexPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexPropsMixin.MultiplexMediaConnectOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexMediaConnectOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexPropsMixin.MultiplexOutputDestinationProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexOutputDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexPropsMixin.MultiplexSettingsProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramMixinProps",
		reflect.TypeOf((*CfnMultiplexprogramMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnMultiplexprogramPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexProgramPacketIdentifiersMapProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramPacketIdentifiersMapProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexProgramPipelineDetailProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramPipelineDetailProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexProgramServiceDescriptorProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramServiceDescriptorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexProgramSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexStatmuxVideoSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexStatmuxVideoSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnMultiplexprogramPropsMixin.MultiplexVideoSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexVideoSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnNetworkMixinProps",
		reflect.TypeOf((*CfnNetworkMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnNetworkPropsMixin",
		reflect.TypeOf((*CfnNetworkPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnNetworkPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnNetworkPropsMixin.IpPoolProperty",
		reflect.TypeOf((*CfnNetworkPropsMixin_IpPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnNetworkPropsMixin.RouteProperty",
		reflect.TypeOf((*CfnNetworkPropsMixin_RouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSdiSourceMixinProps",
		reflect.TypeOf((*CfnSdiSourceMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSdiSourcePropsMixin",
		reflect.TypeOf((*CfnSdiSourcePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnSdiSourcePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapMixinProps",
		reflect.TypeOf((*CfnSignalMapMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapPropsMixin",
		reflect.TypeOf((*CfnSignalMapPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnSignalMapPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapPropsMixin.MediaResourceNeighborProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MediaResourceNeighborProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapPropsMixin.MediaResourceProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MediaResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapPropsMixin.MonitorDeploymentProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MonitorDeploymentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_medialive.mixins.CfnSignalMapPropsMixin.SuccessfulMonitorDeploymentProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_SuccessfulMonitorDeploymentProperty)(nil)).Elem(),
	)
}
