package previewawsamplifyuibuildermixins


// The `SectionalElement` property specifies the configuration information for a visual helper element for a form.
//
// A sectional element can be a header, a text block, or a divider. These elements are static and not associated with any data.
//
// Example:
//   // The code below shows an example of how to instantiate this type.
//   // The values are placeholders you should change.
//   import "github.com/aws/aws-cdk-go/awscdkmixinspreview"
//
//   sectionalElementProperty := &SectionalElementProperty{
//   	Excluded: jsii.Boolean(false),
//   	Level: jsii.Number(123),
//   	Orientation: jsii.String("orientation"),
//   	Position: &FieldPositionProperty{
//   		Below: jsii.String("below"),
//   		Fixed: jsii.String("fixed"),
//   		RightOf: jsii.String("rightOf"),
//   	},
//   	Text: jsii.String("text"),
//   	Type: jsii.String("type"),
//   }
//
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html
//
type CfnFormPropsMixin_SectionalElementProperty struct {
	// Excludes a sectional element that was generated by default for a specified data model.
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-excluded
	//
	Excluded interface{} `field:"optional" json:"excluded" yaml:"excluded"`
	// Specifies the size of the font for a `Heading` sectional element.
	//
	// Valid values are `1 | 2 | 3 | 4 | 5 | 6` .
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-level
	//
	Level *float64 `field:"optional" json:"level" yaml:"level"`
	// Specifies the orientation for a `Divider` sectional element.
	//
	// Valid values are `horizontal` or `vertical` .
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-orientation
	//
	Orientation *string `field:"optional" json:"orientation" yaml:"orientation"`
	// Specifies the position of the text in a field for a `Text` sectional element.
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-position
	//
	Position interface{} `field:"optional" json:"position" yaml:"position"`
	// The text for a `Text` sectional element.
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-text
	//
	Text *string `field:"optional" json:"text" yaml:"text"`
	// The type of sectional element.
	//
	// Valid values are `Heading` , `Text` , and `Divider` .
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-amplifyuibuilder-form-sectionalelement.html#cfn-amplifyuibuilder-form-sectionalelement-type
	//
	Type *string `field:"optional" json:"type" yaml:"type"`
}

