package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsecr"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsecrIPublicRepositoryRef = interfacesawsecr.IPublicRepositoryRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsecrIPullThroughCacheRuleRef = interfacesawsecr.IPullThroughCacheRuleRef
type Type__interfacesawsecrIPullTimeUpdateExclusionRef = interfacesawsecr.IPullTimeUpdateExclusionRef
type Type__interfacesawsecrIRegistryPolicyRef = interfacesawsecr.IRegistryPolicyRef
type Type__interfacesawsecrIRegistryScanningConfigurationRef = interfacesawsecr.IRegistryScanningConfigurationRef
type Type__interfacesawsecrIReplicationConfigurationRef = interfacesawsecr.IReplicationConfigurationRef
type Type__interfacesawsecrIRepositoryRef = interfacesawsecr.IRepositoryRef
type Type__interfacesawsecrIRepositoryCreationTemplateRef = interfacesawsecr.IRepositoryCreationTemplateRef
type Type__interfacesawsecrISigningConfigurationRef = interfacesawsecr.ISigningConfigurationRef
type Type__awscdkIResource = awscdk.IResource
type Type__awscdkResource = awscdk.Resource
