package awsbedrockagentcorealpha

import (
	_init_ "github.com/aws/aws-cdk-go/awsbedrockagentcorealpha/v2/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awsbedrockagentcorealpha/v2/internal"
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsbedrockagentcore"
	"github.com/aws/constructs-go/constructs/v10"
)

// L2 construct for `AWS::BedrockAgentCore::ApiKeyCredentialProvider`.
//
// Use this to register an API key identity in AgentCore Token Vault. To attach the identity to a
// gateway target, use {@link GatewayCredentialProvider.fromApiKeyIdentity } with this construct, or
// {@link ApiKeyCredentialProvider.bindForGatewayApiKeyTarget} with {@link GatewayCredentialProvider.fromApiKeyIdentityArn }.
//
// Example:
//   // The code below shows an example of how to instantiate this type.
//   // The values are placeholders you should change.
//   import bedrock_agentcore_alpha "github.com/aws/aws-cdk-go/awsbedrockagentcorealpha"
//   import cdk "github.com/aws/aws-cdk-go/awscdk"
//
//   var secretValue SecretValue
//
//   apiKeyCredentialProvider := bedrock_agentcore_alpha.NewApiKeyCredentialProvider(this, jsii.String("MyApiKeyCredentialProvider"), &ApiKeyCredentialProviderResourceProps{
//   	ApiKey: secretValue,
//   	ApiKeyCredentialProviderName: jsii.String("apiKeyCredentialProviderName"),
//   	Tags: map[string]*string{
//   		"tagsKey": jsii.String("tags"),
//   	},
//   })
//
// See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrockagentcore-apikeycredentialprovider.html
//
// Experimental.
type ApiKeyCredentialProvider interface {
	awscdk.Resource
	IApiKeyCredentialProvider
	// The name of this API key credential provider.
	// Experimental.
	ApiKeyCredentialProviderName() *string
	// A reference to a ApiKeyCredentialProvider resource.
	// Experimental.
	ApiKeyCredentialProviderRef() *interfacesawsbedrockagentcore.ApiKeyCredentialProviderReference
	// The ARN of the Secrets Manager secret that stores the API key after the resource is created.
	//
	// May be undefined for resources imported without this attribute.
	// Experimental.
	ApiKeySecretArn() *string
	// Timestamp when the credential provider was created.
	// Experimental.
	CreatedTime() *string
	// The ARN of this credential provider.
	// Experimental.
	CredentialProviderArn() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The principal to grant permissions to.
	// Experimental.
	GrantPrincipal() awsiam.IPrincipal
	// Timestamp when the credential provider was last updated.
	// Experimental.
	LastUpdatedTime() *string
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Override the cross-stack reference strength for this resource.
	//
	// When set, any cross-stack reference to this resource will use the specified
	// mechanism instead of the global default determined by the
	// `@aws-cdk/core:defaultCrossStackReferences` context key. This is useful for
	// selectively weakening specific references to avoid the "deadly embrace" problem
	// without changing the app-wide default.
	// Experimental.
	ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// ARNs for {@link GatewayCredentialProvider.fromApiKeyIdentity } / {@link GatewayCredentialProvider.fromApiKeyIdentityArn }.
	// Experimental.
	BindForGatewayApiKeyTarget() *GatewayApiKeyIdentityBinding
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// [disable-awslint:no-grants].
	// Experimental.
	Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant
	// [disable-awslint:no-grants].
	// Experimental.
	GrantAdmin(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	// Experimental.
	GrantFullAccess(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	// Experimental.
	GrantRead(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	// Experimental.
	GrantUse(grantee awsiam.IGrantable) awsiam.Grant
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	// Experimental.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for ApiKeyCredentialProvider
type jsiiProxy_ApiKeyCredentialProvider struct {
	internal.Type__awscdkResource
	jsiiProxy_IApiKeyCredentialProvider
}

func (j *jsiiProxy_ApiKeyCredentialProvider) ApiKeyCredentialProviderName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiKeyCredentialProviderName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) ApiKeyCredentialProviderRef() *interfacesawsbedrockagentcore.ApiKeyCredentialProviderReference {
	var returns *interfacesawsbedrockagentcore.ApiKeyCredentialProviderReference
	_jsii_.Get(
		j,
		"apiKeyCredentialProviderRef",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) ApiKeySecretArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiKeySecretArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) CreatedTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"createdTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) CredentialProviderArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"credentialProviderArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) GrantPrincipal() awsiam.IPrincipal {
	var returns awsiam.IPrincipal
	_jsii_.Get(
		j,
		"grantPrincipal",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) LastUpdatedTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"lastUpdatedTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_ApiKeyCredentialProvider) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewApiKeyCredentialProvider(scope constructs.Construct, id *string, props *ApiKeyCredentialProviderResourceProps) ApiKeyCredentialProvider {
	_init_.Initialize()

	if err := validateNewApiKeyCredentialProviderParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_ApiKeyCredentialProvider{}

	_jsii_.Create(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewApiKeyCredentialProvider_Override(a ApiKeyCredentialProvider, scope constructs.Construct, id *string, props *ApiKeyCredentialProviderResourceProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		[]interface{}{scope, id, props},
		a,
	)
}

// Import an existing API key credential provider.
// Experimental.
func ApiKeyCredentialProvider_FromApiKeyCredentialProviderAttributes(scope constructs.Construct, id *string, attrs *ApiKeyCredentialProviderAttributes) IApiKeyCredentialProvider {
	_init_.Initialize()

	if err := validateApiKeyCredentialProvider_FromApiKeyCredentialProviderAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IApiKeyCredentialProvider

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		"fromApiKeyCredentialProviderAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func ApiKeyCredentialProvider_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateApiKeyCredentialProvider_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func ApiKeyCredentialProvider_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateApiKeyCredentialProvider_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func ApiKeyCredentialProvider_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateApiKeyCredentialProvider_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func ApiKeyCredentialProvider_PROPERTY_INJECTION_ID() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"@aws-cdk/aws-bedrock-agentcore-alpha.ApiKeyCredentialProvider",
		"PROPERTY_INJECTION_ID",
		&returns,
	)
	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength) {
	if err := a.validateApplyCrossStackReferenceStrengthParameters(strength); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"applyCrossStackReferenceStrength",
		[]interface{}{strength},
	)
}

func (a *jsiiProxy_ApiKeyCredentialProvider) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := a.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		a,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (a *jsiiProxy_ApiKeyCredentialProvider) BindForGatewayApiKeyTarget() *GatewayApiKeyIdentityBinding {
	var returns *GatewayApiKeyIdentityBinding

	_jsii_.Invoke(
		a,
		"bindForGatewayApiKeyTarget",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := a.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GetResourceNameAttribute(nameAttr *string) *string {
	if err := a.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	if err := a.validateGrantParameters(grantee); err != nil {
		panic(err)
	}
	args := []interface{}{grantee}
	for _, a := range actions {
		args = append(args, a)
	}

	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grant",
		args,
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GrantAdmin(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantAdminParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantAdmin",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GrantFullAccess(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantFullAccessParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantFullAccess",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GrantRead(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantReadParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantRead",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) GrantUse(grantee awsiam.IGrantable) awsiam.Grant {
	if err := a.validateGrantUseParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		a,
		"grantUse",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_ApiKeyCredentialProvider) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		a,
		"with",
		args,
		&returns,
	)

	return returns
}

