package previewawslexmixins

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasMixinProps",
		reflect.TypeOf((*CfnBotAliasMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin",
		reflect.TypeOf((*CfnBotAliasPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnBotAliasPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.AudioLogDestinationProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_AudioLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.AudioLogSettingProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_AudioLogSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.BotAliasLocaleSettingsItemProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_BotAliasLocaleSettingsItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.BotAliasLocaleSettingsProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_BotAliasLocaleSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.CloudWatchLogGroupLogDestinationProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_CloudWatchLogGroupLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.CodeHookSpecificationProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_CodeHookSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.ConversationLogSettingsProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_ConversationLogSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.LambdaCodeHookProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_LambdaCodeHookProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.S3BucketLogDestinationProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_S3BucketLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.SentimentAnalysisSettingsProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_SentimentAnalysisSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.TextLogDestinationProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_TextLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotAliasPropsMixin.TextLogSettingProperty",
		reflect.TypeOf((*CfnBotAliasPropsMixin_TextLogSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotMixinProps",
		reflect.TypeOf((*CfnBotMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin",
		reflect.TypeOf((*CfnBotPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnBotPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AdvancedRecognitionSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AdvancedRecognitionSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AllowedInputTypesProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AllowedInputTypesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AudioAndDTMFInputSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AudioAndDTMFInputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AudioLogDestinationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AudioLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AudioLogSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AudioLogSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.AudioSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_AudioSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BKBExactResponseFieldsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BKBExactResponseFieldsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockAgentConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockAgentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockAgentIntentConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockAgentIntentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockAgentIntentKnowledgeBaseConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockAgentIntentKnowledgeBaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockGuardrailConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockGuardrailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockKnowledgeStoreConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockKnowledgeStoreConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BedrockModelSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BedrockModelSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BotAliasLocaleSettingsItemProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BotAliasLocaleSettingsItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BotAliasLocaleSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BotAliasLocaleSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BotLocaleProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BotLocaleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.BuildtimeSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_BuildtimeSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ButtonProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ButtonProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CloudWatchLogGroupLogDestinationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CloudWatchLogGroupLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CodeHookSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CodeHookSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CompositeSlotTypeSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CompositeSlotTypeSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ConditionProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ConditionalBranchProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ConditionalBranchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ConditionalSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ConditionalSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ConversationLogSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ConversationLogSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CustomPayloadProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CustomPayloadProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CustomVocabularyItemProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CustomVocabularyItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.CustomVocabularyProperty",
		reflect.TypeOf((*CfnBotPropsMixin_CustomVocabularyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DTMFSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DTMFSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DataPrivacyProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DataPrivacyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DataSourceConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DefaultConditionalBranchProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DefaultConditionalBranchProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DescriptiveBotBuilderSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DescriptiveBotBuilderSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DialogActionProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DialogActionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DialogCodeHookInvocationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DialogCodeHookInvocationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DialogCodeHookSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DialogCodeHookSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.DialogStateProperty",
		reflect.TypeOf((*CfnBotPropsMixin_DialogStateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ElicitationCodeHookInvocationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ElicitationCodeHookInvocationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ErrorLogSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ErrorLogSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ExactResponseFieldsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ExactResponseFieldsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ExternalSourceSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ExternalSourceSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.FulfillmentCodeHookSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_FulfillmentCodeHookSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.FulfillmentStartResponseSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_FulfillmentStartResponseSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.FulfillmentUpdateResponseSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_FulfillmentUpdateResponseSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.FulfillmentUpdatesSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_FulfillmentUpdatesSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.GenerativeAISettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_GenerativeAISettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.GrammarSlotTypeSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_GrammarSlotTypeSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.GrammarSlotTypeSourceProperty",
		reflect.TypeOf((*CfnBotPropsMixin_GrammarSlotTypeSourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ImageResponseCardProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ImageResponseCardProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.InitialResponseSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_InitialResponseSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.InputContextProperty",
		reflect.TypeOf((*CfnBotPropsMixin_InputContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.IntentClosingSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_IntentClosingSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.IntentConfirmationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_IntentConfirmationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.IntentOverrideProperty",
		reflect.TypeOf((*CfnBotPropsMixin_IntentOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.IntentProperty",
		reflect.TypeOf((*CfnBotPropsMixin_IntentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.KendraConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_KendraConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.LambdaCodeHookProperty",
		reflect.TypeOf((*CfnBotPropsMixin_LambdaCodeHookProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.MessageGroupProperty",
		reflect.TypeOf((*CfnBotPropsMixin_MessageGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.MessageProperty",
		reflect.TypeOf((*CfnBotPropsMixin_MessageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.MultipleValuesSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_MultipleValuesSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.NluImprovementSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_NluImprovementSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ObfuscationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ObfuscationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.OpensearchConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_OpensearchConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.OutputContextProperty",
		reflect.TypeOf((*CfnBotPropsMixin_OutputContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.PlainTextMessageProperty",
		reflect.TypeOf((*CfnBotPropsMixin_PlainTextMessageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.PostDialogCodeHookInvocationSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_PostDialogCodeHookInvocationSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.PostFulfillmentStatusSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_PostFulfillmentStatusSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.PromptAttemptSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_PromptAttemptSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.PromptSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_PromptSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.QInConnectAssistantConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_QInConnectAssistantConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.QInConnectIntentConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_QInConnectIntentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.QnAIntentConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_QnAIntentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.QnAKendraConfigurationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_QnAKendraConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ReplicationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ReplicationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.ResponseSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_ResponseSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.RuntimeSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_RuntimeSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.S3BucketLogDestinationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_S3BucketLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.S3LocationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_S3LocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SSMLMessageProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SSMLMessageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SampleUtteranceGenerationSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SampleUtteranceGenerationSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SampleUtteranceProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SampleUtteranceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SampleValueProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SampleValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SessionAttributeProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SessionAttributeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotCaptureSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotCaptureSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotDefaultValueProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotDefaultValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotDefaultValueSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotDefaultValueSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotPriorityProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotPriorityProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotResolutionImprovementSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotResolutionImprovementSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotTypeProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotTypeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotTypeValueProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotTypeValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueElicitationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueElicitationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueOverrideMapProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueOverrideMapProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueOverrideProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueRegexFilterProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueRegexFilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SlotValueSelectionSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SlotValueSelectionSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SpecificationsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SpecificationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.StillWaitingResponseSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_StillWaitingResponseSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SubSlotSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SubSlotSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SubSlotTypeCompositionProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SubSlotTypeCompositionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.SubSlotValueElicitationSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_SubSlotValueElicitationSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.TestBotAliasSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_TestBotAliasSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.TextInputSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_TextInputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.TextLogDestinationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_TextLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.TextLogSettingProperty",
		reflect.TypeOf((*CfnBotPropsMixin_TextLogSettingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.VoiceSettingsProperty",
		reflect.TypeOf((*CfnBotPropsMixin_VoiceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotPropsMixin.WaitAndContinueSpecificationProperty",
		reflect.TypeOf((*CfnBotPropsMixin_WaitAndContinueSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotVersionMixinProps",
		reflect.TypeOf((*CfnBotVersionMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotVersionPropsMixin",
		reflect.TypeOf((*CfnBotVersionPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnBotVersionPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotVersionPropsMixin.BotVersionLocaleDetailsProperty",
		reflect.TypeOf((*CfnBotVersionPropsMixin_BotVersionLocaleDetailsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnBotVersionPropsMixin.BotVersionLocaleSpecificationProperty",
		reflect.TypeOf((*CfnBotVersionPropsMixin_BotVersionLocaleSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnResourcePolicyMixinProps",
		reflect.TypeOf((*CfnResourcePolicyMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_lex.mixins.CfnResourcePolicyPropsMixin",
		reflect.TypeOf((*CfnResourcePolicyPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnResourcePolicyPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
}
