package awsappsync

import (
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsappsync/internal"
)

// Interface for an API.
type IApi interface {
	awscdk.IResource
	// The ARN of the AWS AppSync Api.
	ApiArn() *string
	// The unique identifier for the AWS AppSync Api generated by the service.
	ApiId() *string
}

// The jsii proxy for IApi
type jsiiProxy_IApi struct {
	internal.Type__awscdkIResource
}

func (j *jsiiProxy_IApi) ApiArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_IApi) ApiId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"apiId",
		&returns,
	)
	return returns
}

