package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawswisdom"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawswisdomIAIAgentRef = interfacesawswisdom.IAIAgentRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawswisdomIAIAgentVersionRef = interfacesawswisdom.IAIAgentVersionRef
type Type__interfacesawswisdomIAIGuardrailRef = interfacesawswisdom.IAIGuardrailRef
type Type__interfacesawswisdomIAIGuardrailVersionRef = interfacesawswisdom.IAIGuardrailVersionRef
type Type__interfacesawswisdomIAIPromptRef = interfacesawswisdom.IAIPromptRef
type Type__interfacesawswisdomIAIPromptVersionRef = interfacesawswisdom.IAIPromptVersionRef
type Type__interfacesawswisdomIAssistantRef = interfacesawswisdom.IAssistantRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawswisdomIAssistantAssociationRef = interfacesawswisdom.IAssistantAssociationRef
type Type__interfacesawswisdomIKnowledgeBaseRef = interfacesawswisdom.IKnowledgeBaseRef
type Type__interfacesawswisdomIMessageTemplateRef = interfacesawswisdom.IMessageTemplateRef
type Type__interfacesawswisdomIMessageTemplateVersionRef = interfacesawswisdom.IMessageTemplateVersionRef
type Type__interfacesawswisdomIQuickResponseRef = interfacesawswisdom.IQuickResponseRef
