package previewawsec2events

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents",
		reflect.TypeOf((*InstanceEvents)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "awsAPICallViaCloudTrailPattern", GoMethod: "AwsAPICallViaCloudTrailPattern"},
			_jsii_.MemberMethod{JsiiMethod: "eC2InstanceStateChangeNotificationPattern", GoMethod: "EC2InstanceStateChangeNotificationPattern"},
			_jsii_.MemberMethod{JsiiMethod: "eC2SpotInstanceInterruptionWarningPattern", GoMethod: "EC2SpotInstanceInterruptionWarningPattern"},
		},
		func() interface{} {
			return &jsiiProxy_InstanceEvents{}
		},
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_InstanceEvents_AWSAPICallViaCloudTrail{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.AWSAPICallViaCloudTrailProps",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_AWSAPICallViaCloudTrailProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Attachment",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Attachment)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Attributes",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Attributes)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.CapacityReservationSpecification",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_CapacityReservationSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.CpuOptions",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_CpuOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.CreateFleetRequest",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_CreateFleetRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.CreateFleetResponse",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_CreateFleetResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.CreateLaunchTemplateRequest",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_CreateLaunchTemplateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.DeleteLaunchTemplateRequest",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_DeleteLaunchTemplateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.DeleteLaunchTemplateResponse",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_DeleteLaunchTemplateResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.EnclaveOptions",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_EnclaveOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.ExistingInstances",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_ExistingInstances)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.GroupSet1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_GroupSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.GroupSet1Item",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_GroupSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.GroupSet2",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_GroupSet2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.GroupSet2Item",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_GroupSet2Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.GroupSet3",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_GroupSet3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstanceMarketOptions",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstanceMarketOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstanceMarketOptions1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstanceMarketOptions1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstanceState",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstanceState)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstancesSet",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstancesSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstancesSet1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstancesSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstancesSet1Item",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstancesSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.InstancesSetItem",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_InstancesSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.LaunchTemplate",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_LaunchTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.LaunchTemplate1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_LaunchTemplate1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.LaunchTemplateConfigs",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_LaunchTemplateConfigs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.LaunchTemplateData",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_LaunchTemplateData)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.LaunchTemplateSpecification",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_LaunchTemplateSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Monitoring",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Monitoring)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Monitoring1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Monitoring1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterface",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterface1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterface1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterfaceSet",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterfaceSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterfaceSet1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterfaceSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterfaceSet1Item",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterfaceSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.NetworkInterfaceSetItem",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_NetworkInterfaceSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.OnDemandOptions",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_OnDemandOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Placement",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Placement)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.PrivateIpAddressesSet1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_PrivateIpAddressesSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.PrivateIpAddressesSet1Item",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_PrivateIpAddressesSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.PrivateIpAddressesSet2",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_PrivateIpAddressesSet2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.RequestParameters",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_RequestParameters)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.ResponseElements",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_ResponseElements)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SecurityGroupId",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SecurityGroupId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SessionContext",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SessionContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SessionIssuer",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SessionIssuer)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SpotOptions",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SpotOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SpotOptions1",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SpotOptions1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.SpotOptions2",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_SpotOptions2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.StateReason",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_StateReason)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.Tag",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_Tag)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TagSet",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TagSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TagSpecification",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TagSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TagSpecificationSet",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TagSpecificationSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TagSpecificationSetItem",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TagSpecificationSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TagSpecificationSetItemItem",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TagSpecificationSetItemItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.TargetCapacitySpecification",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_TargetCapacitySpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.AWSAPICallViaCloudTrail.UserIdentity",
		reflect.TypeOf((*InstanceEvents_AWSAPICallViaCloudTrail_UserIdentity)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.EC2InstanceStateChangeNotification",
		reflect.TypeOf((*InstanceEvents_EC2InstanceStateChangeNotification)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_InstanceEvents_EC2InstanceStateChangeNotification{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.EC2InstanceStateChangeNotification.EC2InstanceStateChangeNotificationProps",
		reflect.TypeOf((*InstanceEvents_EC2InstanceStateChangeNotification_EC2InstanceStateChangeNotificationProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.EC2SpotInstanceInterruptionWarning",
		reflect.TypeOf((*InstanceEvents_EC2SpotInstanceInterruptionWarning)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_InstanceEvents_EC2SpotInstanceInterruptionWarning{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents.EC2SpotInstanceInterruptionWarning.EC2SpotInstanceInterruptionWarningProps",
		reflect.TypeOf((*InstanceEvents_EC2SpotInstanceInterruptionWarning_EC2SpotInstanceInterruptionWarningProps)(nil)).Elem(),
	)
}
