package previewawsec2events

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail",
		reflect.TypeOf((*AWSAPICallViaCloudTrail)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_AWSAPICallViaCloudTrail{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.AWSAPICallViaCloudTrailProps",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_AWSAPICallViaCloudTrailProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.Attachment",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Attachment)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.Attributes",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Attributes)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.CapacityReservationSpecification",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_CapacityReservationSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.CpuOptions",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_CpuOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.CreateFleetRequest",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_CreateFleetRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.CreateFleetResponse",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_CreateFleetResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.CreateLaunchTemplateRequest",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_CreateLaunchTemplateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.DeleteLaunchTemplateRequest",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_DeleteLaunchTemplateRequest)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.DeleteLaunchTemplateResponse",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_DeleteLaunchTemplateResponse)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.EnclaveOptions",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_EnclaveOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.ExistingInstances",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_ExistingInstances)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.GroupSet1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GroupSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.GroupSet1Item",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GroupSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.GroupSet2",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GroupSet2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.GroupSet2Item",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GroupSet2Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.GroupSet3",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GroupSet3)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstanceMarketOptions",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstanceMarketOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstanceMarketOptions1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstanceMarketOptions1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstanceState",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstanceState)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstancesSet",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstancesSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstancesSet1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstancesSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstancesSet1Item",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstancesSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.InstancesSetItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_InstancesSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.LaunchTemplate",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_LaunchTemplate)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.LaunchTemplate1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_LaunchTemplate1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.LaunchTemplateConfigs",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_LaunchTemplateConfigs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.LaunchTemplateData",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_LaunchTemplateData)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.LaunchTemplateSpecification",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_LaunchTemplateSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.Monitoring",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Monitoring)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.Monitoring1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Monitoring1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterface",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterface1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterface1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterfaceSet",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterfaceSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterfaceSet1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterfaceSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterfaceSet1Item",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterfaceSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.NetworkInterfaceSetItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_NetworkInterfaceSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.OnDemandOptions",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_OnDemandOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.Placement",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Placement)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.PrivateIpAddressesSet1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_PrivateIpAddressesSet1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.PrivateIpAddressesSet1Item",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_PrivateIpAddressesSet1Item)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.PrivateIpAddressesSet2",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_PrivateIpAddressesSet2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.RequestParameters",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_RequestParameters)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.ResponseElements",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_ResponseElements)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SecurityGroupId",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SecurityGroupId)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SessionContext",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SessionContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SessionIssuer",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SessionIssuer)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SpotOptions",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SpotOptions)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SpotOptions1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SpotOptions1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.SpotOptions2",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SpotOptions2)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.StateReason",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_StateReason)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagSet",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagSpecification",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagSpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagSpecificationSet",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagSpecificationSet)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagSpecificationSetItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagSpecificationSetItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagSpecificationSetItemItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagSpecificationSetItemItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TagType",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TagType)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.TargetCapacitySpecification",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_TargetCapacitySpecification)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.AWSAPICallViaCloudTrail.UserIdentity",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_UserIdentity)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSMultiVolumeSnapshotsCompletionStatus",
		reflect.TypeOf((*EBSMultiVolumeSnapshotsCompletionStatus)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EBSMultiVolumeSnapshotsCompletionStatus{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSMultiVolumeSnapshotsCompletionStatus.EBSMultiVolumeSnapshotsCompletionStatusProps",
		reflect.TypeOf((*EBSMultiVolumeSnapshotsCompletionStatus_EBSMultiVolumeSnapshotsCompletionStatusProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSMultiVolumeSnapshotsCompletionStatus.Snapshot",
		reflect.TypeOf((*EBSMultiVolumeSnapshotsCompletionStatus_Snapshot)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSSnapshotNotification",
		reflect.TypeOf((*EBSSnapshotNotification)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EBSSnapshotNotification{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSSnapshotNotification.EBSSnapshotNotificationProps",
		reflect.TypeOf((*EBSSnapshotNotification_EBSSnapshotNotificationProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSVolumeNotification",
		reflect.TypeOf((*EBSVolumeNotification)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EBSVolumeNotification{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EBSVolumeNotification.EBSVolumeNotificationProps",
		reflect.TypeOf((*EBSVolumeNotification_EBSVolumeNotificationProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2FastLaunchStateChangeNotification",
		reflect.TypeOf((*EC2FastLaunchStateChangeNotification)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EC2FastLaunchStateChangeNotification{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2FastLaunchStateChangeNotification.EC2FastLaunchStateChangeNotificationProps",
		reflect.TypeOf((*EC2FastLaunchStateChangeNotification_EC2FastLaunchStateChangeNotificationProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2InstanceStateChangeNotification",
		reflect.TypeOf((*EC2InstanceStateChangeNotification)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EC2InstanceStateChangeNotification{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2InstanceStateChangeNotification.EC2InstanceStateChangeNotificationProps",
		reflect.TypeOf((*EC2InstanceStateChangeNotification_EC2InstanceStateChangeNotificationProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2SpotInstanceInterruptionWarning",
		reflect.TypeOf((*EC2SpotInstanceInterruptionWarning)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_EC2SpotInstanceInterruptionWarning{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_ec2.events.EC2SpotInstanceInterruptionWarning.EC2SpotInstanceInterruptionWarningProps",
		reflect.TypeOf((*EC2SpotInstanceInterruptionWarning_EC2SpotInstanceInterruptionWarningProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_ec2.events.InstanceEvents",
		reflect.TypeOf((*InstanceEvents)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "awsAPICallViaCloudTrailPattern", GoMethod: "AwsAPICallViaCloudTrailPattern"},
			_jsii_.MemberMethod{JsiiMethod: "ec2InstanceStateChangeNotificationPattern", GoMethod: "Ec2InstanceStateChangeNotificationPattern"},
			_jsii_.MemberMethod{JsiiMethod: "ec2SpotInstanceInterruptionWarningPattern", GoMethod: "Ec2SpotInstanceInterruptionWarningPattern"},
		},
		func() interface{} {
			return &jsiiProxy_InstanceEvents{}
		},
	)
}
