package previewawskinesisfirehosemixins

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamMixinProps",
		reflect.TypeOf((*CfnDeliveryStreamMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnDeliveryStreamPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonOpenSearchServerlessBufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonOpenSearchServerlessBufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonOpenSearchServerlessDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonOpenSearchServerlessDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonOpenSearchServerlessRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonOpenSearchServerlessRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonopensearchserviceBufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonopensearchserviceBufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonopensearchserviceDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonopensearchserviceDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AmazonopensearchserviceRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AmazonopensearchserviceRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.AuthenticationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_AuthenticationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.BufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_BufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.CatalogConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_CatalogConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.CloudWatchLoggingOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_CloudWatchLoggingOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.CopyCommandProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_CopyCommandProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DataFormatConversionConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DataFormatConversionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabaseColumnsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabaseColumnsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabaseSourceAuthenticationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabaseSourceAuthenticationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabaseSourceConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabaseSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabaseSourceVPCConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabaseSourceVPCConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabaseTablesProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabaseTablesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DatabasesProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DatabasesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DeliveryStreamEncryptionConfigurationInputProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DeliveryStreamEncryptionConfigurationInputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DeserializerProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DeserializerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DestinationTableConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DestinationTableConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DirectPutSourceConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DirectPutSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DocumentIdOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DocumentIdOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.DynamicPartitioningConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_DynamicPartitioningConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ElasticsearchBufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ElasticsearchBufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ElasticsearchDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ElasticsearchDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ElasticsearchRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ElasticsearchRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.EncryptionConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_EncryptionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ExtendedS3DestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ExtendedS3DestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.HiveJsonSerDeProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_HiveJsonSerDeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.HttpEndpointCommonAttributeProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_HttpEndpointCommonAttributeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.HttpEndpointConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_HttpEndpointConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.HttpEndpointDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_HttpEndpointDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.HttpEndpointRequestConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_HttpEndpointRequestConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.IcebergDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_IcebergDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.InputFormatConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_InputFormatConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.KMSEncryptionConfigProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_KMSEncryptionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.KinesisStreamSourceConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_KinesisStreamSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.MSKSourceConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_MSKSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.OpenXJsonSerDeProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_OpenXJsonSerDeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.OrcSerDeProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_OrcSerDeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.OutputFormatConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_OutputFormatConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ParquetSerDeProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ParquetSerDeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.PartitionFieldProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_PartitionFieldProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.PartitionSpecProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_PartitionSpecProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ProcessingConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ProcessingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ProcessorParameterProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ProcessorParameterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.ProcessorProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_ProcessorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.RedshiftDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_RedshiftDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.RedshiftRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_RedshiftRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.RetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_RetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.S3DestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_S3DestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SchemaConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SchemaConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SchemaEvolutionConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SchemaEvolutionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SecretsManagerConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SecretsManagerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SerializerProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SerializerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SnowflakeBufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SnowflakeBufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SnowflakeDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SnowflakeDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SnowflakeRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SnowflakeRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SnowflakeRoleConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SnowflakeRoleConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SnowflakeVpcConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SnowflakeVpcConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SplunkBufferingHintsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SplunkBufferingHintsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SplunkDestinationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SplunkDestinationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.SplunkRetryOptionsProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_SplunkRetryOptionsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.TableCreationConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_TableCreationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_kinesisfirehose.mixins.CfnDeliveryStreamPropsMixin.VpcConfigurationProperty",
		reflect.TypeOf((*CfnDeliveryStreamPropsMixin_VpcConfigurationProperty)(nil)).Elem(),
	)
}
