package internal
import (
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawselasticloadbalancingv2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
)
type Type__constructsConstruct = constructs.Construct
type Type__awscdkResource = awscdk.Resource
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawselasticloadbalancingv2IListenerRef = interfacesawselasticloadbalancingv2.IListenerRef
type Type__interfacesawselasticloadbalancingv2IListenerCertificateRef = interfacesawselasticloadbalancingv2.IListenerCertificateRef
type Type__interfacesawselasticloadbalancingv2IListenerRuleRef = interfacesawselasticloadbalancingv2.IListenerRuleRef
type Type__interfacesawselasticloadbalancingv2ILoadBalancerRef = interfacesawselasticloadbalancingv2.ILoadBalancerRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawselasticloadbalancingv2ITargetGroupRef = interfacesawselasticloadbalancingv2.ITargetGroupRef
type Type__interfacesawselasticloadbalancingv2ITrustStoreRef = interfacesawselasticloadbalancingv2.ITrustStoreRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawselasticloadbalancingv2ITrustStoreRevocationRef = interfacesawselasticloadbalancingv2.ITrustStoreRevocationRef
type Type__awsec2IConnectable = awsec2.IConnectable
type Type__awscdkIResource = awscdk.IResource
type Type__awsec2IVpcEndpointServiceLoadBalancer = awsec2.IVpcEndpointServiceLoadBalancer
type Type__constructsIConstruct = constructs.IConstruct
