package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsservicecatalog"
	"github.com/aws/constructs-go/constructs/v10"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsservicecatalogIAcceptedPortfolioShareRef = interfacesawsservicecatalog.IAcceptedPortfolioShareRef
type Type__interfacesawsservicecatalogICloudFormationProductRef = interfacesawsservicecatalog.ICloudFormationProductRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsservicecatalogICloudFormationProvisionedProductRef = interfacesawsservicecatalog.ICloudFormationProvisionedProductRef
type Type__interfacesawsservicecatalogILaunchNotificationConstraintRef = interfacesawsservicecatalog.ILaunchNotificationConstraintRef
type Type__interfacesawsservicecatalogILaunchRoleConstraintRef = interfacesawsservicecatalog.ILaunchRoleConstraintRef
type Type__interfacesawsservicecatalogILaunchTemplateConstraintRef = interfacesawsservicecatalog.ILaunchTemplateConstraintRef
type Type__interfacesawsservicecatalogIPortfolioRef = interfacesawsservicecatalog.IPortfolioRef
type Type__interfacesawsservicecatalogIPortfolioPrincipalAssociationRef = interfacesawsservicecatalog.IPortfolioPrincipalAssociationRef
type Type__interfacesawsservicecatalogIPortfolioProductAssociationRef = interfacesawsservicecatalog.IPortfolioProductAssociationRef
type Type__interfacesawsservicecatalogIPortfolioShareRef = interfacesawsservicecatalog.IPortfolioShareRef
type Type__interfacesawsservicecatalogIResourceUpdateConstraintRef = interfacesawsservicecatalog.IResourceUpdateConstraintRef
type Type__interfacesawsservicecatalogIServiceActionRef = interfacesawsservicecatalog.IServiceActionRef
type Type__interfacesawsservicecatalogIServiceActionAssociationRef = interfacesawsservicecatalog.IServiceActionAssociationRef
type Type__interfacesawsservicecatalogIStackSetConstraintRef = interfacesawsservicecatalog.IStackSetConstraintRef
type Type__interfacesawsservicecatalogITagOptionRef = interfacesawsservicecatalog.ITagOptionRef
type Type__interfacesawsservicecatalogITagOptionAssociationRef = interfacesawsservicecatalog.ITagOptionAssociationRef
type Type__awscdkIResource = awscdk.IResource
type Type__awscdkResource = awscdk.Resource
type Type__awscdkStack = awscdk.Stack
type Type__constructsConstruct = constructs.Construct
