package previewawsdevopsguruevents

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed",
		reflect.TypeOf((*DevOpsGuruInsightClosed)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DevOpsGuruInsightClosed{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.AlarmCondition",
		reflect.TypeOf((*DevOpsGuruInsightClosed_AlarmCondition)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.Anomaly",
		reflect.TypeOf((*DevOpsGuruInsightClosed_Anomaly)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.AnomalyResource",
		reflect.TypeOf((*DevOpsGuruInsightClosed_AnomalyResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.AnomalySourceMetadata",
		reflect.TypeOf((*DevOpsGuruInsightClosed_AnomalySourceMetadata)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.CloudFormation",
		reflect.TypeOf((*DevOpsGuruInsightClosed_CloudFormation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.CloudWatchDimension",
		reflect.TypeOf((*DevOpsGuruInsightClosed_CloudWatchDimension)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.DataIdentifiers",
		reflect.TypeOf((*DevOpsGuruInsightClosed_DataIdentifiers)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.DevOpsGuruInsightClosedProps",
		reflect.TypeOf((*DevOpsGuruInsightClosed_DevOpsGuruInsightClosedProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.GroupBy",
		reflect.TypeOf((*DevOpsGuruInsightClosed_GroupBy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.MetricQuery",
		reflect.TypeOf((*DevOpsGuruInsightClosed_MetricQuery)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.ReferenceValue",
		reflect.TypeOf((*DevOpsGuruInsightClosed_ReferenceValue)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.ResourceCollection",
		reflect.TypeOf((*DevOpsGuruInsightClosed_ResourceCollection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.SourceDetail",
		reflect.TypeOf((*DevOpsGuruInsightClosed_SourceDetail)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightClosed.TagType",
		reflect.TypeOf((*DevOpsGuruInsightClosed_TagType)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DevOpsGuruInsightSeverityUpgraded{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.AlarmCondition",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_AlarmCondition)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.Anomaly",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_Anomaly)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.AnomalyResource",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_AnomalyResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.AnomalySourceMetadata",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_AnomalySourceMetadata)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.CloudFormation",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_CloudFormation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.CloudWatchDimension",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_CloudWatchDimension)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.DataIdentifiers",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_DataIdentifiers)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.DevOpsGuruInsightSeverityUpgradedProps",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_DevOpsGuruInsightSeverityUpgradedProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.GroupBy",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_GroupBy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.MetricQuery",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_MetricQuery)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.ReferenceValue",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_ReferenceValue)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.ResourceCollection",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_ResourceCollection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.SourceDetail",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_SourceDetail)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruInsightSeverityUpgraded.TagType",
		reflect.TypeOf((*DevOpsGuruInsightSeverityUpgraded_TagType)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DevOpsGuruNewAnomalyAssociation{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.AlarmCondition",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_AlarmCondition)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.Anomaly",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_Anomaly)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.AnomalyResource",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_AnomalyResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.AnomalySourceMetadata",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_AnomalySourceMetadata)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.CloudFormation",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_CloudFormation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.CloudWatchDimension",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_CloudWatchDimension)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.DataIdentifiers",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_DataIdentifiers)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.DevOpsGuruNewAnomalyAssociationProps",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_DevOpsGuruNewAnomalyAssociationProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.GroupBy",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_GroupBy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.MetricQuery",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_MetricQuery)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.ReferenceValue",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_ReferenceValue)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.ResourceCollection",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_ResourceCollection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.SourceDetail",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_SourceDetail)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewAnomalyAssociation.TagType",
		reflect.TypeOf((*DevOpsGuruNewAnomalyAssociation_TagType)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DevOpsGuruNewInsightOpen{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.AlarmCondition",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_AlarmCondition)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.Anomaly",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_Anomaly)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.AnomalyResource",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_AnomalyResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.AnomalySourceMetadata",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_AnomalySourceMetadata)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.CloudFormation",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_CloudFormation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.CloudWatchDimension",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_CloudWatchDimension)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.DataIdentifiers",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_DataIdentifiers)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.DevOpsGuruNewInsightOpenProps",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_DevOpsGuruNewInsightOpenProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.GroupBy",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_GroupBy)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.MetricQuery",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_MetricQuery)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.ReferenceValue",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_ReferenceValue)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.ResourceCollection",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_ResourceCollection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.SourceDetail",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_SourceDetail)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewInsightOpen.TagType",
		reflect.TypeOf((*DevOpsGuruNewInsightOpen_TagType)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_DevOpsGuruNewRecommendationCreated{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.AnomalyResource",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_AnomalyResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.CloudFormation",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_CloudFormation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.CloudWatchDimension",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_CloudWatchDimension)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.DevOpsGuruNewRecommendationCreatedProps",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_DevOpsGuruNewRecommendationCreatedProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.EventResource",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_EventResource)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.Recommendation",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_Recommendation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.RelatedAnomaly",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_RelatedAnomaly)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.RelatedAnomalySourceDetail",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_RelatedAnomalySourceDetail)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.RelatedEvent",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_RelatedEvent)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.ResourceCollection",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_ResourceCollection)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_devopsguru.events.DevOpsGuruNewRecommendationCreated.TagType",
		reflect.TypeOf((*DevOpsGuruNewRecommendationCreated_TagType)(nil)).Elem(),
	)
}
