package previewawssesmixins


// Experimental.
type CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields string

const (
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_INGRESS_POINT_TYPE CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "INGRESS_POINT_TYPE"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_INGRESS_POINT_ID CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "INGRESS_POINT_ID"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_INGRESS_POINT_SESSION_ID CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "INGRESS_POINT_SESSION_ID"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_TRAFFIC_POLICY_ID CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "TRAFFIC_POLICY_ID"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_TRAFFIC_POLICY_EVALUATION CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "TRAFFIC_POLICY_EVALUATION"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_TRAFFIC_POLICY_VERDICT CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "TRAFFIC_POLICY_VERDICT"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_SENDER_IP_ADDRESS CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "SENDER_IP_ADDRESS"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_SMTP_MAIL_FROM CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "SMTP_MAIL_FROM"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_SMTP_HELO CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "SMTP_HELO"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_TLS_PROTOCOL CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "TLS_PROTOCOL"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_RECIPIENT CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "RECIPIENT"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_TLS_CIPHER_SUITE CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "TLS_CIPHER_SUITE"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_RESOURCE_ARN CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "RESOURCE_ARN"
	// Experimental.
	CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields_EVENT_TIMESTAMP CfnMailManagerIngressPointTrafficPolicyDebugLogsRecordFields = "EVENT_TIMESTAMP"
)

