package awsmediaconnectalpha

import (
	_init_ "github.com/aws/aws-cdk-go/awsmediaconnectalpha/v2/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awscloudwatch"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsmediaconnect"
	"github.com/aws/aws-cdk-go/awsmediaconnectalpha/v2/internal"
	"github.com/aws/constructs-go/constructs/v10"
)

// Defines an AWS Elemental MediaConnect Flow.
//
// Example:
//   var stack Stack
//   var securityGroup ISecurityGroup
//   var subnet ISubnet
//   var role IRole
//
//
//   vpcInterface := awsmediaconnectalpha.VpcInterface_Define(&VpcInterfaceDefineProps{
//   	VpcInterfaceName: jsii.String("my-vpc-interface"),
//   	Role: role,
//   	SecurityGroups: []ISecurityGroup{
//   		securityGroup,
//   	},
//   	Subnet: subnet,
//   })
//
//   flow := awsmediaconnectalpha.NewFlow(stack, jsii.String("MyFlow"), &FlowProps{
//   	Source: awsmediaconnectalpha.SourceConfiguration_Rist(&SourceRist{
//   		FlowSourceName: jsii.String("vpc-source"),
//   		Description: jsii.String("VPC-based source"),
//   		Port: jsii.Number(5000),
//   		MaxLatency: awscdk.Duration_Millis(jsii.Number(2000)),
//   		Network: awsmediaconnectalpha.NetworkConfiguration_Vpc(vpcInterface),
//   	}),
//   	VpcInterfaces: []VpcInterfaceConfig{
//   		vpcInterface,
//   	},
//   })
//
// Experimental.
type Flow interface {
	awscdk.Resource
	IFlow
	// The IP address that the flow uses to send outbound content.
	// Experimental.
	EgressIp() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	// Experimental.
	Env() *interfaces.ResourceEnvironment
	// The Amazon Resource Name (ARN) of the flow.
	// Experimental.
	FlowArn() *string
	// The Availability Zone that the flow was created in.
	// Experimental.
	FlowAvailabilityZone() *string
	// A reference to this Flow resource.
	//
	// Required by the auto-generated IFlowRef interface.
	// Experimental.
	FlowRef() *interfacesawsmediaconnect.FlowReference
	// Collection of grant methods for this flow.
	// Experimental.
	Grants() FlowGrants
	// Failover Configuration for flow.
	// Experimental.
	IsFailoverEnabled() *bool
	// The tree node.
	// Experimental.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The Amazon Resource Name (ARN) of the source defined on the flow.
	// Experimental.
	SourceArn() *string
	// The IP address that the flow listens on for incoming content.
	//
	// Available for listener-style source protocols (RTP, RTP-FEC, RIST, SRT listener,
	// Zixi push). Accessing this on SRT caller, entitlement, gateway bridge, router,
	// CDI, JPEG XS, or imported flows throws — those sources don't expose a listening
	// IP address.
	// Experimental.
	SourceIngestIp() *string
	// The port that the flow listens on for incoming content.
	//
	// Available for the same listener-style source protocols as `sourceIngestIp`.
	// Accessing this on SRT caller, entitlement, gateway bridge, router, CDI, JPEG XS,
	// or imported flows throws.
	// Experimental.
	SourceIngestPort() *string
	// The full ingest URL for the flow source, combining protocol, IP, and port. For example: `srt://203.0.113.10:5000`.
	//
	// Available for listener-style source protocols (RTP, RTP-FEC, RIST, SRT listener,
	// Zixi push) where the flow listens for an upstream sender. Accessing this on
	// SRT caller, entitlement, gateway bridge, router, CDI, JPEG XS, or imported
	// flows throws — those sources don't expose a single host:port ingest URL.
	// Experimental.
	SourceIngestUrl() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Add an output to this flow.
	// Experimental.
	AddOutput(id *string, options *AddFlowOutputOptions) IFlowOutput
	// Add a VPC interface to this flow.
	// Experimental.
	AddVpcInterface(vpc *VpcInterfaceConfig) *VpcInterfaceConfig
	// Override the cross-stack reference strength for this resource.
	//
	// When set, any cross-stack reference to this resource will use the specified
	// mechanism instead of the global default determined by the
	// `@aws-cdk/core:defaultCrossStackReferences` context key. This is useful for
	// selectively weakening specific references to avoid the "deadly embrace" problem
	// without changing the app-wide default.
	// Experimental.
	ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Create a CloudWatch metric for this flow.
	// Experimental.
	Metric(metricName *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the bitrate of content ingested into the flow.
	//
	// Emits the `SourceBitRate` metric with dimension `FlowARN`, which aggregates across
	// all sources on the flow. To narrow to a specific source on a multi-source flow, call
	// {@link metric} with an additional `SourceARN` dimension.
	// Default: - average over 60 seconds.
	//
	// Experimental.
	MetricSourceBitrate(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric indicating the connection state of the source.
	//
	// 1 for connected, 0 for disconnected.
	// Applies only to Zixi, SRT, and RIST sources.
	//
	// Emits the `SourceConnected` metric with dimension `FlowARN`.
	// Default: - minimum over 60 seconds.
	//
	// Experimental.
	MetricSourceConnected(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the number of times the source transitioned from connected to disconnected.
	//
	// Emits the `SourceDisconnections` metric with dimension `FlowARN`.
	// Default: - sum over 60 seconds.
	//
	// Experimental.
	MetricSourceDisconnections(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the number of packets lost during transit, measured before any error correction takes place.
	//
	// Emits the `SourceDroppedPackets` metric with dimension `FlowARN`.
	// Default: - sum over 60 seconds.
	//
	// Experimental.
	MetricSourceDroppedPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the current network jitter of the source, measured in milliseconds.
	//
	// Emits the `SourceJitter` metric with dimension `FlowARN`.
	// Default: - average over 60 seconds.
	//
	// Experimental.
	MetricSourceJitter(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for packets that were lost in transit and not recovered by error correction.
	//
	// Emits the `SourceNotRecoveredPackets` metric with dimension `FlowARN`, which aggregates
	// across all sources on the flow.
	// Default: - sum over 60 seconds.
	//
	// Experimental.
	MetricSourceNotRecoveredPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the percentage of packets lost during transit, even if they were recovered.
	//
	// Emits the `SourcePacketLossPercent` metric with dimension `FlowARN`.
	// Default: - average over 60 seconds.
	//
	// Experimental.
	MetricSourcePacketLossPercent(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the round-trip time between the source and MediaConnect. Applies only to RIST, Zixi, and SRT sources.
	//
	// Emits the `SourceRoundTripTime` metric with dimension `FlowARN`.
	// Default: - average over 60 seconds.
	//
	// Experimental.
	MetricSourceRoundTripTime(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric indicating which source is selected for ingest when using `Failover` failover mode.
	//
	// A value of 1 indicates the source is being used as the input; 0 indicates it is standby.
	//
	// Emits the `SourceSelected` metric with dimension `FlowARN`. To narrow to a specific source,
	// call {@link metric} with an additional `SourceARN` dimension.
	// Default: - maximum over 60 seconds.
	//
	// Experimental.
	MetricSourceSelected(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Metric for the total number of packets received by the flow sources.
	//
	// Emits the `SourceTotalPackets` metric with dimension `FlowARN`, which aggregates across
	// all sources on the flow.
	// Default: - sum over 60 seconds.
	//
	// Experimental.
	MetricSourceTotalPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	// Experimental.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for Flow
type jsiiProxy_Flow struct {
	internal.Type__awscdkResource
	jsiiProxy_IFlow
}

func (j *jsiiProxy_Flow) EgressIp() *string {
	var returns *string
	_jsii_.Get(
		j,
		"egressIp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) FlowArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"flowArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) FlowAvailabilityZone() *string {
	var returns *string
	_jsii_.Get(
		j,
		"flowAvailabilityZone",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) FlowRef() *interfacesawsmediaconnect.FlowReference {
	var returns *interfacesawsmediaconnect.FlowReference
	_jsii_.Get(
		j,
		"flowRef",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) Grants() FlowGrants {
	var returns FlowGrants
	_jsii_.Get(
		j,
		"grants",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) IsFailoverEnabled() *bool {
	var returns *bool
	_jsii_.Get(
		j,
		"isFailoverEnabled",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) SourceArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"sourceArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) SourceIngestIp() *string {
	var returns *string
	_jsii_.Get(
		j,
		"sourceIngestIp",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) SourceIngestPort() *string {
	var returns *string
	_jsii_.Get(
		j,
		"sourceIngestPort",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) SourceIngestUrl() *string {
	var returns *string
	_jsii_.Get(
		j,
		"sourceIngestUrl",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Flow) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewFlow(scope constructs.Construct, id *string, props *FlowProps) Flow {
	_init_.Initialize()

	if err := validateNewFlowParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_Flow{}

	_jsii_.Create(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewFlow_Override(f Flow, scope constructs.Construct, id *string, props *FlowProps) {
	_init_.Initialize()

	_jsii_.Create(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		[]interface{}{scope, id, props},
		f,
	)
}

// Import an existing Flow from its ARN.
//
// Use `fromFlowAttributes()` instead if you need access to `sourceArn` or any other
// attribute not encoded in the flow ARN.
// Experimental.
func Flow_FromFlowArn(scope constructs.Construct, id *string, flowArn *string) IFlow {
	_init_.Initialize()

	if err := validateFlow_FromFlowArnParameters(scope, id, flowArn); err != nil {
		panic(err)
	}
	var returns IFlow

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"fromFlowArn",
		[]interface{}{scope, id, flowArn},
		&returns,
	)

	return returns
}

// Creates a Flow construct that represents an external (imported) Flow.
// Experimental.
func Flow_FromFlowAttributes(scope constructs.Construct, id *string, attrs *FlowAttributes) IFlow {
	_init_.Initialize()

	if err := validateFlow_FromFlowAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IFlow

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"fromFlowAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
// Experimental.
func Flow_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateFlow_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
// Experimental.
func Flow_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateFlow_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func Flow_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateFlow_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func Flow_PROPERTY_INJECTION_ID() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"@aws-cdk/aws-mediaconnect-alpha.Flow",
		"PROPERTY_INJECTION_ID",
		&returns,
	)
	return returns
}

func (f *jsiiProxy_Flow) AddOutput(id *string, options *AddFlowOutputOptions) IFlowOutput {
	if err := f.validateAddOutputParameters(id, options); err != nil {
		panic(err)
	}
	var returns IFlowOutput

	_jsii_.Invoke(
		f,
		"addOutput",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) AddVpcInterface(vpc *VpcInterfaceConfig) *VpcInterfaceConfig {
	if err := f.validateAddVpcInterfaceParameters(vpc); err != nil {
		panic(err)
	}
	var returns *VpcInterfaceConfig

	_jsii_.Invoke(
		f,
		"addVpcInterface",
		[]interface{}{vpc},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength) {
	if err := f.validateApplyCrossStackReferenceStrengthParameters(strength); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		f,
		"applyCrossStackReferenceStrength",
		[]interface{}{strength},
	)
}

func (f *jsiiProxy_Flow) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := f.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		f,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (f *jsiiProxy_Flow) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		f,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := f.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		f,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) GetResourceNameAttribute(nameAttr *string) *string {
	if err := f.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		f,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) Metric(metricName *string, props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricParameters(metricName, props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metric",
		[]interface{}{metricName, props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceBitrate(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceBitrateParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceBitrate",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceConnected(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceConnectedParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceConnected",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceDisconnections(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceDisconnectionsParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceDisconnections",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceDroppedPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceDroppedPacketsParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceDroppedPackets",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceJitter(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceJitterParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceJitter",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceNotRecoveredPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceNotRecoveredPacketsParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceNotRecoveredPackets",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourcePacketLossPercent(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourcePacketLossPercentParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourcePacketLossPercent",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceRoundTripTime(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceRoundTripTimeParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceRoundTripTime",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceSelected(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceSelectedParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceSelected",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) MetricSourceTotalPackets(props *awscloudwatch.MetricOptions) awscloudwatch.Metric {
	if err := f.validateMetricSourceTotalPacketsParameters(props); err != nil {
		panic(err)
	}
	var returns awscloudwatch.Metric

	_jsii_.Invoke(
		f,
		"metricSourceTotalPackets",
		[]interface{}{props},
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		f,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (f *jsiiProxy_Flow) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		f,
		"with",
		args,
		&returns,
	)

	return returns
}

