package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsverifiedpermissions"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsverifiedpermissionsIIdentitySourceRef = interfacesawsverifiedpermissions.IIdentitySourceRef
type Type__interfacesawsverifiedpermissionsIPolicyRef = interfacesawsverifiedpermissions.IPolicyRef
type Type__interfacesawsverifiedpermissionsIPolicyStoreRef = interfacesawsverifiedpermissions.IPolicyStoreRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsverifiedpermissionsIPolicyTemplateRef = interfacesawsverifiedpermissions.IPolicyTemplateRef
