package awsmedialive

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelMixinProps",
		reflect.TypeOf((*CfnChannelMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPlacementGroupMixinProps",
		reflect.TypeOf((*CfnChannelPlacementGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPlacementGroupPropsMixin",
		reflect.TypeOf((*CfnChannelPlacementGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnChannelPlacementGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin",
		reflect.TypeOf((*CfnChannelPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnChannelPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AacSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AacSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Ac3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Ac3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AdditionalDestinationsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AdditionalDestinationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AncillarySourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AncillarySourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AnywhereSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AnywhereSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ArchiveCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ArchiveContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ArchiveGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ArchiveOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ArchiveS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ArchiveS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AribDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AribDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AribSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AribSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioChannelMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioChannelMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioCodecSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioCodecSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioDolbyEDecodeProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioDolbyEDecodeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioHlsRenditionSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioHlsRenditionSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioLanguageSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioLanguageSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioNormalizationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioNormalizationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioOnlyHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioOnlyHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioPidSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioPidSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioSilenceFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioSilenceFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioTrackProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioTrackProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioTrackSelectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioTrackSelectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AudioWatermarkSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AudioWatermarkSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AutomaticInputFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AutomaticInputFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Av1ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Av1ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Av1SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Av1SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AvailBlankingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailBlankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AvailConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.AvailSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_AvailSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.BandwidthReductionFilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BandwidthReductionFilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.BlackoutSlateProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BlackoutSlateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.BurnInDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_BurnInDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionLanguageMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionLanguageMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionRectangleProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionRectangleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CaptionSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CaptionSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CdiInputSpecificationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CdiInputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ChannelEngineVersionRequestProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ChannelEngineVersionRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CmafIngestCaptionLanguageMappingProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestCaptionLanguageMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CmafIngestGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.CmafIngestOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_CmafIngestOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ColorCorrectionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorCorrectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ColorCorrectionSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorCorrectionSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ColorSpacePassthroughSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ColorSpacePassthroughSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DisabledLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DisabledLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DolbyVision81SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DolbyVision81SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DvbNitSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbNitSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DvbSdtSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSdtSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DvbSubDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSubDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DvbSubSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbSubSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.DvbTdtSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_DvbTdtSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Eac3AtmosSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Eac3AtmosSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Eac3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Eac3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EbuTtDDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EbuTtDDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EmbeddedDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EmbeddedPlusScte20DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedPlusScte20DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EmbeddedSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EmbeddedSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EncoderSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EncoderSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EpochLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EpochLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.EsamProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_EsamProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FailoverConditionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FailoverConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FailoverConditionSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FailoverConditionSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FeatureActivationsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FeatureActivationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FecOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FecOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Fmp4HlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Fmp4HlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FollowerChannelSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FollowerChannelSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.FrameCaptureSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_FrameCaptureSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.GlobalConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_GlobalConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H264ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H264FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H264SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H264SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H265ColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265ColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H265FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.H265SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_H265SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Hdr10SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Hdr10SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsAkamaiSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsAkamaiSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsBasicPutSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsBasicPutSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsCdnSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsCdnSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsMediaStoreSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsMediaStoreSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsS3SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsS3SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HlsWebdavSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HlsWebdavSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.HtmlMotionGraphicsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_HtmlMotionGraphicsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InferenceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InferenceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputAttachmentProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputAttachmentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputChannelLevelProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputChannelLevelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputLocationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputLossBehaviorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLossBehaviorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputLossFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputLossFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.InputSpecificationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_InputSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.KeyProviderSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_KeyProviderSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.LinkedChannelSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_LinkedChannelSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.M2tsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_M2tsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.M3u8SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_M3u8SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MaintenanceCreateSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MaintenanceCreateSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaConnectRouterContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaConnectRouterContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaConnectRouterGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaConnectRouterGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaConnectRouterOutputConnectionMapProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaConnectRouterOutputConnectionMapProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaConnectRouterOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaConnectRouterOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaConnectRouterOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaConnectRouterOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageAdditionalDestinationsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageAdditionalDestinationsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageV2DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageV2DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MediaPackageV2GroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MediaPackageV2GroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MotionGraphicsConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MotionGraphicsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MotionGraphicsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MotionGraphicsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Mp2SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mp2SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Mpeg2FilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mpeg2FilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Mpeg2SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Mpeg2SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MsSmoothGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MsSmoothGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MsSmoothOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MsSmoothOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MulticastInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MulticastInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MultiplexContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MultiplexGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MultiplexM2tsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexM2tsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MultiplexOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.MultiplexProgramChannelDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_MultiplexProgramChannelDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.NetworkInputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NetworkInputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.NielsenCBETProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenCBETProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.NielsenConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.NielsenNaesIiNwProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenNaesIiNwProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.NielsenWatermarksSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_NielsenWatermarksSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputDestinationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputGroupProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputLocationRefProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputLocationRefProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.OutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_OutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.PassThroughSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_PassThroughSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.PipelineLockingSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_PipelineLockingSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.PrimaryChannelSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_PrimaryChannelSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.RawSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RawSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Rec601SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Rec601SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Rec709SettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Rec709SettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.RemixSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RemixSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.RtmpCaptionInfoDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpCaptionInfoDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.RtmpGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.RtmpOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_RtmpOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte20PlusEmbeddedDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte20PlusEmbeddedDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte20SourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte20SourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte27DestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte27DestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte27SourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte27SourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte35SpliceInsertProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte35SpliceInsertProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.Scte35TimeSignalAposProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_Scte35TimeSignalAposProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.SmpteTtDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SmpteTtDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.SrtGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.SrtOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.SrtOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_SrtOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.StandardHlsSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_StandardHlsSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.StaticKeySettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_StaticKeySettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TeletextDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TeletextDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TeletextSourceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TeletextSourceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TemporalFilterSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TemporalFilterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.ThumbnailConfigurationProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_ThumbnailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TimecodeBurninSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TimecodeBurninSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TimecodeConfigProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TimecodeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.TtmlDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_TtmlDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.UdpContainerSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpContainerSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.UdpGroupSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.UdpOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_UdpOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoBlackFailoverSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoBlackFailoverSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoCodecSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoCodecSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoDescriptionProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoDescriptionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoSelectorColorSpaceSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorColorSpaceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoSelectorPidProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorPidProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoSelectorProgramIdProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorProgramIdProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoSelectorProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VideoSelectorSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VideoSelectorSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.VpcOutputSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_VpcOutputSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.WavSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_WavSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnChannelPropsMixin.WebvttDestinationSettingsProperty",
		reflect.TypeOf((*CfnChannelPropsMixin_WebvttDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnCloudWatchAlarmTemplateGroupMixinProps",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnCloudWatchAlarmTemplateGroupPropsMixin",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnCloudWatchAlarmTemplateGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnCloudWatchAlarmTemplateMixinProps",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplateMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnCloudWatchAlarmTemplatePropsMixin",
		reflect.TypeOf((*CfnCloudWatchAlarmTemplatePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnCloudWatchAlarmTemplatePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnClusterMixinProps",
		reflect.TypeOf((*CfnClusterMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnClusterPropsMixin",
		reflect.TypeOf((*CfnClusterPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnClusterPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnClusterPropsMixin.ClusterNetworkSettingsProperty",
		reflect.TypeOf((*CfnClusterPropsMixin_ClusterNetworkSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnClusterPropsMixin.InterfaceMappingProperty",
		reflect.TypeOf((*CfnClusterPropsMixin_InterfaceMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnEventBridgeRuleTemplateGroupMixinProps",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnEventBridgeRuleTemplateGroupPropsMixin",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnEventBridgeRuleTemplateGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnEventBridgeRuleTemplateMixinProps",
		reflect.TypeOf((*CfnEventBridgeRuleTemplateMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnEventBridgeRuleTemplatePropsMixin",
		reflect.TypeOf((*CfnEventBridgeRuleTemplatePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnEventBridgeRuleTemplatePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnEventBridgeRuleTemplatePropsMixin.EventBridgeRuleTemplateTargetProperty",
		reflect.TypeOf((*CfnEventBridgeRuleTemplatePropsMixin_EventBridgeRuleTemplateTargetProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputMixinProps",
		reflect.TypeOf((*CfnInputMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin",
		reflect.TypeOf((*CfnInputPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnInputPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputDestinationRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputDestinationRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputDeviceSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputDeviceSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputRequestDestinationRouteProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputRequestDestinationRouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputSdpLocationProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputSdpLocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputSourceRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputSourceRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.InputVpcRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_InputVpcRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.MediaConnectFlowRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MediaConnectFlowRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.MulticastSettingsCreateRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MulticastSettingsCreateRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.MulticastSourceCreateRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_MulticastSourceCreateRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.RouterDestinationSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_RouterDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.RouterSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_RouterSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.Smpte2110ReceiverGroupProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.Smpte2110ReceiverGroupSdpSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupSdpSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.Smpte2110ReceiverGroupSettingsProperty",
		reflect.TypeOf((*CfnInputPropsMixin_Smpte2110ReceiverGroupSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.SrtCallerDecryptionRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtCallerDecryptionRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.SrtCallerSourceRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtCallerSourceRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.SrtListenerDecryptionRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtListenerDecryptionRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.SrtListenerSettingsRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtListenerSettingsRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputPropsMixin.SrtSettingsRequestProperty",
		reflect.TypeOf((*CfnInputPropsMixin_SrtSettingsRequestProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputSecurityGroupMixinProps",
		reflect.TypeOf((*CfnInputSecurityGroupMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputSecurityGroupPropsMixin",
		reflect.TypeOf((*CfnInputSecurityGroupPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnInputSecurityGroupPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnInputSecurityGroupPropsMixin.InputWhitelistRuleCidrProperty",
		reflect.TypeOf((*CfnInputSecurityGroupPropsMixin_InputWhitelistRuleCidrProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexMixinProps",
		reflect.TypeOf((*CfnMultiplexMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexPropsMixin",
		reflect.TypeOf((*CfnMultiplexPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnMultiplexPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexPropsMixin.MultiplexMediaConnectOutputDestinationSettingsProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexMediaConnectOutputDestinationSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexPropsMixin.MultiplexOutputDestinationProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexOutputDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexPropsMixin.MultiplexSettingsProperty",
		reflect.TypeOf((*CfnMultiplexPropsMixin_MultiplexSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramMixinProps",
		reflect.TypeOf((*CfnMultiplexprogramMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnMultiplexprogramPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexProgramPacketIdentifiersMapProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramPacketIdentifiersMapProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexProgramPipelineDetailProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramPipelineDetailProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexProgramServiceDescriptorProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramServiceDescriptorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexProgramSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexProgramSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexStatmuxVideoSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexStatmuxVideoSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnMultiplexprogramPropsMixin.MultiplexVideoSettingsProperty",
		reflect.TypeOf((*CfnMultiplexprogramPropsMixin_MultiplexVideoSettingsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnNetworkMixinProps",
		reflect.TypeOf((*CfnNetworkMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnNetworkPropsMixin",
		reflect.TypeOf((*CfnNetworkPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnNetworkPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnNetworkPropsMixin.IpPoolProperty",
		reflect.TypeOf((*CfnNetworkPropsMixin_IpPoolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnNetworkPropsMixin.RouteProperty",
		reflect.TypeOf((*CfnNetworkPropsMixin_RouteProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSdiSourceMixinProps",
		reflect.TypeOf((*CfnSdiSourceMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSdiSourcePropsMixin",
		reflect.TypeOf((*CfnSdiSourcePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnSdiSourcePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapMixinProps",
		reflect.TypeOf((*CfnSignalMapMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapPropsMixin",
		reflect.TypeOf((*CfnSignalMapPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnSignalMapPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapPropsMixin.MediaResourceNeighborProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MediaResourceNeighborProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapPropsMixin.MediaResourceProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MediaResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapPropsMixin.MonitorDeploymentProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_MonitorDeploymentProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_medialive.CfnSignalMapPropsMixin.SuccessfulMonitorDeploymentProperty",
		reflect.TypeOf((*CfnSignalMapPropsMixin_SuccessfulMonitorDeploymentProperty)(nil)).Elem(),
	)
}
