package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsmediatailor"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsmediatailorIChannelRef = interfacesawsmediatailor.IChannelRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsmediatailorIChannelPolicyRef = interfacesawsmediatailor.IChannelPolicyRef
type Type__interfacesawsmediatailorILiveSourceRef = interfacesawsmediatailor.ILiveSourceRef
type Type__interfacesawsmediatailorIPlaybackConfigurationRef = interfacesawsmediatailor.IPlaybackConfigurationRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsmediatailorISourceLocationRef = interfacesawsmediatailor.ISourceLocationRef
type Type__interfacesawsmediatailorIVodSourceRef = interfacesawsmediatailor.IVodSourceRef
