package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/awselasticloadbalancingv2"
)
type Type__awselasticloadbalancingv2INetworkLoadBalancerTarget = awselasticloadbalancingv2.INetworkLoadBalancerTarget
type Type__awselasticloadbalancingv2IApplicationLoadBalancerTarget = awselasticloadbalancingv2.IApplicationLoadBalancerTarget
