package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawssecurityagent"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawssecurityagentIAgentSpaceRef = interfacesawssecurityagent.IAgentSpaceRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawssecurityagentIApplicationRef = interfacesawssecurityagent.IApplicationRef
type Type__interfacesawssecurityagentIPentestRef = interfacesawssecurityagent.IPentestRef
type Type__interfacesawssecurityagentISecurityRequirementPackRef = interfacesawssecurityagent.ISecurityRequirementPackRef
type Type__interfacesawssecurityagentITargetDomainRef = interfacesawssecurityagent.ITargetDomainRef
