package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsdeadline"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsdeadlineIFarmRef = interfacesawsdeadline.IFarmRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsdeadlineIFleetRef = interfacesawsdeadline.IFleetRef
type Type__interfacesawsdeadlineILicenseEndpointRef = interfacesawsdeadline.ILicenseEndpointRef
type Type__interfacesawsdeadlineILimitRef = interfacesawsdeadline.ILimitRef
type Type__interfacesawsdeadlineIMeteredProductRef = interfacesawsdeadline.IMeteredProductRef
type Type__interfacesawsdeadlineIMonitorRef = interfacesawsdeadline.IMonitorRef
type Type__interfacesawsdeadlineIQueueRef = interfacesawsdeadline.IQueueRef
type Type__interfacesawsdeadlineIQueueEnvironmentRef = interfacesawsdeadline.IQueueEnvironmentRef
type Type__interfacesawsdeadlineIQueueFleetAssociationRef = interfacesawsdeadline.IQueueFleetAssociationRef
type Type__interfacesawsdeadlineIQueueLimitAssociationRef = interfacesawsdeadline.IQueueLimitAssociationRef
type Type__interfacesawsdeadlineIStorageProfileRef = interfacesawsdeadline.IStorageProfileRef
