package awscloudwatch

import (
	_init_ "github.com/aws/aws-cdk-go/awscdk/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk"
	"github.com/aws/constructs-go/constructs/v3"
)

// An alarm on a CloudWatch metric.
//
// Example:
//   import cloudwatch "github.com/aws/aws-cdk-go/awscdk"
//
//   var alias alias
//
//   // or add alarms to an existing group
//   var blueGreenAlias alias
//
//   alarm := cloudwatch.NewAlarm(this, jsii.String("Errors"), &alarmProps{
//   	comparisonOperator: cloudwatch.comparisonOperator_GREATER_THAN_THRESHOLD,
//   	threshold: jsii.Number(1),
//   	evaluationPeriods: jsii.Number(1),
//   	metric: alias.metricErrors(),
//   })
//   deploymentGroup := codedeploy.NewLambdaDeploymentGroup(this, jsii.String("BlueGreenDeployment"), &lambdaDeploymentGroupProps{
//   	alias: alias,
//   	deploymentConfig: codedeploy.lambdaDeploymentConfig_LINEAR_10PERCENT_EVERY_1MINUTE(),
//   	alarms: []iAlarm{
//   		alarm,
//   	},
//   })
//   deploymentGroup.addAlarm(cloudwatch.NewAlarm(this, jsii.String("BlueGreenErrors"), &alarmProps{
//   	comparisonOperator: cloudwatch.*comparisonOperator_GREATER_THAN_THRESHOLD,
//   	threshold: jsii.Number(1),
//   	evaluationPeriods: jsii.Number(1),
//   	metric: blueGreenAlias.metricErrors(),
//   }))
//
// Experimental.
type Alarm interface {
	AlarmBase
	// Experimental.
	AlarmActionArns() *[]*string
	// Experimental.
	SetAlarmActionArns(val *[]*string)
	// ARN of this alarm.
	// Experimental.
	AlarmArn() *string
	// Name of this alarm.
	// Experimental.
	AlarmName() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed by the CDK
	// (generally, those created by creating new class instances like Role, Bucket, etc.),
	// this is always the same as the environment of the stack they belong to;
	// however, for imported resources
	// (those obtained from static methods like fromRoleArn, fromBucketName, etc.),
	// that might be different than the stack they were imported into.
	// Experimental.
	Env() *awscdk.ResourceEnvironment
	// Experimental.
	InsufficientDataActionArns() *[]*string
	// Experimental.
	SetInsufficientDataActionArns(val *[]*string)
	// The metric object this alarm was based on.
	// Experimental.
	Metric() IMetric
	// The construct tree node associated with this construct.
	// Experimental.
	Node() awscdk.ConstructNode
	// Experimental.
	OkActionArns() *[]*string
	// Experimental.
	SetOkActionArns(val *[]*string)
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//    cross-environment scenarios.
	// Experimental.
	PhysicalName() *string
	// The stack in which this resource is defined.
	// Experimental.
	Stack() awscdk.Stack
	// Trigger this action if the alarm fires.
	//
	// Typically the ARN of an SNS topic or ARN of an AutoScaling policy.
	// Experimental.
	AddAlarmAction(actions ...IAlarmAction)
	// Trigger this action if there is insufficient data to evaluate the alarm.
	//
	// Typically the ARN of an SNS topic or ARN of an AutoScaling policy.
	// Experimental.
	AddInsufficientDataAction(actions ...IAlarmAction)
	// Trigger this action if the alarm returns from breaching state into ok state.
	//
	// Typically the ARN of an SNS topic or ARN of an AutoScaling policy.
	// Experimental.
	AddOkAction(actions ...IAlarmAction)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	// Experimental.
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	// Experimental.
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	// Experimental.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	// Experimental.
	GetResourceNameAttribute(nameAttr *string) *string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	// Experimental.
	OnPrepare()
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	// Experimental.
	OnSynthesize(session constructs.ISynthesisSession)
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	// Experimental.
	OnValidate() *[]*string
	// Perform final modifications before synthesis.
	//
	// This method can be implemented by derived constructs in order to perform
	// final changes before synthesis. prepare() will be called after child
	// constructs have been prepared.
	//
	// This is an advanced framework feature. Only use this if you
	// understand the implications.
	// Experimental.
	Prepare()
	// AlarmRule indicating ALARM state for Alarm.
	// Experimental.
	RenderAlarmRule() *string
	// Allows this construct to emit artifacts into the cloud assembly during synthesis.
	//
	// This method is usually implemented by framework-level constructs such as `Stack` and `Asset`
	// as they participate in synthesizing the cloud assembly.
	// Experimental.
	Synthesize(session awscdk.ISynthesisSession)
	// Turn this alarm into a horizontal annotation.
	//
	// This is useful if you want to represent an Alarm in a non-AlarmWidget.
	// An `AlarmWidget` can directly show an alarm, but it can only show a
	// single alarm and no other metrics. Instead, you can convert the alarm to
	// a HorizontalAnnotation and add it as an annotation to another graph.
	//
	// This might be useful if:
	//
	// - You want to show multiple alarms inside a single graph, for example if
	//    you have both a "small margin/long period" alarm as well as a
	//    "large margin/short period" alarm.
	//
	// - You want to show an Alarm line in a graph with multiple metrics in it.
	// Experimental.
	ToAnnotation() *HorizontalAnnotation
	// Returns a string representation of this construct.
	// Experimental.
	ToString() *string
	// Validate the current construct.
	//
	// This method can be implemented by derived constructs in order to perform
	// validation logic. It is called on all constructs before synthesis.
	//
	// Returns: An array of validation error messages, or an empty array if the construct is valid.
	// Experimental.
	Validate() *[]*string
}

// The jsii proxy struct for Alarm
type jsiiProxy_Alarm struct {
	jsiiProxy_AlarmBase
}

func (j *jsiiProxy_Alarm) AlarmActionArns() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"alarmActionArns",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) AlarmArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"alarmArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) AlarmName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"alarmName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) Env() *awscdk.ResourceEnvironment {
	var returns *awscdk.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) InsufficientDataActionArns() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"insufficientDataActionArns",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) Metric() IMetric {
	var returns IMetric
	_jsii_.Get(
		j,
		"metric",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) Node() awscdk.ConstructNode {
	var returns awscdk.ConstructNode
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) OkActionArns() *[]*string {
	var returns *[]*string
	_jsii_.Get(
		j,
		"okActionArns",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_Alarm) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}


// Experimental.
func NewAlarm(scope constructs.Construct, id *string, props *AlarmProps) Alarm {
	_init_.Initialize()

	j := jsiiProxy_Alarm{}

	_jsii_.Create(
		"monocdk.aws_cloudwatch.Alarm",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

// Experimental.
func NewAlarm_Override(a Alarm, scope constructs.Construct, id *string, props *AlarmProps) {
	_init_.Initialize()

	_jsii_.Create(
		"monocdk.aws_cloudwatch.Alarm",
		[]interface{}{scope, id, props},
		a,
	)
}

func (j *jsiiProxy_Alarm) SetAlarmActionArns(val *[]*string) {
	_jsii_.Set(
		j,
		"alarmActionArns",
		val,
	)
}

func (j *jsiiProxy_Alarm) SetInsufficientDataActionArns(val *[]*string) {
	_jsii_.Set(
		j,
		"insufficientDataActionArns",
		val,
	)
}

func (j *jsiiProxy_Alarm) SetOkActionArns(val *[]*string) {
	_jsii_.Set(
		j,
		"okActionArns",
		val,
	)
}

// Import an existing CloudWatch alarm provided an ARN.
// Experimental.
func Alarm_FromAlarmArn(scope constructs.Construct, id *string, alarmArn *string) IAlarm {
	_init_.Initialize()

	var returns IAlarm

	_jsii_.StaticInvoke(
		"monocdk.aws_cloudwatch.Alarm",
		"fromAlarmArn",
		[]interface{}{scope, id, alarmArn},
		&returns,
	)

	return returns
}

// Return whether the given object is a Construct.
// Experimental.
func Alarm_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	var returns *bool

	_jsii_.StaticInvoke(
		"monocdk.aws_cloudwatch.Alarm",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
// Experimental.
func Alarm_IsResource(construct awscdk.IConstruct) *bool {
	_init_.Initialize()

	var returns *bool

	_jsii_.StaticInvoke(
		"monocdk.aws_cloudwatch.Alarm",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) AddAlarmAction(actions ...IAlarmAction) {
	args := []interface{}{}
	for _, a := range actions {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addAlarmAction",
		args,
	)
}

func (a *jsiiProxy_Alarm) AddInsufficientDataAction(actions ...IAlarmAction) {
	args := []interface{}{}
	for _, a := range actions {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addInsufficientDataAction",
		args,
	)
}

func (a *jsiiProxy_Alarm) AddOkAction(actions ...IAlarmAction) {
	args := []interface{}{}
	for _, a := range actions {
		args = append(args, a)
	}

	_jsii_.InvokeVoid(
		a,
		"addOkAction",
		args,
	)
}

func (a *jsiiProxy_Alarm) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	_jsii_.InvokeVoid(
		a,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (a *jsiiProxy_Alarm) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) GetResourceNameAttribute(nameAttr *string) *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) OnPrepare() {
	_jsii_.InvokeVoid(
		a,
		"onPrepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_Alarm) OnSynthesize(session constructs.ISynthesisSession) {
	_jsii_.InvokeVoid(
		a,
		"onSynthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_Alarm) OnValidate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"onValidate",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) Prepare() {
	_jsii_.InvokeVoid(
		a,
		"prepare",
		nil, // no parameters
	)
}

func (a *jsiiProxy_Alarm) RenderAlarmRule() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"renderAlarmRule",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) Synthesize(session awscdk.ISynthesisSession) {
	_jsii_.InvokeVoid(
		a,
		"synthesize",
		[]interface{}{session},
	)
}

func (a *jsiiProxy_Alarm) ToAnnotation() *HorizontalAnnotation {
	var returns *HorizontalAnnotation

	_jsii_.Invoke(
		a,
		"toAnnotation",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		a,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (a *jsiiProxy_Alarm) Validate() *[]*string {
	var returns *[]*string

	_jsii_.Invoke(
		a,
		"validate",
		nil, // no parameters
		&returns,
	)

	return returns
}

