package awsconnectcampaignsv2

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignMixinProps",
		reflect.TypeOf((*CfnCampaignMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin",
		reflect.TypeOf((*CfnCampaignPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnCampaignPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.AnswerMachineDetectionConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_AnswerMachineDetectionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.ChannelSubtypeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_ChannelSubtypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.CommunicationLimitProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_CommunicationLimitProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.CommunicationLimitsConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_CommunicationLimitsConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.CommunicationLimitsProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_CommunicationLimitsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.CommunicationTimeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_CommunicationTimeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.DailyHourProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_DailyHourProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.EmailChannelSubtypeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_EmailChannelSubtypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.EmailOutboundConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_EmailOutboundConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.EmailOutboundModeProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_EmailOutboundModeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.EntryLimitsConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_EntryLimitsConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.EventTriggerProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_EventTriggerProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.LocalTimeZoneConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_LocalTimeZoneConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.OpenHoursProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_OpenHoursProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.PredictiveConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_PredictiveConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.PreviewConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_PreviewConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.ProgressiveConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_ProgressiveConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.RestrictedPeriodProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_RestrictedPeriodProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.RestrictedPeriodsProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_RestrictedPeriodsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.ScheduleProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_ScheduleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.SmsChannelSubtypeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_SmsChannelSubtypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.SmsOutboundConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_SmsOutboundConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.SmsOutboundModeProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_SmsOutboundModeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.SourceProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_SourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TelephonyChannelSubtypeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TelephonyChannelSubtypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TelephonyOutboundConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TelephonyOutboundConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TelephonyOutboundModeProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TelephonyOutboundModeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TimeRangeProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TimeRangeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TimeWindowProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TimeWindowProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.TimeoutConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_TimeoutConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.WhatsAppChannelSubtypeConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_WhatsAppChannelSubtypeConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.WhatsAppOutboundConfigProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_WhatsAppOutboundConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_connectcampaignsv2.CfnCampaignPropsMixin.WhatsAppOutboundModeProperty",
		reflect.TypeOf((*CfnCampaignPropsMixin_WhatsAppOutboundModeProperty)(nil)).Elem(),
	)
}
