package mixinsawspipes

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipeMixinProps",
		reflect.TypeOf((*CfnPipeMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin",
		reflect.TypeOf((*CfnPipePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnPipePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__coreMixin)
			_jsii_.InitJsiiProxy(&j.Type__coreIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.AwsVpcConfigurationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_AwsVpcConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchArrayPropertiesProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchArrayPropertiesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchContainerOverridesProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchContainerOverridesProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchEnvironmentVariableProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchEnvironmentVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchJobDependencyProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchJobDependencyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchResourceRequirementProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchResourceRequirementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.BatchRetryStrategyProperty",
		reflect.TypeOf((*CfnPipePropsMixin_BatchRetryStrategyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.CapacityProviderStrategyItemProperty",
		reflect.TypeOf((*CfnPipePropsMixin_CapacityProviderStrategyItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.CloudwatchLogsLogDestinationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_CloudwatchLogsLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.DeadLetterConfigProperty",
		reflect.TypeOf((*CfnPipePropsMixin_DeadLetterConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.DimensionMappingProperty",
		reflect.TypeOf((*CfnPipePropsMixin_DimensionMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsContainerOverrideProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsContainerOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsEnvironmentFileProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsEnvironmentFileProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsEnvironmentVariableProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsEnvironmentVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsEphemeralStorageProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsEphemeralStorageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsInferenceAcceleratorOverrideProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsInferenceAcceleratorOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsResourceRequirementProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsResourceRequirementProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.EcsTaskOverrideProperty",
		reflect.TypeOf((*CfnPipePropsMixin_EcsTaskOverrideProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.FilterCriteriaProperty",
		reflect.TypeOf((*CfnPipePropsMixin_FilterCriteriaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.FilterProperty",
		reflect.TypeOf((*CfnPipePropsMixin_FilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.FirehoseLogDestinationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_FirehoseLogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.MQBrokerAccessCredentialsProperty",
		reflect.TypeOf((*CfnPipePropsMixin_MQBrokerAccessCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.MSKAccessCredentialsProperty",
		reflect.TypeOf((*CfnPipePropsMixin_MSKAccessCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.MultiMeasureAttributeMappingProperty",
		reflect.TypeOf((*CfnPipePropsMixin_MultiMeasureAttributeMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.MultiMeasureMappingProperty",
		reflect.TypeOf((*CfnPipePropsMixin_MultiMeasureMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.NetworkConfigurationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_NetworkConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeEnrichmentHttpParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeEnrichmentHttpParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeEnrichmentParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeEnrichmentParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeLogConfigurationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeLogConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceActiveMQBrokerParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceActiveMQBrokerParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceDynamoDBStreamParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceDynamoDBStreamParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceKinesisStreamParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceKinesisStreamParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceManagedStreamingKafkaParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceManagedStreamingKafkaParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceRabbitMQBrokerParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceRabbitMQBrokerParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceSelfManagedKafkaParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceSelfManagedKafkaParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeSourceSqsQueueParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeSourceSqsQueueParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetBatchJobParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetBatchJobParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetCloudWatchLogsParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetCloudWatchLogsParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetEcsTaskParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetEcsTaskParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetEventBridgeEventBusParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetEventBridgeEventBusParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetHttpParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetHttpParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetKinesisStreamParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetKinesisStreamParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetLambdaFunctionParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetLambdaFunctionParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetRedshiftDataParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetRedshiftDataParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetSageMakerPipelineParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetSageMakerPipelineParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetSqsQueueParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetSqsQueueParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetStateMachineParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetStateMachineParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PipeTargetTimestreamParametersProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PipeTargetTimestreamParametersProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PlacementConstraintProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PlacementConstraintProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.PlacementStrategyProperty",
		reflect.TypeOf((*CfnPipePropsMixin_PlacementStrategyProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.S3LogDestinationProperty",
		reflect.TypeOf((*CfnPipePropsMixin_S3LogDestinationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.SageMakerPipelineParameterProperty",
		reflect.TypeOf((*CfnPipePropsMixin_SageMakerPipelineParameterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.SelfManagedKafkaAccessConfigurationCredentialsProperty",
		reflect.TypeOf((*CfnPipePropsMixin_SelfManagedKafkaAccessConfigurationCredentialsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.SelfManagedKafkaAccessConfigurationVpcProperty",
		reflect.TypeOf((*CfnPipePropsMixin_SelfManagedKafkaAccessConfigurationVpcProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_pipes.mixins.CfnPipePropsMixin.SingleMeasureMappingProperty",
		reflect.TypeOf((*CfnPipePropsMixin_SingleMeasureMappingProperty)(nil)).Elem(),
	)
}
