package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsbedrockagentcore"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsec2"
)
type Type__awscdkResource = awscdk.Resource
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsbedrockagentcoreIApiKeyCredentialProviderRef = interfacesawsbedrockagentcore.IApiKeyCredentialProviderRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsbedrockagentcoreIBrowserCustomRef = interfacesawsbedrockagentcore.IBrowserCustomRef
type Type__interfacesawsbedrockagentcoreIBrowserProfileRef = interfacesawsbedrockagentcore.IBrowserProfileRef
type Type__interfacesawsbedrockagentcoreICodeInterpreterCustomRef = interfacesawsbedrockagentcore.ICodeInterpreterCustomRef
type Type__interfacesawsbedrockagentcoreIEvaluatorRef = interfacesawsbedrockagentcore.IEvaluatorRef
type Type__interfacesawsbedrockagentcoreIGatewayRef = interfacesawsbedrockagentcore.IGatewayRef
type Type__interfacesawsbedrockagentcoreIGatewayTargetRef = interfacesawsbedrockagentcore.IGatewayTargetRef
type Type__interfacesawsbedrockagentcoreIMemoryRef = interfacesawsbedrockagentcore.IMemoryRef
type Type__interfacesawsbedrockagentcoreIOAuth2CredentialProviderRef = interfacesawsbedrockagentcore.IOAuth2CredentialProviderRef
type Type__interfacesawsbedrockagentcoreIOnlineEvaluationConfigRef = interfacesawsbedrockagentcore.IOnlineEvaluationConfigRef
type Type__interfacesawsbedrockagentcoreIPolicyRef = interfacesawsbedrockagentcore.IPolicyRef
type Type__interfacesawsbedrockagentcoreIPolicyEngineRef = interfacesawsbedrockagentcore.IPolicyEngineRef
type Type__interfacesawsbedrockagentcoreIRuntimeRef = interfacesawsbedrockagentcore.IRuntimeRef
type Type__interfacesawsbedrockagentcoreIRuntimeEndpointRef = interfacesawsbedrockagentcore.IRuntimeEndpointRef
type Type__interfacesawsbedrockagentcoreIWorkloadIdentityRef = interfacesawsbedrockagentcore.IWorkloadIdentityRef
type Type__awsiamIGrantable = awsiam.IGrantable
type Type__awscdkIResource = awscdk.IResource
type Type__awsec2IConnectable = awsec2.IConnectable
