package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsservicecatalogappregistry"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsservicecatalogappregistryIApplicationRef = interfacesawsservicecatalogappregistry.IApplicationRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsservicecatalogappregistryIAttributeGroupRef = interfacesawsservicecatalogappregistry.IAttributeGroupRef
type Type__interfacesawsservicecatalogappregistryIAttributeGroupAssociationRef = interfacesawsservicecatalogappregistry.IAttributeGroupAssociationRef
type Type__interfacesawsservicecatalogappregistryIResourceAssociationRef = interfacesawsservicecatalogappregistry.IResourceAssociationRef
