package previewawscodebuildevents

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail",
		reflect.TypeOf((*AWSAPICallViaCloudTrail)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_AWSAPICallViaCloudTrail{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.AWSAPICallViaCloudTrailProps",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_AWSAPICallViaCloudTrailProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Artifacts",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Artifacts)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Artifacts1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Artifacts1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Attributes",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Attributes)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Auth",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Auth)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Badge",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Badge)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Build",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Build)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.BuildPhase",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_BuildPhase)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Cache",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Cache)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Environment",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Environment)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Environment1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Environment1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.EnvironmentItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_EnvironmentItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.GitSubmodulesConfig",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_GitSubmodulesConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Logs",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Logs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Project",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Project)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.ProjectItem",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_ProjectItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.RequestParameters",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_RequestParameters)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.ResponseElements",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_ResponseElements)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.SessionContext",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SessionContext)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.SessionIssuer",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_SessionIssuer)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Source",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Source)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Source1",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Source1)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.UserIdentity",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_UserIdentity)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.VpcConfig",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_VpcConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSAPICallViaCloudTrail.Webhook",
		reflect.TypeOf((*AWSAPICallViaCloudTrail_Webhook)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSServiceEventViaCloudTrail",
		reflect.TypeOf((*AWSServiceEventViaCloudTrail)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_AWSServiceEventViaCloudTrail{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSServiceEventViaCloudTrail.AWSServiceEventViaCloudTrailProps",
		reflect.TypeOf((*AWSServiceEventViaCloudTrail_AWSServiceEventViaCloudTrailProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSServiceEventViaCloudTrail.ServiceEventDetails",
		reflect.TypeOf((*AWSServiceEventViaCloudTrail_ServiceEventDetails)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.AWSServiceEventViaCloudTrail.UserIdentity",
		reflect.TypeOf((*AWSServiceEventViaCloudTrail_UserIdentity)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange",
		reflect.TypeOf((*CodeBuildBuildPhaseChange)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_CodeBuildBuildPhaseChange{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.AdditionalInformation",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_AdditionalInformation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.AdditionalInformationItem",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_AdditionalInformationItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Artifact",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Artifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Auth",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Auth)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Cache",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Cache)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.CodeBuildBuildPhaseChangeProps",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_CodeBuildBuildPhaseChangeProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Environment",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Environment)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.EnvironmentItem",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_EnvironmentItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Logs",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Logs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.NetworkInterface",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_NetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.Source",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_Source)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.VpcConfig",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_VpcConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildPhaseChange.VpcConfigItem",
		reflect.TypeOf((*CodeBuildBuildPhaseChange_VpcConfigItem)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange",
		reflect.TypeOf((*CodeBuildBuildStateChange)(nil)).Elem(),
		nil, // no members
		func() interface{} {
			return &jsiiProxy_CodeBuildBuildStateChange{}
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.AdditionalInformation",
		reflect.TypeOf((*CodeBuildBuildStateChange_AdditionalInformation)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.AdditionalInformationItem",
		reflect.TypeOf((*CodeBuildBuildStateChange_AdditionalInformationItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Artifact",
		reflect.TypeOf((*CodeBuildBuildStateChange_Artifact)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Auth",
		reflect.TypeOf((*CodeBuildBuildStateChange_Auth)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Cache",
		reflect.TypeOf((*CodeBuildBuildStateChange_Cache)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.CodeBuildBuildStateChangeProps",
		reflect.TypeOf((*CodeBuildBuildStateChange_CodeBuildBuildStateChangeProps)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Environment",
		reflect.TypeOf((*CodeBuildBuildStateChange_Environment)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.EnvironmentItem",
		reflect.TypeOf((*CodeBuildBuildStateChange_EnvironmentItem)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Logs",
		reflect.TypeOf((*CodeBuildBuildStateChange_Logs)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.NetworkInterface",
		reflect.TypeOf((*CodeBuildBuildStateChange_NetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.Source",
		reflect.TypeOf((*CodeBuildBuildStateChange_Source)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.VpcConfig",
		reflect.TypeOf((*CodeBuildBuildStateChange_VpcConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/mixins-preview.aws_codebuild.events.CodeBuildBuildStateChange.VpcConfigItem",
		reflect.TypeOf((*CodeBuildBuildStateChange_VpcConfigItem)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/mixins-preview.aws_codebuild.events.ProjectEvents",
		reflect.TypeOf((*ProjectEvents)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "codeBuildBuildPhaseChangePattern", GoMethod: "CodeBuildBuildPhaseChangePattern"},
			_jsii_.MemberMethod{JsiiMethod: "codeBuildBuildStateChangePattern", GoMethod: "CodeBuildBuildStateChangePattern"},
		},
		func() interface{} {
			return &jsiiProxy_ProjectEvents{}
		},
	)
}
