package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsservicediscovery"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsservicediscoveryIHttpNamespaceRef = interfacesawsservicediscovery.IHttpNamespaceRef
type Type__awscdkITaggable = awscdk.ITaggable
type Type__interfacesawsservicediscoveryIInstanceRef = interfacesawsservicediscovery.IInstanceRef
type Type__interfacesawsservicediscoveryIPrivateDnsNamespaceRef = interfacesawsservicediscovery.IPrivateDnsNamespaceRef
type Type__interfacesawsservicediscoveryIPublicDnsNamespaceRef = interfacesawsservicediscovery.IPublicDnsNamespaceRef
type Type__interfacesawsservicediscoveryIServiceRef = interfacesawsservicediscovery.IServiceRef
type Type__awscdkResource = awscdk.Resource
type Type__awscdkIResource = awscdk.IResource
