package awsbedrockagentcore

import (
	_init_ "github.com/aws/aws-cdk-go/awscdk/v2/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbedrockagentcore/internal"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsiam"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsbedrockagentcore"
	"github.com/aws/constructs-go/constructs/v10"
)

// L2 construct for `AWS::BedrockAgentCore::WorkloadIdentity`.
//
// A workload identity is the stable identity of an agent in an AWS account. It ties together
// IAM roles, OAuth2 flows, API keys, and workload access tokens for consistent authentication
// across environments.
//
// Example:
//   agentcore.NewWorkloadIdentity(this, jsii.String("MyWorkloadIdentity"), &WorkloadIdentityProps{
//   	WorkloadIdentityName: jsii.String("customer-support-agent-prod"),
//   	AllowedResourceOauth2ReturnUrls: []*string{
//   		jsii.String("https://app.example.com/oauth/callback"),
//   	},
//   	Tags: map[string]*string{
//   		"team": jsii.String("agents"),
//   		"env": jsii.String("prod"),
//   	},
//   })
//
// See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrockagentcore-workloadidentity.html
//
type WorkloadIdentity interface {
	awscdk.Resource
	IWorkloadIdentity
	// Timestamp when the workload identity was created.
	CreatedTime() *string
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	Env() *interfaces.ResourceEnvironment
	// The principal to grant permissions to.
	GrantPrincipal() awsiam.IPrincipal
	// Timestamp when the workload identity was last updated.
	LastUpdatedTime() *string
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// The ARN of this workload identity.
	WorkloadIdentityArn() *string
	// The name of this workload identity.
	WorkloadIdentityName() *string
	// A reference to a WorkloadIdentity resource.
	WorkloadIdentityRef() *interfacesawsbedrockagentcore.WorkloadIdentityReference
	// Override the cross-stack reference strength for this resource.
	//
	// When set, any cross-stack reference to this resource will use the specified
	// mechanism instead of the global default determined by the
	// `@aws-cdk/core:defaultCrossStackReferences` context key. This is useful for
	// selectively weakening specific references to avoid the "deadly embrace" problem
	// without changing the app-wide default.
	ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength)
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// [disable-awslint:no-grants].
	Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant
	// [disable-awslint:no-grants].
	GrantAdmin(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	GrantFullAccess(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	GrantRead(grantee awsiam.IGrantable) awsiam.Grant
	// [disable-awslint:no-grants].
	GrantUse(grantee awsiam.IGrantable) awsiam.Grant
	// Returns a string representation of this construct.
	ToString() *string
	// Applies one or more mixins to this construct.
	//
	// Mixins are applied in order. The list of constructs is captured at the
	// start of the call, so constructs added by a mixin will not be visited.
	// Use multiple `with()` calls if subsequent mixins should apply to added
	// constructs.
	With(mixins ...constructs.IMixin) constructs.IConstruct
}

// The jsii proxy struct for WorkloadIdentity
type jsiiProxy_WorkloadIdentity struct {
	internal.Type__awscdkResource
	jsiiProxy_IWorkloadIdentity
}

func (j *jsiiProxy_WorkloadIdentity) CreatedTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"createdTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) GrantPrincipal() awsiam.IPrincipal {
	var returns awsiam.IPrincipal
	_jsii_.Get(
		j,
		"grantPrincipal",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) LastUpdatedTime() *string {
	var returns *string
	_jsii_.Get(
		j,
		"lastUpdatedTime",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) WorkloadIdentityArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workloadIdentityArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) WorkloadIdentityName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"workloadIdentityName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_WorkloadIdentity) WorkloadIdentityRef() *interfacesawsbedrockagentcore.WorkloadIdentityReference {
	var returns *interfacesawsbedrockagentcore.WorkloadIdentityReference
	_jsii_.Get(
		j,
		"workloadIdentityRef",
		&returns,
	)
	return returns
}


func NewWorkloadIdentity(scope constructs.Construct, id *string, props *WorkloadIdentityProps) WorkloadIdentity {
	_init_.Initialize()

	if err := validateNewWorkloadIdentityParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_WorkloadIdentity{}

	_jsii_.Create(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewWorkloadIdentity_Override(w WorkloadIdentity, scope constructs.Construct, id *string, props *WorkloadIdentityProps) {
	_init_.Initialize()

	_jsii_.Create(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		[]interface{}{scope, id, props},
		w,
	)
}

// Import an existing workload identity.
func WorkloadIdentity_FromWorkloadIdentityAttributes(scope constructs.Construct, id *string, attrs *WorkloadIdentityAttributes) IWorkloadIdentity {
	_init_.Initialize()

	if err := validateWorkloadIdentity_FromWorkloadIdentityAttributesParameters(scope, id, attrs); err != nil {
		panic(err)
	}
	var returns IWorkloadIdentity

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		"fromWorkloadIdentityAttributes",
		[]interface{}{scope, id, attrs},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func WorkloadIdentity_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateWorkloadIdentity_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func WorkloadIdentity_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkloadIdentity_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func WorkloadIdentity_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateWorkloadIdentity_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func WorkloadIdentity_PROPERTY_INJECTION_ID() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"aws-cdk-lib.aws_bedrockagentcore.WorkloadIdentity",
		"PROPERTY_INJECTION_ID",
		&returns,
	)
	return returns
}

func (w *jsiiProxy_WorkloadIdentity) ApplyCrossStackReferenceStrength(strength awscdk.ReferenceStrength) {
	if err := w.validateApplyCrossStackReferenceStrengthParameters(strength); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyCrossStackReferenceStrength",
		[]interface{}{strength},
	)
}

func (w *jsiiProxy_WorkloadIdentity) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := w.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		w,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (w *jsiiProxy_WorkloadIdentity) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := w.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GetResourceNameAttribute(nameAttr *string) *string {
	if err := w.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		w,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) Grant(grantee awsiam.IGrantable, actions ...*string) awsiam.Grant {
	if err := w.validateGrantParameters(grantee); err != nil {
		panic(err)
	}
	args := []interface{}{grantee}
	for _, a := range actions {
		args = append(args, a)
	}

	var returns awsiam.Grant

	_jsii_.Invoke(
		w,
		"grant",
		args,
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GrantAdmin(grantee awsiam.IGrantable) awsiam.Grant {
	if err := w.validateGrantAdminParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		w,
		"grantAdmin",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GrantFullAccess(grantee awsiam.IGrantable) awsiam.Grant {
	if err := w.validateGrantFullAccessParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		w,
		"grantFullAccess",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GrantRead(grantee awsiam.IGrantable) awsiam.Grant {
	if err := w.validateGrantReadParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		w,
		"grantRead",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) GrantUse(grantee awsiam.IGrantable) awsiam.Grant {
	if err := w.validateGrantUseParameters(grantee); err != nil {
		panic(err)
	}
	var returns awsiam.Grant

	_jsii_.Invoke(
		w,
		"grantUse",
		[]interface{}{grantee},
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		w,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (w *jsiiProxy_WorkloadIdentity) With(mixins ...constructs.IMixin) constructs.IConstruct {
	args := []interface{}{}
	for _, a := range mixins {
		args = append(args, a)
	}

	var returns constructs.IConstruct

	_jsii_.Invoke(
		w,
		"with",
		args,
		&returns,
	)

	return returns
}

