package internal
import (
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawscloudformation"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
)
type Type__constructsConstruct = constructs.Construct
type Type__interfacesawscloudformationICustomResourceRef = interfacesawscloudformation.ICustomResourceRef
type Type__interfacesawscloudformationIGuardHookRef = interfacesawscloudformation.IGuardHookRef
type Type__interfacesawscloudformationIHookDefaultVersionRef = interfacesawscloudformation.IHookDefaultVersionRef
type Type__interfacesawscloudformationIHookTypeConfigRef = interfacesawscloudformation.IHookTypeConfigRef
type Type__interfacesawscloudformationIHookVersionRef = interfacesawscloudformation.IHookVersionRef
type Type__interfacesawscloudformationILambdaHookRef = interfacesawscloudformation.ILambdaHookRef
type Type__interfacesawscloudformationIMacroRef = interfacesawscloudformation.IMacroRef
type Type__interfacesawscloudformationIModuleDefaultVersionRef = interfacesawscloudformation.IModuleDefaultVersionRef
type Type__interfacesawscloudformationIModuleVersionRef = interfacesawscloudformation.IModuleVersionRef
type Type__interfacesawscloudformationIPublicTypeVersionRef = interfacesawscloudformation.IPublicTypeVersionRef
type Type__interfacesawscloudformationIPublisherRef = interfacesawscloudformation.IPublisherRef
type Type__interfacesawscloudformationIResourceDefaultVersionRef = interfacesawscloudformation.IResourceDefaultVersionRef
type Type__interfacesawscloudformationIResourceVersionRef = interfacesawscloudformation.IResourceVersionRef
type Type__interfacesawscloudformationIStackRef = interfacesawscloudformation.IStackRef
type Type__interfacesawscloudformationIStackSetRef = interfacesawscloudformation.IStackSetRef
type Type__interfacesawscloudformationITypeActivationRef = interfacesawscloudformation.ITypeActivationRef
type Type__interfacesawscloudformationIWaitConditionRef = interfacesawscloudformation.IWaitConditionRef
type Type__interfacesawscloudformationIWaitConditionHandleRef = interfacesawscloudformation.IWaitConditionHandleRef
type Type__constructsIConstruct = constructs.IConstruct
type Type__interfacesIEnvironmentAware = interfaces.IEnvironmentAware
