package awsbedrock

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentAliasMixinProps",
		reflect.TypeOf((*CfnAgentAliasMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentAliasPropsMixin",
		reflect.TypeOf((*CfnAgentAliasPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnAgentAliasPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentAliasPropsMixin.AgentAliasHistoryEventProperty",
		reflect.TypeOf((*CfnAgentAliasPropsMixin_AgentAliasHistoryEventProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentAliasPropsMixin.AgentAliasRoutingConfigurationListItemProperty",
		reflect.TypeOf((*CfnAgentAliasPropsMixin_AgentAliasRoutingConfigurationListItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentMixinProps",
		reflect.TypeOf((*CfnAgentMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin",
		reflect.TypeOf((*CfnAgentPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnAgentPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.APISchemaProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_APISchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.ActionGroupExecutorProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_ActionGroupExecutorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.AgentActionGroupProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_AgentActionGroupProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.AgentCollaboratorProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_AgentCollaboratorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.AgentDescriptorProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_AgentDescriptorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.AgentKnowledgeBaseProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_AgentKnowledgeBaseProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.CustomOrchestrationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_CustomOrchestrationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.FunctionProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_FunctionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.FunctionSchemaProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_FunctionSchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.GuardrailConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_GuardrailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.InferenceConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_InferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.MemoryConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_MemoryConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.OrchestrationExecutorProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_OrchestrationExecutorProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.ParameterDetailProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_ParameterDetailProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.PromptConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_PromptConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.PromptOverrideConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_PromptOverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.S3IdentifierProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_S3IdentifierProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAgentPropsMixin.SessionSummaryConfigurationProperty",
		reflect.TypeOf((*CfnAgentPropsMixin_SessionSummaryConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnApplicationInferenceProfileMixinProps",
		reflect.TypeOf((*CfnApplicationInferenceProfileMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnApplicationInferenceProfilePropsMixin",
		reflect.TypeOf((*CfnApplicationInferenceProfilePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnApplicationInferenceProfilePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnApplicationInferenceProfilePropsMixin.InferenceProfileModelProperty",
		reflect.TypeOf((*CfnApplicationInferenceProfilePropsMixin_InferenceProfileModelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnApplicationInferenceProfilePropsMixin.InferenceProfileModelSourceProperty",
		reflect.TypeOf((*CfnApplicationInferenceProfilePropsMixin_InferenceProfileModelSourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyMixinProps",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnAutomatedReasoningPolicyPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin.PolicyDefinitionProperty",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin_PolicyDefinitionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin.PolicyDefinitionRuleProperty",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin_PolicyDefinitionRuleProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin.PolicyDefinitionTypeProperty",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin_PolicyDefinitionTypeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin.PolicyDefinitionTypeValueProperty",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin_PolicyDefinitionTypeValueProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyPropsMixin.PolicyDefinitionVariableProperty",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyPropsMixin_PolicyDefinitionVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyVersionMixinProps",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyVersionMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnAutomatedReasoningPolicyVersionPropsMixin",
		reflect.TypeOf((*CfnAutomatedReasoningPolicyVersionPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnAutomatedReasoningPolicyVersionPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnBlueprintMixinProps",
		reflect.TypeOf((*CfnBlueprintMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnBlueprintPropsMixin",
		reflect.TypeOf((*CfnBlueprintPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnBlueprintPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectMixinProps",
		reflect.TypeOf((*CfnDataAutomationProjectMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnDataAutomationProjectPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioExtractionCategoryProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioExtractionCategoryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioExtractionCategoryTypeConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioExtractionCategoryTypeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioLanguageConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioLanguageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioOverrideConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioOverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioStandardExtractionProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioStandardExtractionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioStandardGenerativeFieldProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioStandardGenerativeFieldProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.AudioStandardOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_AudioStandardOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.BlueprintItemProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_BlueprintItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ChannelLabelingConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ChannelLabelingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.CustomOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_CustomOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentBoundingBoxProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentBoundingBoxProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentExtractionGranularityProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentExtractionGranularityProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentOutputAdditionalFileFormatProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentOutputAdditionalFileFormatProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentOutputFormatProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentOutputFormatProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentOutputTextFormatProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentOutputTextFormatProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentOverrideConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentOverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentStandardExtractionProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentStandardExtractionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentStandardGenerativeFieldProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentStandardGenerativeFieldProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.DocumentStandardOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_DocumentStandardOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageBoundingBoxProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageBoundingBoxProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageExtractionCategoryProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageExtractionCategoryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageOverrideConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageOverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageStandardExtractionProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageStandardExtractionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageStandardGenerativeFieldProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageStandardGenerativeFieldProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ImageStandardOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ImageStandardOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ModalityProcessingConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ModalityProcessingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.ModalityRoutingConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_ModalityRoutingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.OverrideConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_OverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.PIIEntitiesConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_PIIEntitiesConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.SensitiveDataConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_SensitiveDataConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.SpeakerLabelingConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_SpeakerLabelingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.SplitterConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_SplitterConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.StandardOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_StandardOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.TranscriptConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_TranscriptConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoBoundingBoxProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoBoundingBoxProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoExtractionCategoryProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoExtractionCategoryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoOverrideConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoOverrideConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoStandardExtractionProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoStandardExtractionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoStandardGenerativeFieldProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoStandardGenerativeFieldProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataAutomationProjectPropsMixin.VideoStandardOutputConfigurationProperty",
		reflect.TypeOf((*CfnDataAutomationProjectPropsMixin_VideoStandardOutputConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourceMixinProps",
		reflect.TypeOf((*CfnDataSourceMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin",
		reflect.TypeOf((*CfnDataSourcePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnDataSourcePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.BedrockDataAutomationConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_BedrockDataAutomationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.BedrockFoundationModelConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_BedrockFoundationModelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.BedrockFoundationModelContextEnrichmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_BedrockFoundationModelContextEnrichmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ChunkingConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ChunkingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ConfluenceCrawlerConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceCrawlerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ConfluenceDataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceDataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ConfluenceSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ConfluenceSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ContextEnrichmentConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ContextEnrichmentConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.CrawlFilterConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_CrawlFilterConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.CustomTransformationConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_CustomTransformationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.DataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_DataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.EnrichmentStrategyConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_EnrichmentStrategyConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.FixedSizeChunkingConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_FixedSizeChunkingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.HierarchicalChunkingConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_HierarchicalChunkingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.HierarchicalChunkingLevelConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_HierarchicalChunkingLevelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.IntermediateStorageProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_IntermediateStorageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ParsingConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ParsingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ParsingPromptProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ParsingPromptProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.PatternObjectFilterConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_PatternObjectFilterConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.PatternObjectFilterProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_PatternObjectFilterProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.S3DataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_S3DataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.S3LocationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_S3LocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SalesforceCrawlerConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceCrawlerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SalesforceDataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceDataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SalesforceSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SalesforceSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SeedUrlProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SeedUrlProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SemanticChunkingConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SemanticChunkingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.ServerSideEncryptionConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_ServerSideEncryptionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SharePointCrawlerConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SharePointCrawlerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SharePointDataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SharePointDataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.SharePointSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_SharePointSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.TransformationFunctionProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_TransformationFunctionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.TransformationLambdaConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_TransformationLambdaConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.TransformationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_TransformationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.UrlConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_UrlConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.VectorIngestionConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_VectorIngestionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.WebCrawlerConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.WebCrawlerLimitsProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebCrawlerLimitsProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.WebDataSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebDataSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnDataSourcePropsMixin.WebSourceConfigurationProperty",
		reflect.TypeOf((*CfnDataSourcePropsMixin_WebSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowAliasMixinProps",
		reflect.TypeOf((*CfnFlowAliasMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowAliasPropsMixin",
		reflect.TypeOf((*CfnFlowAliasPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnFlowAliasPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowAliasPropsMixin.FlowAliasConcurrencyConfigurationProperty",
		reflect.TypeOf((*CfnFlowAliasPropsMixin_FlowAliasConcurrencyConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowAliasPropsMixin.FlowAliasRoutingConfigurationListItemProperty",
		reflect.TypeOf((*CfnFlowAliasPropsMixin_FlowAliasRoutingConfigurationListItemProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowMixinProps",
		reflect.TypeOf((*CfnFlowMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin",
		reflect.TypeOf((*CfnFlowPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnFlowPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.AgentFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_AgentFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.ConditionFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_ConditionFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FieldForRerankingProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FieldForRerankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowConditionProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowConditionalConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowConditionalConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowConnectionProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowConnectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowDataConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowDataConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowDefinitionProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowDefinitionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowNodeInputProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowNodeInputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowNodeOutputProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowNodeOutputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowNodeProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowNodeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.FlowValidationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_FlowValidationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.GuardrailConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_GuardrailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.InlineCodeFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_InlineCodeFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.KnowledgeBaseFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_KnowledgeBaseFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.KnowledgeBaseOrchestrationConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_KnowledgeBaseOrchestrationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.KnowledgeBasePromptTemplateProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_KnowledgeBasePromptTemplateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.LambdaFunctionFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_LambdaFunctionFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.LexFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_LexFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.LoopControllerFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_LoopControllerFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.LoopFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_LoopFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.MetadataConfigurationForRerankingProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_MetadataConfigurationForRerankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PerformanceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PerformanceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptFlowNodeInlineConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptFlowNodeInlineConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptFlowNodeResourceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptFlowNodeResourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptFlowNodeSourceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptFlowNodeSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptInferenceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptInputVariableProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptInputVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptModelInferenceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptModelInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.PromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_PromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.RerankingMetadataSelectiveModeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_RerankingMetadataSelectiveModeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.RetrievalFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_RetrievalFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.RetrievalFlowNodeS3ConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_RetrievalFlowNodeS3ConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.RetrievalFlowNodeServiceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_RetrievalFlowNodeServiceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.S3LocationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_S3LocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.StorageFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_StorageFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.StorageFlowNodeS3ConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_StorageFlowNodeS3ConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.StorageFlowNodeServiceConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_StorageFlowNodeServiceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.TextPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_TextPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.VectorSearchBedrockRerankingConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_VectorSearchBedrockRerankingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.VectorSearchBedrockRerankingModelConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_VectorSearchBedrockRerankingModelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowPropsMixin.VectorSearchRerankingConfigurationProperty",
		reflect.TypeOf((*CfnFlowPropsMixin_VectorSearchRerankingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionMixinProps",
		reflect.TypeOf((*CfnFlowVersionMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin",
		reflect.TypeOf((*CfnFlowVersionPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnFlowVersionPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.AgentFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_AgentFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.ConditionFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_ConditionFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FieldForRerankingProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FieldForRerankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowConditionProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowConditionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowConditionalConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowConditionalConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowConnectionProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowConnectionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowDataConnectionConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowDataConnectionConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowDefinitionProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowDefinitionProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowNodeInputProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowNodeInputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowNodeOutputProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowNodeOutputProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.FlowNodeProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_FlowNodeProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.GuardrailConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_GuardrailConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.InlineCodeFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_InlineCodeFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.KnowledgeBaseFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_KnowledgeBaseFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.KnowledgeBaseOrchestrationConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_KnowledgeBaseOrchestrationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.KnowledgeBasePromptTemplateProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_KnowledgeBasePromptTemplateProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.LambdaFunctionFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_LambdaFunctionFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.LexFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_LexFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.LoopControllerFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_LoopControllerFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.LoopFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_LoopFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.MetadataConfigurationForRerankingProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_MetadataConfigurationForRerankingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PerformanceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PerformanceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptFlowNodeInlineConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptFlowNodeInlineConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptFlowNodeResourceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptFlowNodeResourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptFlowNodeSourceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptFlowNodeSourceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptInferenceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptInputVariableProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptInputVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptModelInferenceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptModelInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.PromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_PromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.RerankingMetadataSelectiveModeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_RerankingMetadataSelectiveModeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.RetrievalFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_RetrievalFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.RetrievalFlowNodeS3ConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_RetrievalFlowNodeS3ConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.RetrievalFlowNodeServiceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_RetrievalFlowNodeServiceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.StorageFlowNodeConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_StorageFlowNodeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.StorageFlowNodeS3ConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_StorageFlowNodeS3ConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.StorageFlowNodeServiceConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_StorageFlowNodeServiceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.TextPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_TextPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.VectorSearchBedrockRerankingConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_VectorSearchBedrockRerankingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.VectorSearchBedrockRerankingModelConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_VectorSearchBedrockRerankingModelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnFlowVersionPropsMixin.VectorSearchRerankingConfigurationProperty",
		reflect.TypeOf((*CfnFlowVersionPropsMixin_VectorSearchRerankingConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailMixinProps",
		reflect.TypeOf((*CfnGuardrailMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin",
		reflect.TypeOf((*CfnGuardrailPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnGuardrailPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.AutomatedReasoningPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_AutomatedReasoningPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ContentFilterConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ContentFilterConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ContentFiltersTierConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ContentFiltersTierConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ContentPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ContentPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ContextualGroundingFilterConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ContextualGroundingFilterConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ContextualGroundingPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ContextualGroundingPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.GuardrailCrossRegionConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_GuardrailCrossRegionConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.ManagedWordsConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_ManagedWordsConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.PiiEntityConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_PiiEntityConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.RegexConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_RegexConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.SensitiveInformationPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_SensitiveInformationPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.TopicConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_TopicConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.TopicPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_TopicPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.TopicsTierConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_TopicsTierConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.WordConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_WordConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailPropsMixin.WordPolicyConfigProperty",
		reflect.TypeOf((*CfnGuardrailPropsMixin_WordPolicyConfigProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailVersionMixinProps",
		reflect.TypeOf((*CfnGuardrailVersionMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnGuardrailVersionPropsMixin",
		reflect.TypeOf((*CfnGuardrailVersionPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnGuardrailVersionPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnIntelligentPromptRouterMixinProps",
		reflect.TypeOf((*CfnIntelligentPromptRouterMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnIntelligentPromptRouterPropsMixin",
		reflect.TypeOf((*CfnIntelligentPromptRouterPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnIntelligentPromptRouterPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnIntelligentPromptRouterPropsMixin.PromptRouterTargetModelProperty",
		reflect.TypeOf((*CfnIntelligentPromptRouterPropsMixin_PromptRouterTargetModelProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnIntelligentPromptRouterPropsMixin.RoutingCriteriaProperty",
		reflect.TypeOf((*CfnIntelligentPromptRouterPropsMixin_RoutingCriteriaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBaseMixinProps",
		reflect.TypeOf((*CfnKnowledgeBaseMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnKnowledgeBasePropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.AudioConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_AudioConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.AudioSegmentationConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_AudioSegmentationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.BedrockEmbeddingModelConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_BedrockEmbeddingModelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.CuratedQueryProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_CuratedQueryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.EmbeddingModelConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_EmbeddingModelConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.KendraKnowledgeBaseConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_KendraKnowledgeBaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.KnowledgeBaseConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_KnowledgeBaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.MongoDbAtlasConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_MongoDbAtlasConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.MongoDbAtlasFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_MongoDbAtlasFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.NeptuneAnalyticsConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_NeptuneAnalyticsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.NeptuneAnalyticsFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_NeptuneAnalyticsFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.OpenSearchManagedClusterConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_OpenSearchManagedClusterConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.OpenSearchManagedClusterFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_OpenSearchManagedClusterFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.OpenSearchServerlessConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_OpenSearchServerlessConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.OpenSearchServerlessFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_OpenSearchServerlessFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.PineconeConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_PineconeConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.PineconeFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_PineconeFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.QueryGenerationColumnProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_QueryGenerationColumnProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.QueryGenerationConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_QueryGenerationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.QueryGenerationContextProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_QueryGenerationContextProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.QueryGenerationTableProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_QueryGenerationTableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RdsConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RdsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RdsFieldMappingProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RdsFieldMappingProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftProvisionedAuthConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftProvisionedAuthConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftProvisionedConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftProvisionedConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftQueryEngineAwsDataCatalogStorageConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftQueryEngineAwsDataCatalogStorageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftQueryEngineConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftQueryEngineConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftQueryEngineRedshiftStorageConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftQueryEngineRedshiftStorageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftQueryEngineStorageConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftQueryEngineStorageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftServerlessAuthConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftServerlessAuthConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.RedshiftServerlessConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_RedshiftServerlessConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.S3LocationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_S3LocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.S3VectorsConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_S3VectorsConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.SqlKnowledgeBaseConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_SqlKnowledgeBaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.StorageConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_StorageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.SupplementalDataStorageConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_SupplementalDataStorageConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.SupplementalDataStorageLocationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_SupplementalDataStorageLocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.VectorKnowledgeBaseConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_VectorKnowledgeBaseConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.VideoConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_VideoConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnKnowledgeBasePropsMixin.VideoSegmentationConfigurationProperty",
		reflect.TypeOf((*CfnKnowledgeBasePropsMixin_VideoSegmentationConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptMixinProps",
		reflect.TypeOf((*CfnPromptMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin",
		reflect.TypeOf((*CfnPromptPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnPromptPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.CachePointBlockProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_CachePointBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ChatPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ChatPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ContentBlockProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ContentBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.MessageProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_MessageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptAgentResourceProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptAgentResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptGenAiResourceProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptGenAiResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptInferenceConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptInputVariableProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptInputVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptMetadataEntryProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptMetadataEntryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptModelInferenceConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptModelInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.PromptVariantProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_PromptVariantProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.SpecificToolChoiceProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_SpecificToolChoiceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.SystemContentBlockProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_SystemContentBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.TextPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_TextPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.TextS3LocationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_TextS3LocationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ToolChoiceProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ToolChoiceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ToolConfigurationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ToolConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ToolInputSchemaProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ToolInputSchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ToolProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ToolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptPropsMixin.ToolSpecificationProperty",
		reflect.TypeOf((*CfnPromptPropsMixin_ToolSpecificationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionMixinProps",
		reflect.TypeOf((*CfnPromptVersionMixinProps)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin",
		reflect.TypeOf((*CfnPromptVersionPropsMixin)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "applyTo", GoMethod: "ApplyTo"},
			_jsii_.MemberProperty{JsiiProperty: "props", GoGetter: "Props"},
			_jsii_.MemberProperty{JsiiProperty: "strategy", GoGetter: "Strategy"},
			_jsii_.MemberMethod{JsiiMethod: "supports", GoMethod: "Supports"},
		},
		func() interface{} {
			j := jsiiProxy_CfnPromptVersionPropsMixin{}
			_jsii_.InitJsiiProxy(&j.Type__awscdkMixin)
			_jsii_.InitJsiiProxy(&j.Type__constructsIMixin)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.CachePointBlockProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_CachePointBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ChatPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ChatPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ContentBlockProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ContentBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.MessageProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_MessageProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptAgentResourceProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptAgentResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptGenAiResourceProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptGenAiResourceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptInferenceConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptInputVariableProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptInputVariableProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptMetadataEntryProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptMetadataEntryProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptModelInferenceConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptModelInferenceConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.PromptVariantProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_PromptVariantProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.SpecificToolChoiceProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_SpecificToolChoiceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.SystemContentBlockProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_SystemContentBlockProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.TextPromptTemplateConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_TextPromptTemplateConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ToolChoiceProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ToolChoiceProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ToolConfigurationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ToolConfigurationProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ToolInputSchemaProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ToolInputSchemaProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ToolProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ToolProperty)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@aws-cdk/cfn-property-mixins.aws_bedrock.CfnPromptVersionPropsMixin.ToolSpecificationProperty",
		reflect.TypeOf((*CfnPromptVersionPropsMixin_ToolSpecificationProperty)(nil)).Elem(),
	)
}
