package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsdirectconnect"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawsdirectconnectIConnectionRef = interfacesawsdirectconnect.IConnectionRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawsdirectconnectIDirectConnectGatewayRef = interfacesawsdirectconnect.IDirectConnectGatewayRef
type Type__interfacesawsdirectconnectIDirectConnectGatewayAssociationRef = interfacesawsdirectconnect.IDirectConnectGatewayAssociationRef
type Type__interfacesawsdirectconnectILagRef = interfacesawsdirectconnect.ILagRef
type Type__interfacesawsdirectconnectIPrivateVirtualInterfaceRef = interfacesawsdirectconnect.IPrivateVirtualInterfaceRef
type Type__interfacesawsdirectconnectIPublicVirtualInterfaceRef = interfacesawsdirectconnect.IPublicVirtualInterfaceRef
type Type__interfacesawsdirectconnectITransitVirtualInterfaceRef = interfacesawsdirectconnect.ITransitVirtualInterfaceRef
