package internal
import (
	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawspinpointemail"
)
type Type__awscdkCfnResource = awscdk.CfnResource
type Type__awscdkIInspectable = awscdk.IInspectable
type Type__interfacesawspinpointemailIConfigurationSetRef = interfacesawspinpointemail.IConfigurationSetRef
type Type__awscdkITaggableV2 = awscdk.ITaggableV2
type Type__interfacesawspinpointemailIConfigurationSetEventDestinationRef = interfacesawspinpointemail.IConfigurationSetEventDestinationRef
type Type__interfacesawspinpointemailIDedicatedIpPoolRef = interfacesawspinpointemail.IDedicatedIpPoolRef
type Type__interfacesawspinpointemailIIdentityRef = interfacesawspinpointemail.IIdentityRef
