package awsbackup

import (
	_init_ "github.com/aws/aws-cdk-go/awscdk/v2/jsii"
	_jsii_ "github.com/aws/jsii-runtime-go/runtime"

	"github.com/aws/aws-cdk-go/awscdk/v2"
	"github.com/aws/aws-cdk-go/awscdk/v2/awsbackup/internal"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces"
	"github.com/aws/aws-cdk-go/awscdk/v2/interfaces/interfacesawsbackup"
	"github.com/aws/constructs-go/constructs/v10"
)

// A backup plan.
//
// Example:
//   // Daily, weekly and monthly with 5 year retention
//   plan := backup.BackupPlan_DailyWeeklyMonthly5YearRetention(this, jsii.String("Plan"))
//
type BackupPlan interface {
	awscdk.Resource
	IBackupPlan
	// The ARN of the backup plan.
	BackupPlanArn() *string
	// The identifier of the backup plan.
	BackupPlanId() *string
	// A reference to a BackupPlan resource.
	BackupPlanRef() *interfacesawsbackup.BackupPlanReference
	// The backup vault where backups are stored if not defined at the rule level.
	BackupVault() IBackupVault
	// The environment this resource belongs to.
	//
	// For resources that are created and managed in a Stack (those created by
	// creating new class instances like `new Role()`, `new Bucket()`, etc.), this
	// is always the same as the environment of the stack they belong to.
	//
	// For referenced resources (those obtained from referencing methods like
	// `Role.fromRoleArn()`, `Bucket.fromBucketName()`, etc.), they might be
	// different than the stack they were imported into.
	Env() *interfaces.ResourceEnvironment
	// The tree node.
	Node() constructs.Node
	// Returns a string-encoded token that resolves to the physical name that should be passed to the CloudFormation resource.
	//
	// This value will resolve to one of the following:
	// - a concrete value (e.g. `"my-awesome-bucket"`)
	// - `undefined`, when a name should be generated by CloudFormation
	// - a concrete name generated automatically during synthesis, in
	//   cross-environment scenarios.
	PhysicalName() *string
	// The stack in which this resource is defined.
	Stack() awscdk.Stack
	// Version Id.
	VersionId() *string
	// Adds a rule to a plan.
	AddRule(rule BackupPlanRule)
	// Adds a selection to this plan.
	AddSelection(id *string, options *BackupSelectionOptions) BackupSelection
	// Apply the given removal policy to this resource.
	//
	// The Removal Policy controls what happens to this resource when it stops
	// being managed by CloudFormation, either because you've removed it from the
	// CDK application or because you've made a change that requires the resource
	// to be replaced.
	//
	// The resource can be deleted (`RemovalPolicy.DESTROY`), or left in your AWS
	// account for data recovery and cleanup later (`RemovalPolicy.RETAIN`).
	ApplyRemovalPolicy(policy awscdk.RemovalPolicy)
	GeneratePhysicalName() *string
	// Returns an environment-sensitive token that should be used for the resource's "ARN" attribute (e.g. `bucket.bucketArn`).
	//
	// Normally, this token will resolve to `arnAttr`, but if the resource is
	// referenced across environments, `arnComponents` will be used to synthesize
	// a concrete ARN with the resource's physical name. Make sure to reference
	// `this.physicalName` in `arnComponents`.
	GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string
	// Returns an environment-sensitive token that should be used for the resource's "name" attribute (e.g. `bucket.bucketName`).
	//
	// Normally, this token will resolve to `nameAttr`, but if the resource is
	// referenced across environments, it will be resolved to `this.physicalName`,
	// which will be a concrete name.
	GetResourceNameAttribute(nameAttr *string) *string
	// Returns a string representation of this construct.
	ToString() *string
}

// The jsii proxy struct for BackupPlan
type jsiiProxy_BackupPlan struct {
	internal.Type__awscdkResource
	jsiiProxy_IBackupPlan
}

func (j *jsiiProxy_BackupPlan) BackupPlanArn() *string {
	var returns *string
	_jsii_.Get(
		j,
		"backupPlanArn",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) BackupPlanId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"backupPlanId",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) BackupPlanRef() *interfacesawsbackup.BackupPlanReference {
	var returns *interfacesawsbackup.BackupPlanReference
	_jsii_.Get(
		j,
		"backupPlanRef",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) BackupVault() IBackupVault {
	var returns IBackupVault
	_jsii_.Get(
		j,
		"backupVault",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) Env() *interfaces.ResourceEnvironment {
	var returns *interfaces.ResourceEnvironment
	_jsii_.Get(
		j,
		"env",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) Node() constructs.Node {
	var returns constructs.Node
	_jsii_.Get(
		j,
		"node",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) PhysicalName() *string {
	var returns *string
	_jsii_.Get(
		j,
		"physicalName",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) Stack() awscdk.Stack {
	var returns awscdk.Stack
	_jsii_.Get(
		j,
		"stack",
		&returns,
	)
	return returns
}

func (j *jsiiProxy_BackupPlan) VersionId() *string {
	var returns *string
	_jsii_.Get(
		j,
		"versionId",
		&returns,
	)
	return returns
}


func NewBackupPlan(scope constructs.Construct, id *string, props *BackupPlanProps) BackupPlan {
	_init_.Initialize()

	if err := validateNewBackupPlanParameters(scope, id, props); err != nil {
		panic(err)
	}
	j := jsiiProxy_BackupPlan{}

	_jsii_.Create(
		"aws-cdk-lib.aws_backup.BackupPlan",
		[]interface{}{scope, id, props},
		&j,
	)

	return &j
}

func NewBackupPlan_Override(b BackupPlan, scope constructs.Construct, id *string, props *BackupPlanProps) {
	_init_.Initialize()

	_jsii_.Create(
		"aws-cdk-lib.aws_backup.BackupPlan",
		[]interface{}{scope, id, props},
		b,
	)
}

// Daily with 35 day retention.
func BackupPlan_Daily35DayRetention(scope constructs.Construct, id *string, backupVault interfacesawsbackup.IBackupVaultRef) BackupPlan {
	_init_.Initialize()

	if err := validateBackupPlan_Daily35DayRetentionParameters(scope, id); err != nil {
		panic(err)
	}
	var returns BackupPlan

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"daily35DayRetention",
		[]interface{}{scope, id, backupVault},
		&returns,
	)

	return returns
}

// Daily and monthly with 1 year retention.
func BackupPlan_DailyMonthly1YearRetention(scope constructs.Construct, id *string, backupVault interfacesawsbackup.IBackupVaultRef) BackupPlan {
	_init_.Initialize()

	if err := validateBackupPlan_DailyMonthly1YearRetentionParameters(scope, id); err != nil {
		panic(err)
	}
	var returns BackupPlan

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"dailyMonthly1YearRetention",
		[]interface{}{scope, id, backupVault},
		&returns,
	)

	return returns
}

// Daily, weekly and monthly with 5 year retention.
func BackupPlan_DailyWeeklyMonthly5YearRetention(scope constructs.Construct, id *string, backupVault interfacesawsbackup.IBackupVaultRef) BackupPlan {
	_init_.Initialize()

	if err := validateBackupPlan_DailyWeeklyMonthly5YearRetentionParameters(scope, id); err != nil {
		panic(err)
	}
	var returns BackupPlan

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"dailyWeeklyMonthly5YearRetention",
		[]interface{}{scope, id, backupVault},
		&returns,
	)

	return returns
}

// Daily, weekly and monthly with 7 year retention.
func BackupPlan_DailyWeeklyMonthly7YearRetention(scope constructs.Construct, id *string, backupVault interfacesawsbackup.IBackupVaultRef) BackupPlan {
	_init_.Initialize()

	if err := validateBackupPlan_DailyWeeklyMonthly7YearRetentionParameters(scope, id); err != nil {
		panic(err)
	}
	var returns BackupPlan

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"dailyWeeklyMonthly7YearRetention",
		[]interface{}{scope, id, backupVault},
		&returns,
	)

	return returns
}

// Import an existing backup plan.
func BackupPlan_FromBackupPlanId(scope constructs.Construct, id *string, backupPlanId *string) IBackupPlan {
	_init_.Initialize()

	if err := validateBackupPlan_FromBackupPlanIdParameters(scope, id, backupPlanId); err != nil {
		panic(err)
	}
	var returns IBackupPlan

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"fromBackupPlanId",
		[]interface{}{scope, id, backupPlanId},
		&returns,
	)

	return returns
}

// Checks if `x` is a construct.
//
// Use this method instead of `instanceof` to properly detect `Construct`
// instances, even when the construct library is symlinked.
//
// Explanation: in JavaScript, multiple copies of the `constructs` library on
// disk are seen as independent, completely different libraries. As a
// consequence, the class `Construct` in each copy of the `constructs` library
// is seen as a different class, and an instance of one class will not test as
// `instanceof` the other class. `npm install` will not create installations
// like this, but users may manually symlink construct libraries together or
// use a monorepo tool: in those cases, multiple copies of the `constructs`
// library can be accidentally installed, and `instanceof` will behave
// unpredictably. It is safest to avoid using `instanceof`, and using
// this type-testing method instead.
//
// Returns: true if `x` is an object created from a class which extends `Construct`.
func BackupPlan_IsConstruct(x interface{}) *bool {
	_init_.Initialize()

	if err := validateBackupPlan_IsConstructParameters(x); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"isConstruct",
		[]interface{}{x},
		&returns,
	)

	return returns
}

// Returns true if the construct was created by CDK, and false otherwise.
func BackupPlan_IsOwnedResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateBackupPlan_IsOwnedResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"isOwnedResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

// Check whether the given construct is a Resource.
func BackupPlan_IsResource(construct constructs.IConstruct) *bool {
	_init_.Initialize()

	if err := validateBackupPlan_IsResourceParameters(construct); err != nil {
		panic(err)
	}
	var returns *bool

	_jsii_.StaticInvoke(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"isResource",
		[]interface{}{construct},
		&returns,
	)

	return returns
}

func BackupPlan_PROPERTY_INJECTION_ID() *string {
	_init_.Initialize()
	var returns *string
	_jsii_.StaticGet(
		"aws-cdk-lib.aws_backup.BackupPlan",
		"PROPERTY_INJECTION_ID",
		&returns,
	)
	return returns
}

func (b *jsiiProxy_BackupPlan) AddRule(rule BackupPlanRule) {
	if err := b.validateAddRuleParameters(rule); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"addRule",
		[]interface{}{rule},
	)
}

func (b *jsiiProxy_BackupPlan) AddSelection(id *string, options *BackupSelectionOptions) BackupSelection {
	if err := b.validateAddSelectionParameters(id, options); err != nil {
		panic(err)
	}
	var returns BackupSelection

	_jsii_.Invoke(
		b,
		"addSelection",
		[]interface{}{id, options},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BackupPlan) ApplyRemovalPolicy(policy awscdk.RemovalPolicy) {
	if err := b.validateApplyRemovalPolicyParameters(policy); err != nil {
		panic(err)
	}
	_jsii_.InvokeVoid(
		b,
		"applyRemovalPolicy",
		[]interface{}{policy},
	)
}

func (b *jsiiProxy_BackupPlan) GeneratePhysicalName() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"generatePhysicalName",
		nil, // no parameters
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BackupPlan) GetResourceArnAttribute(arnAttr *string, arnComponents *awscdk.ArnComponents) *string {
	if err := b.validateGetResourceArnAttributeParameters(arnAttr, arnComponents); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		b,
		"getResourceArnAttribute",
		[]interface{}{arnAttr, arnComponents},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BackupPlan) GetResourceNameAttribute(nameAttr *string) *string {
	if err := b.validateGetResourceNameAttributeParameters(nameAttr); err != nil {
		panic(err)
	}
	var returns *string

	_jsii_.Invoke(
		b,
		"getResourceNameAttribute",
		[]interface{}{nameAttr},
		&returns,
	)

	return returns
}

func (b *jsiiProxy_BackupPlan) ToString() *string {
	var returns *string

	_jsii_.Invoke(
		b,
		"toString",
		nil, // no parameters
		&returns,
	)

	return returns
}

